// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(all(feature = "borsh", feature = "offchain"))]
use crate::sdk_core_offchain::borsh::{BorshDeserialize, BorshSerialize};
#[cfg(all(feature = "borsh", not(feature = "offchain")))]
use crate::sdk_core_cpi::borsh::{BorshDeserialize, BorshSerialize};

#[cfg(feature = "offchain")]
/// Field-for-field mirror of the real `pump_amm::Pool` account (13 fields,
/// 261 bytes with discriminator) — confirmed against a freshly re-dumped
/// `pump_amm.so` (see `docs/plan/fees-07-donation-relay-progress.md`).
/// `pump_fees`'s own `Pool` mirror depends on this exact layout matching;
/// any change here must be mirrored there too.
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize, BorshDeserialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_offchain::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Copy, Clone, Debug))]
#[cfg_attr(not(feature = "borsh"), repr(C))]
pub struct Pool {
    pub pool_bump: u8,
    pub index: u16,
    pub creator: crate::sdk_core_offchain::Address,
    pub base_mint: crate::sdk_core_offchain::Address,
    pub quote_mint: crate::sdk_core_offchain::Address,
    pub lp_mint: crate::sdk_core_offchain::Address,
    pub pool_base_token_account: crate::sdk_core_offchain::Address,
    pub pool_quote_token_account: crate::sdk_core_offchain::Address,
    pub coin_creator: crate::sdk_core_offchain::Address,
    pub lp_supply: u64,
    pub is_mayhem_mode: crate::sdk_core_offchain::Bool,
    pub is_cashback_coin: crate::sdk_core_offchain::Bool,
    pub virtual_quote_reserves: [u8; 16],
}

#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Zeroable for Pool {}
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Pod for Pool {}
#[cfg(feature = "cpi")]
/// Field-for-field mirror of the real `pump_amm::Pool` account (13 fields,
/// 261 bytes with discriminator) — confirmed against a freshly re-dumped
/// `pump_amm.so` (see `docs/plan/fees-07-donation-relay-progress.md`).
/// `pump_fees`'s own `Pool` mirror depends on this exact layout matching;
/// any change here must be mirrored there too.
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize, BorshDeserialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_cpi::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Copy, Clone, Debug))]
#[cfg_attr(not(feature = "borsh"), repr(C))]
pub struct PoolCpi {
    pub pool_bump: u8,
    pub index: u16,
    pub creator: crate::sdk_core_cpi::Address,
    pub base_mint: crate::sdk_core_cpi::Address,
    pub quote_mint: crate::sdk_core_cpi::Address,
    pub lp_mint: crate::sdk_core_cpi::Address,
    pub pool_base_token_account: crate::sdk_core_cpi::Address,
    pub pool_quote_token_account: crate::sdk_core_cpi::Address,
    pub coin_creator: crate::sdk_core_cpi::Address,
    pub lp_supply: u64,
    pub is_mayhem_mode: crate::sdk_core_cpi::Bool,
    pub is_cashback_coin: crate::sdk_core_cpi::Bool,
    pub virtual_quote_reserves: [u8; 16],
}

#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Zeroable for PoolCpi {}
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Pod for PoolCpi {}

/// 8-byte on-chain discriminator for `Pool` accounts.
pub const POOL_DISCRIMINATOR: [u8; 8] = [241, 154, 109, 4, 17, 177, 109, 188];
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
impl naclac_client::NaclacDecode for Pool {
    const DISCRIMINATOR: Option<[u8; 8]> = Some(POOL_DISCRIMINATOR);
    fn naclac_decode(data: &[u8]) -> Result<Self, naclac_client::NaclacClientError> {
        naclac_client::decode_pod_checked::<Self>(data, POOL_DISCRIMINATOR)
    }
}

#[cfg(feature = "offchain")]
#[cfg(feature = "borsh")]
impl naclac_client::NaclacDecode for Pool {
    const DISCRIMINATOR: Option<[u8; 8]> = Some(POOL_DISCRIMINATOR);
    fn naclac_decode(data: &[u8]) -> Result<Self, naclac_client::NaclacClientError> {
        naclac_client::decode_borsh_checked::<Self>(data, POOL_DISCRIMINATOR)
    }
}
#[cfg(feature = "offchain")]
/// Fetches and decodes a `Pool` account from the chain.
pub fn fetch_pool(
    provider: &naclac_client::NaclacProvider,
    address: &naclac_client::Address,
) -> Result<Pool, naclac_client::NaclacClientError> {
    let raw = provider.get_account_data(address)?;
    <Pool as naclac_client::NaclacDecode>::naclac_decode(&raw)
}

#[cfg(feature = "offchain")]
/// Fetches a `Pool` account. Returns `None` if the account does not exist.
pub fn fetch_maybe_pool(
    provider: &naclac_client::NaclacProvider,
    address: &naclac_client::Address,
) -> Result<Option<Pool>, naclac_client::NaclacClientError> {
    match fetch_pool(provider, address) {
        Ok(a) => Ok(Some(a)),
        Err(naclac_client::NaclacClientError::AccountNotFound(_)) => Ok(None),
        Err(e) => Err(e),
    }
}

#[cfg(feature = "offchain")]
/// Fetches and decodes every on-chain `Pool` account owned by `program_id`.
pub fn fetch_all_pool(
    provider: &naclac_client::NaclacProvider,
    program_id: &naclac_client::Address,
) -> Result<crate::sdk_core_offchain::Vec<(naclac_client::Address, Pool)>, naclac_client::NaclacClientError> {
    let raw_accounts = provider.get_program_accounts(program_id, Some(&POOL_DISCRIMINATOR))?;
    let mut results = crate::sdk_core_offchain::Vec::new();
    for (address, data) in raw_accounts {
        if let Ok(value) = <Pool as naclac_client::NaclacDecode>::naclac_decode(&data) {
            results.push((address, value));
        }
    }
    Ok(results)
}
