[package]
name = "naclac-macros"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Procedural macros for the Naclac Solana Framework"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["full", "extra-traits", "visit", "visit-mut"] }
sha2 = { workspace = true }

heck = "0.5.0"
solana-address = { workspace = true }
bs58 = { workspace = true }
toml = { workspace = true }

[features]
debug-mode = []
pinocchio = []
borsh = []