// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
pub const PROGRAM_ID: naclac_client::Address = naclac_client::Address::new_from_array([
    20, 88, 111, 82, 192, 221, 82, 247, 124, 107, 5, 182, 9, 17, 70, 227, 52, 164, 2, 149, 254, 121, 101, 59, 101, 17, 108, 95, 144, 36, 3, 220
]);

#[cfg(feature = "cpi")]
pub const PROGRAM_ID_CPI: crate::sdk_core_cpi::Address = crate::sdk_core_cpi::Address::new_from_array([
    20, 88, 111, 82, 192, 221, 82, 247, 124, 107, 5, 182, 9, 17, 70, 227, 52, 164, 2, 149, 254, 121, 101, 59, 101, 17, 108, 95, 144, 36, 3, 220
]);

pub const SEED_SMALL: &[u8] = &[115, 109, 97, 108, 108];
pub const SEED_BIG: &[u8] = &[98, 105, 103];
