// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
pub const PROGRAM_ID: naclac_client::Address = naclac_client::Address::new_from_array([
    173, 138, 22, 104, 165, 108, 89, 185, 59, 91, 165, 114, 218, 123, 246, 233, 101, 7, 116, 95, 143, 136, 238, 216, 145, 230, 78, 235, 87, 243, 242, 12
]);

#[cfg(feature = "cpi")]
pub const PROGRAM_ID_CPI: crate::sdk_core_cpi::Address = crate::sdk_core_cpi::Address::new_from_array([
    173, 138, 22, 104, 165, 108, 89, 185, 59, 91, 165, 114, 218, 123, 246, 233, 101, 7, 116, 95, 143, 136, 238, 216, 145, 230, 78, 235, 87, 243, 242, 12
]);

pub const AMM_CREATOR_VAULT_AUTHORITY_SEED: &[u8] = &[99, 114, 101, 97, 116, 111, 114, 95, 118, 97, 117, 108, 116];
#[cfg(feature = "offchain")]
pub const PUMP_PROGRAM_ID: naclac_client::Address = naclac_client::Address::new_from_array([219, 228, 38, 61, 197, 238, 49, 67, 254, 52, 90, 137, 137, 108, 51, 148, 9, 123, 135, 93, 203, 217, 165, 115, 223, 190, 144, 135, 242, 216, 223, 192]);
#[cfg(feature = "cpi")]
pub const PUMP_PROGRAM_ID_CPI: crate::sdk_core_cpi::Address = crate::sdk_core_cpi::Address::new_from_array([219, 228, 38, 61, 197, 238, 49, 67, 254, 52, 90, 137, 137, 108, 51, 148, 9, 123, 135, 93, 203, 217, 165, 115, 223, 190, 144, 135, 242, 216, 223, 192]);
pub const PUMP_CREATOR_VAULT_SEED: &[u8] = &[99, 114, 101, 97, 116, 111, 114, 45, 118, 97, 117, 108, 116];
pub const POOL_SEED: &[u8] = &[112, 111, 111, 108];
pub const POOL_LP_MINT_SEED: &[u8] = &[112, 111, 111, 108, 95, 108, 112, 95, 109, 105, 110, 116];
pub const GLOBAL_CONFIG_SEED: &[u8] = &[103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103];
pub const BOOST_VAULT_SEED: &[u8] = &[98, 111, 111, 115, 116, 95, 118, 97, 117, 108, 116];
