// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(all(feature = "borsh", feature = "offchain"))]
use crate::sdk_core_offchain::borsh::{BorshDeserialize, BorshSerialize};
#[cfg(all(feature = "borsh", not(feature = "offchain")))]
use crate::sdk_core_cpi::borsh::{BorshDeserialize, BorshSerialize};

#[cfg(feature = "offchain")]
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize, BorshDeserialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_offchain::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Copy, Clone, Debug))]
#[cfg_attr(not(feature = "borsh"), repr(C))]
pub struct CreatePoolArgs {
    pub index: u16,
    pub base_amount_in: u64,
    pub quote_amount_in: u64,
    pub coin_creator: crate::sdk_core_offchain::Address,
    pub is_mayhem_mode: crate::sdk_core_offchain::Bool,
    pub is_cashback_coin: crate::sdk_core_offchain::Bool,
    pub pool_bump: u8,
    pub lp_mint_bump: u8,
    pub user_base_token_account_bump: u8,
    pub user_quote_token_account_bump: u8,
    pub user_pool_token_account_bump: u8,
    pub pool_base_token_account_bump: u8,
    pub pool_quote_token_account_bump: u8,
}

#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Zeroable for CreatePoolArgs {}
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Pod for CreatePoolArgs {}

#[cfg(feature = "cpi")]
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize, BorshDeserialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_cpi::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Copy, Clone, Debug))]
#[cfg_attr(not(feature = "borsh"), repr(C))]
pub struct CreatePoolArgsCpi {
    pub index: u16,
    pub base_amount_in: u64,
    pub quote_amount_in: u64,
    pub coin_creator: crate::sdk_core_cpi::Address,
    pub is_mayhem_mode: crate::sdk_core_cpi::Bool,
    pub is_cashback_coin: crate::sdk_core_cpi::Bool,
    pub pool_bump: u8,
    pub lp_mint_bump: u8,
    pub user_base_token_account_bump: u8,
    pub user_quote_token_account_bump: u8,
    pub user_pool_token_account_bump: u8,
    pub pool_base_token_account_bump: u8,
    pub pool_quote_token_account_bump: u8,
}

#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Zeroable for CreatePoolArgsCpi {}
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Pod for CreatePoolArgsCpi {}

