// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#![cfg_attr(all(feature = "cpi", feature = "pinocchio"), no_std)]

#[cfg(feature = "cpi")]
pub use naclac_lang::prelude as sdk_core_cpi;
#[cfg(feature = "offchain")]
pub use naclac_client as sdk_core_offchain;

pub mod instructions;
pub mod types;

pub use instructions::*;
pub use types::*;

#[macro_export]
macro_rules! declare_id {
    ($id:expr) => {};
}

declare_id!("CfCmyXnF1To9ryX2g5Sj3X8yhpFopYxZFrgFf8fWVwU5");

#[cfg(feature = "cpi")]
#[derive(Clone, Copy)]
pub struct Metadata;

#[cfg(feature = "cpi")]
impl sdk_core_cpi::Id for Metadata {
    fn id() -> sdk_core_cpi::Address {
        sdk_core_cpi::Address::new_from_array([173, 57, 241, 2, 231, 82, 13, 70, 217, 254, 200, 237, 220, 165, 252, 188, 208, 201, 130, 2, 113, 38, 1, 239, 24, 21, 254, 30, 156, 126, 171, 106])
    }
}

