// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ProgramError {
    /// Signer does not match the authority this instruction requires -- which `Global` field that is varies per instruction, not always `authority` itself.
    NotAuthorized,
    /// Remaining accounts count doesn't match what this instruction expects
    NotEnoughRemainingAccounts,
    /// A remaining account's address doesn't match the expected shareholder
    ShareholderAccountMismatch,
    /// Only native-SOL creator vaults are supported here
    UnsupportedQuoteMint,
    /// The passed quote mint doesn't match the bonding curve's quote mint
    QuoteMintMismatch,
    /// Quote mint is not in the whitelist
    QuoteMintNotWhitelisted,
    /// Slippage tolerance exceeded
    SlippageExceeded,
    /// Math overflow
    MathOverflow,
    /// Missing or malformed fee data
    MissingFeesReturnData,
    /// Not enough tokens available to buy
    NotEnoughTokensToBuy,
    /// Fee recipient account is not rent-exempt
    FeeRecipientNotRentExempt,
    /// Invalid fee recipient
    InvalidFeeRecipient,
    /// Invalid buyback fee recipient
    InvalidBuybackFeeRecipient,
    /// Bonding curve is not complete
    NotComplete,
    /// Migration is disabled
    MigrateDisabled,
    /// Invalid withdraw authority
    InvalidWithdrawAuthority,
    /// Unsupported quote mint for migration
    UnsupportedQuoteMintForMigrate,
    /// Pool migration fee too high
    PoolMigrationFeeTooHigh,
    /// Minimum tokens out must be greater than zero
    ZeroMinTokensOut,
    /// Buy amount cannot be zero
    BuyZeroAmount,
    /// Sell amount cannot be zero
    SellZeroAmount,
    /// Quote mint whitelist is full
    QuoteMintWhitelistFull,
    /// Quote mint is already whitelisted
    QuoteMintAlreadyWhitelisted,
    /// Quote mint cannot be added or removed via whitelist (default or native SOL mint)
    QuoteMintNotEligibleForWhitelist,
    /// Create v2: quote token program must be legacy SPL Token
    InvalidQuoteTokenProgram,
    /// create_v2 is currently disabled by the admin
    CreateV2Disabled,
    /// Cashback is not enabled
    CashbackNotEnabled,
    /// Mayhem mode is not enabled by the admin
    MayhemModeDisabled,
    /// buyback fee recipients require exactly 8 remaining accounts (or none)
    WrongBuybackFeeRecipientsCount,
}

impl ProgramError {
    pub fn from_code(code: u32) -> Option<Self> {
        match code {
            6000 => Some(Self::NotAuthorized),
            6001 => Some(Self::NotEnoughRemainingAccounts),
            6002 => Some(Self::ShareholderAccountMismatch),
            6003 => Some(Self::UnsupportedQuoteMint),
            6004 => Some(Self::QuoteMintMismatch),
            6005 => Some(Self::QuoteMintNotWhitelisted),
            6006 => Some(Self::SlippageExceeded),
            6007 => Some(Self::MathOverflow),
            6008 => Some(Self::MissingFeesReturnData),
            6009 => Some(Self::NotEnoughTokensToBuy),
            6010 => Some(Self::FeeRecipientNotRentExempt),
            6011 => Some(Self::InvalidFeeRecipient),
            6012 => Some(Self::InvalidBuybackFeeRecipient),
            6013 => Some(Self::NotComplete),
            6014 => Some(Self::MigrateDisabled),
            6015 => Some(Self::InvalidWithdrawAuthority),
            6016 => Some(Self::UnsupportedQuoteMintForMigrate),
            6017 => Some(Self::PoolMigrationFeeTooHigh),
            6018 => Some(Self::ZeroMinTokensOut),
            6019 => Some(Self::BuyZeroAmount),
            6020 => Some(Self::SellZeroAmount),
            6021 => Some(Self::QuoteMintWhitelistFull),
            6022 => Some(Self::QuoteMintAlreadyWhitelisted),
            6023 => Some(Self::QuoteMintNotEligibleForWhitelist),
            6024 => Some(Self::InvalidQuoteTokenProgram),
            6025 => Some(Self::CreateV2Disabled),
            6026 => Some(Self::CashbackNotEnabled),
            6027 => Some(Self::MayhemModeDisabled),
            6028 => Some(Self::WrongBuybackFeeRecipientsCount),
            _ => None,
        }
    }

    pub fn message(&self) -> &'static str {
        match self {
            Self::NotAuthorized => "Signer does not match the authority this instruction requires -- which `Global` field that is varies per instruction, not always `authority` itself.",
            Self::NotEnoughRemainingAccounts => "Remaining accounts count doesn't match what this instruction expects",
            Self::ShareholderAccountMismatch => "A remaining account's address doesn't match the expected shareholder",
            Self::UnsupportedQuoteMint => "Only native-SOL creator vaults are supported here",
            Self::QuoteMintMismatch => "The passed quote mint doesn't match the bonding curve's quote mint",
            Self::QuoteMintNotWhitelisted => "Quote mint is not in the whitelist",
            Self::SlippageExceeded => "Slippage tolerance exceeded",
            Self::MathOverflow => "Math overflow",
            Self::MissingFeesReturnData => "Missing or malformed fee data",
            Self::NotEnoughTokensToBuy => "Not enough tokens available to buy",
            Self::FeeRecipientNotRentExempt => "Fee recipient account is not rent-exempt",
            Self::InvalidFeeRecipient => "Invalid fee recipient",
            Self::InvalidBuybackFeeRecipient => "Invalid buyback fee recipient",
            Self::NotComplete => "Bonding curve is not complete",
            Self::MigrateDisabled => "Migration is disabled",
            Self::InvalidWithdrawAuthority => "Invalid withdraw authority",
            Self::UnsupportedQuoteMintForMigrate => "Unsupported quote mint for migration",
            Self::PoolMigrationFeeTooHigh => "Pool migration fee too high",
            Self::ZeroMinTokensOut => "Minimum tokens out must be greater than zero",
            Self::BuyZeroAmount => "Buy amount cannot be zero",
            Self::SellZeroAmount => "Sell amount cannot be zero",
            Self::QuoteMintWhitelistFull => "Quote mint whitelist is full",
            Self::QuoteMintAlreadyWhitelisted => "Quote mint is already whitelisted",
            Self::QuoteMintNotEligibleForWhitelist => "Quote mint cannot be added or removed via whitelist (default or native SOL mint)",
            Self::InvalidQuoteTokenProgram => "Create v2: quote token program must be legacy SPL Token",
            Self::CreateV2Disabled => "create_v2 is currently disabled by the admin",
            Self::CashbackNotEnabled => "Cashback is not enabled",
            Self::MayhemModeDisabled => "Mayhem mode is not enabled by the admin",
            Self::WrongBuybackFeeRecipientsCount => "buyback fee recipients require exactly 8 remaining accounts (or none)",
        }
    }
}

