// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#![cfg_attr(all(feature = "cpi", feature = "pinocchio"), no_std)]

#[cfg(feature = "cpi")]
pub use naclac_lang::prelude as sdk_core_cpi;
#[cfg(feature = "offchain")]
pub use naclac_client as sdk_core_offchain;

pub mod instructions;
pub mod types;

pub use instructions::*;
pub use types::*;

#[macro_export]
macro_rules! declare_id {
    ($id:expr) => {};
}

declare_id!("AfERbyQZJP6FteX4WpwCKrRUqiNSNN7T3ak36ePoX2y");

#[cfg(feature = "cpi")]
#[derive(Clone, Copy)]
pub struct InterfaceBorsh;

#[cfg(feature = "cpi")]
impl sdk_core_cpi::Id for InterfaceBorsh {
    fn id() -> sdk_core_cpi::Address {
        sdk_core_cpi::Address::new_from_array([2, 121, 116, 170, 46, 35, 24, 143, 61, 242, 59, 66, 114, 228, 194, 127, 201, 158, 246, 150, 25, 120, 53, 31, 179, 17, 183, 140, 44, 163, 142, 154])
    }
}

