// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
#[cfg(feature = "borsh")]
use crate::sdk_core_offchain::borsh::BorshSerialize;
#[cfg(feature = "offchain")]
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_offchain::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Copy, Clone, Debug))]
#[cfg_attr(not(feature = "borsh"), repr(C, packed))]
pub struct CheckAmountIxArgs {
    pub amount: u64,
}

#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Zeroable for CheckAmountIxArgs {}
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Pod for CheckAmountIxArgs {}

#[cfg(feature = "cpi")]
#[cfg(feature = "borsh")]
use crate::sdk_core_cpi::borsh::BorshSerialize;
#[cfg(feature = "cpi")]
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_cpi::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Copy, Clone, Debug))]
#[cfg_attr(not(feature = "borsh"), repr(C, packed))]
pub struct CheckAmountCpiIxArgs {
    pub amount: u64,
}

#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Zeroable for CheckAmountCpiIxArgs {}
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Pod for CheckAmountCpiIxArgs {}

#[cfg(feature = "offchain")]
pub struct CheckAmountAccounts {
    pub payer: naclac_client::Address,
}

#[cfg(feature = "offchain")]
pub fn build_check_amount<'a>(
    provider: &'a naclac_client::NaclacProvider,
    program_id: naclac_client::Address,
    amount: u64,
    accounts: CheckAmountAccounts,
) -> naclac_client::InstructionBuilder<'a> {
    let mut ix_data = crate::sdk_core_offchain::vec![64, 134, 148, 88, 151, 6, 135, 30];
    let args = CheckAmountIxArgs {
        amount,
    };
    #[cfg(not(feature = "borsh"))]
    {
        ix_data.extend_from_slice(crate::sdk_core_offchain::bytemuck::bytes_of(&args));
    }
    #[cfg(feature = "borsh")]
    {
        crate::sdk_core_offchain::borsh::BorshSerialize::serialize(&args, &mut ix_data).unwrap();
    }
    naclac_client::InstructionBuilder::new(provider, program_id, ix_data)
        .account(naclac_client::AccountMeta { address: accounts.payer, is_signer: true, is_writable: false }, "payer")
}

#[cfg(feature = "cpi")]
pub struct CheckAmountCpiAccounts<'a> {
    pub payer: crate::sdk_core_cpi::CpiHandle<'a>,
}

#[cfg(feature = "cpi")]
pub struct CheckAmountCpiCall<'a> {
    pub accounts: CheckAmountCpiAccounts<'a>,
    pub amount: u64,
    pub signer_seeds: &'a [&'a [&'a [u8]]],
    pub remaining_accounts: &'a [(crate::sdk_core_cpi::AccountInfo, bool, bool)],
}

#[cfg(feature = "cpi")]
pub trait CheckAmountCpi<'info> {
    fn check_amount<'a>(
        &self,
        accounts: CheckAmountCpiAccounts<'a>,
        amount: u64
    ) -> crate::sdk_core_cpi::Result<()> {
        self.check_amount_with_remaining_accounts(CheckAmountCpiCall {
        accounts,
        amount,
        signer_seeds: &[],
        remaining_accounts: &[],
    })
    }

    fn check_amount_signed<'a>(
        &self,
        accounts: CheckAmountCpiAccounts<'a>,
        amount: u64,
        signer_seeds: &[&[&[u8]]]
    ) -> crate::sdk_core_cpi::Result<()> {
        self.check_amount_with_remaining_accounts(CheckAmountCpiCall {
        accounts,
        amount,
        signer_seeds,
        remaining_accounts: &[],
    })
    }

    fn check_amount_with_remaining_accounts<'a>(
        &self,
        call: CheckAmountCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()>;

}

#[cfg(feature = "cpi")]
impl<'info> CheckAmountCpi<'info> for crate::sdk_core_cpi::Program<crate::ErrorCodes> {
    fn check_amount_with_remaining_accounts<'a>(
        &self,
        call: CheckAmountCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()> {
        let CheckAmountCpiCall { accounts, amount, signer_seeds, remaining_accounts } = call;
        let args = CheckAmountCpiIxArgs {
            amount,
        };
        let mut ix_data = crate::sdk_core_cpi::Vec::new();
        ix_data.extend_from_slice(&[64, 134, 148, 88, 151, 6, 135, 30]);
        #[cfg(not(feature = "borsh"))]
        {
        ix_data.extend_from_slice(crate::sdk_core_cpi::bytemuck::bytes_of(&args));
        }
        #[cfg(feature = "borsh")]
        {
            crate::sdk_core_cpi::borsh::BorshSerialize::serialize(&args, &mut ix_data).unwrap();
        }
        #[cfg(feature = "pinocchio")]
        {
            let mut metas_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount>::uninit() }; 32];
            let mut idx = 0;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly_signer(accounts.payer.info.view.address()));
            idx += 1;
            for (acc, is_writable, is_signer) in remaining_accounts {
                if idx >= 32 { break; }
                let meta = if *is_writable {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(acc.view.address())
                    }
                } else {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(acc.view.address())
                    }
                };
                metas_arr[idx].write(meta);
                idx += 1;
            }
            let account_metas = unsafe { core::slice::from_raw_parts(metas_arr.as_ptr() as *const crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount, idx) };
            let program_id_address = self.address();
            let instruction = crate::sdk_core_cpi::pinocchio::instruction::InstructionView {
                program_id: program_id_address.as_address(),
                accounts: account_metas,
                data: &ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(accounts.payer);
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed_pinocchio_handles(&instruction, account_handles, signer_seeds)
        }
        #[cfg(not(feature = "pinocchio"))]
        {
            use crate::sdk_core_cpi::ToAddress;
            let mut account_metas = crate::sdk_core_cpi::vec![
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.payer.address(), true),
            ];
            for (acc, is_writable, is_signer) in remaining_accounts {
                let meta = if *is_writable {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new(acc.address(), *is_signer)
                } else {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(acc.address(), *is_signer)
                };
                account_metas.push(meta);
            }
            let instruction = ::naclac_lang::solana_program::instruction::Instruction {
                program_id: self.address(),
                accounts: account_metas,
                data: ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(accounts.payer);
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed(&instruction, account_handles, signer_seeds)
        }
    }
}

