// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
#[cfg(feature = "borsh")]
use crate::sdk_core_offchain::borsh::BorshSerialize;
#[cfg(feature = "offchain")]
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_offchain::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Copy, Clone, Debug))]
#[cfg_attr(not(feature = "borsh"), repr(C, packed))]
pub struct TouchConfigEntryBareBumpWithArgsIxArgs {
    pub is_pump_pool: crate::sdk_core_offchain::Bool,
    pub market_cap_lamports: u128,
    pub trade_size_lamports: u64,
    pub is_new_quote_mint: crate::sdk_core_offchain::Bool,
}

#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Zeroable for TouchConfigEntryBareBumpWithArgsIxArgs {}
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Pod for TouchConfigEntryBareBumpWithArgsIxArgs {}

#[cfg(feature = "cpi")]
#[cfg(feature = "borsh")]
use crate::sdk_core_cpi::borsh::BorshSerialize;
#[cfg(feature = "cpi")]
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_cpi::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Copy, Clone, Debug))]
#[cfg_attr(not(feature = "borsh"), repr(C, packed))]
pub struct TouchConfigEntryBareBumpWithArgsCpiIxArgs {
    pub is_pump_pool: crate::sdk_core_cpi::Bool,
    pub market_cap_lamports: u128,
    pub trade_size_lamports: u64,
    pub is_new_quote_mint: crate::sdk_core_cpi::Bool,
}

#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Zeroable for TouchConfigEntryBareBumpWithArgsCpiIxArgs {}
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Pod for TouchConfigEntryBareBumpWithArgsCpiIxArgs {}

#[cfg(feature = "offchain")]
pub struct TouchConfigEntryBareBumpWithArgsAccounts {
    /// SAFETY: only used as PDA seed material for `config_entry` below; never
    /// deserialized, invoked, or otherwise trusted for its own contents.
    pub config_program_id: naclac_client::Address,
    pub config_entry: naclac_client::Address,
}

#[cfg(feature = "offchain")]
pub fn build_touch_config_entry_bare_bump_with_args<'a>(
    provider: &'a naclac_client::NaclacProvider,
    program_id: naclac_client::Address,
    is_pump_pool: crate::sdk_core_offchain::Bool,
    market_cap_lamports: u128,
    trade_size_lamports: u64,
    is_new_quote_mint: crate::sdk_core_offchain::Bool,
    accounts: TouchConfigEntryBareBumpWithArgsAccounts,
) -> naclac_client::InstructionBuilder<'a> {
    let mut ix_data = crate::sdk_core_offchain::vec![69, 181, 74, 168, 31, 97, 37, 192];
    let args = TouchConfigEntryBareBumpWithArgsIxArgs {
        is_pump_pool,
        market_cap_lamports,
        trade_size_lamports,
        is_new_quote_mint,
    };
    #[cfg(not(feature = "borsh"))]
    {
        ix_data.extend_from_slice(crate::sdk_core_offchain::bytemuck::bytes_of(&args));
    }
    #[cfg(feature = "borsh")]
    {
        crate::sdk_core_offchain::borsh::BorshSerialize::serialize(&args, &mut ix_data).unwrap();
    }
    naclac_client::InstructionBuilder::new(provider, program_id, ix_data)
        .account(naclac_client::AccountMeta { address: accounts.config_program_id, is_signer: false, is_writable: false }, "config_program_id")
        .account(naclac_client::AccountMeta { address: accounts.config_entry, is_signer: false, is_writable: true }, "config_entry")
}

#[cfg(feature = "cpi")]
pub struct TouchConfigEntryBareBumpWithArgsCpiAccounts<'a> {
    /// SAFETY: only used as PDA seed material for `config_entry` below; never
    /// deserialized, invoked, or otherwise trusted for its own contents.
    pub config_program_id: crate::sdk_core_cpi::CpiHandle<'a>,
    pub config_entry: crate::sdk_core_cpi::CpiHandleMut<'a>,
}

#[cfg(feature = "cpi")]
pub struct TouchConfigEntryBareBumpWithArgsCpiCall<'a> {
    pub accounts: TouchConfigEntryBareBumpWithArgsCpiAccounts<'a>,
    pub is_pump_pool: crate::sdk_core_cpi::Bool,
    pub market_cap_lamports: u128,
    pub trade_size_lamports: u64,
    pub is_new_quote_mint: crate::sdk_core_cpi::Bool,
    pub signer_seeds: &'a [&'a [&'a [u8]]],
    pub remaining_accounts: &'a [(crate::sdk_core_cpi::AccountInfo, bool, bool)],
}

#[cfg(feature = "cpi")]
pub trait TouchConfigEntryBareBumpWithArgsCpi<'info> {
    fn touch_config_entry_bare_bump_with_args<'a>(
        &self,
        accounts: TouchConfigEntryBareBumpWithArgsCpiAccounts<'a>,
        is_pump_pool: crate::sdk_core_cpi::Bool,
        market_cap_lamports: u128,
        trade_size_lamports: u64,
        is_new_quote_mint: crate::sdk_core_cpi::Bool
    ) -> crate::sdk_core_cpi::Result<()> {
        self.touch_config_entry_bare_bump_with_args_with_remaining_accounts(TouchConfigEntryBareBumpWithArgsCpiCall {
        accounts,
        is_pump_pool,
        market_cap_lamports,
        trade_size_lamports,
        is_new_quote_mint,
        signer_seeds: &[],
        remaining_accounts: &[],
    })
    }

    fn touch_config_entry_bare_bump_with_args_signed<'a>(
        &self,
        accounts: TouchConfigEntryBareBumpWithArgsCpiAccounts<'a>,
        is_pump_pool: crate::sdk_core_cpi::Bool,
        market_cap_lamports: u128,
        trade_size_lamports: u64,
        is_new_quote_mint: crate::sdk_core_cpi::Bool,
        signer_seeds: &[&[&[u8]]]
    ) -> crate::sdk_core_cpi::Result<()> {
        self.touch_config_entry_bare_bump_with_args_with_remaining_accounts(TouchConfigEntryBareBumpWithArgsCpiCall {
        accounts,
        is_pump_pool,
        market_cap_lamports,
        trade_size_lamports,
        is_new_quote_mint,
        signer_seeds,
        remaining_accounts: &[],
    })
    }

    fn touch_config_entry_bare_bump_with_args_with_remaining_accounts<'a>(
        &self,
        call: TouchConfigEntryBareBumpWithArgsCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()>;

}

#[cfg(feature = "cpi")]
impl<'info> TouchConfigEntryBareBumpWithArgsCpi<'info> for crate::sdk_core_cpi::Program<crate::PdaSeedsZc> {
    fn touch_config_entry_bare_bump_with_args_with_remaining_accounts<'a>(
        &self,
        call: TouchConfigEntryBareBumpWithArgsCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()> {
        let TouchConfigEntryBareBumpWithArgsCpiCall { accounts, is_pump_pool, market_cap_lamports, trade_size_lamports, is_new_quote_mint, signer_seeds, remaining_accounts } = call;
        let args = TouchConfigEntryBareBumpWithArgsCpiIxArgs {
            is_pump_pool,
            market_cap_lamports,
            trade_size_lamports,
            is_new_quote_mint,
        };
        let mut ix_data = crate::sdk_core_cpi::Vec::new();
        ix_data.extend_from_slice(&[69, 181, 74, 168, 31, 97, 37, 192]);
        #[cfg(not(feature = "borsh"))]
        {
        ix_data.extend_from_slice(crate::sdk_core_cpi::bytemuck::bytes_of(&args));
        }
        #[cfg(feature = "borsh")]
        {
            crate::sdk_core_cpi::borsh::BorshSerialize::serialize(&args, &mut ix_data).unwrap();
        }
        #[cfg(feature = "pinocchio")]
        {
            let mut metas_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount>::uninit() }; 32];
            let mut idx = 0;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.config_program_id.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(accounts.config_entry.info.view.address()));
            idx += 1;
            for (acc, is_writable, is_signer) in remaining_accounts {
                if idx >= 32 { break; }
                let meta = if *is_writable {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(acc.view.address())
                    }
                } else {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(acc.view.address())
                    }
                };
                metas_arr[idx].write(meta);
                idx += 1;
            }
            let account_metas = unsafe { core::slice::from_raw_parts(metas_arr.as_ptr() as *const crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount, idx) };
            let program_id_address = self.address();
            let instruction = crate::sdk_core_cpi::pinocchio::instruction::InstructionView {
                program_id: program_id_address.as_address(),
                accounts: account_metas,
                data: &ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(accounts.config_program_id);
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.config_entry));
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed_pinocchio_handles(&instruction, account_handles, signer_seeds)
        }
        #[cfg(not(feature = "pinocchio"))]
        {
            use crate::sdk_core_cpi::ToAddress;
            let mut account_metas = crate::sdk_core_cpi::vec![
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.config_program_id.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new(accounts.config_entry.address(), false),
            ];
            for (acc, is_writable, is_signer) in remaining_accounts {
                let meta = if *is_writable {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new(acc.address(), *is_signer)
                } else {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(acc.address(), *is_signer)
                };
                account_metas.push(meta);
            }
            let instruction = ::naclac_lang::solana_program::instruction::Instruction {
                program_id: self.address(),
                accounts: account_metas,
                data: ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(accounts.config_program_id);
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.config_entry));
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed(&instruction, account_handles, signer_seeds)
        }
    }
}

