version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      solana-deps:
        patterns:
          - "solana-*"
          - "spl-*"
      pinocchio-deps:
        patterns:
          - "pinocchio*"

  - package-ecosystem: npm
    directory: "/client"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
