// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#![cfg_attr(all(feature = "cpi", feature = "pinocchio"), no_std)]

#[cfg(feature = "cpi")]
pub use naclac_lang::prelude as sdk_core_cpi;
#[cfg(feature = "offchain")]
pub use naclac_client as sdk_core_offchain;

#[cfg(feature = "offchain")]
pub mod components;
pub mod instructions;
pub mod types;

#[cfg(feature = "offchain")]
pub use components::*;
pub use instructions::*;
pub use types::*;

#[macro_export]
macro_rules! declare_id {
    ($id:expr) => {};
}

declare_id!("FADseVzrrwxbzWN83XK9YXoHULUf4E2LvZDp8F3fKKm8");

#[cfg(feature = "offchain")]
pub fn get_counter_pda(
    program_id: &naclac_client::Address
) -> (naclac_client::Address, u8) {
    naclac_client::Address::find_program_address(
        &[
            &[99, 111, 117, 110, 116, 101, 114],
        ],
        program_id,
    )
}

#[cfg(feature = "cpi")]
#[derive(Clone, Copy)]
pub struct SingleFileLayout;

#[cfg(feature = "cpi")]
impl sdk_core_cpi::Id for SingleFileLayout {
    fn id() -> sdk_core_cpi::Address {
        sdk_core_cpi::Address::new_from_array([210, 96, 102, 105, 52, 88, 166, 232, 113, 58, 189, 52, 38, 188, 208, 134, 130, 181, 112, 173, 76, 98, 18, 253, 220, 108, 254, 149, 155, 95, 8, 247])
    }
}

