// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(all(feature = "borsh", feature = "offchain"))]
use crate::sdk_core_offchain::borsh::{BorshDeserialize, BorshSerialize};
#[cfg(all(feature = "borsh", not(feature = "offchain")))]
use crate::sdk_core_cpi::borsh::{BorshDeserialize, BorshSerialize};

#[cfg(feature = "offchain")]
#[cfg(feature = "borsh")]
#[derive(Clone, Debug, BorshSerialize, BorshDeserialize)]
#[borsh(crate = "crate::sdk_core_offchain::borsh")]
pub struct Child {
    pub bump: u8,
    pub value: u64,
}

#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
#[derive(Copy, Clone, Debug)]
#[repr(C)]
pub struct Child {
    pub bump: u8,
    pub __naclac_padding_0: [u8; __Child_GAP_0],
    pub value: u64,
    pub __naclac_padding_1: [u8; __Child_GAP_1],
}

#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __Child_GAP_0: usize = {
    let __offset: usize = ::core::mem::size_of::<u8>();
    let __align: usize = ::core::mem::align_of::<u64>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __Child_GAP_1: usize = {
    let __offset: usize = ::core::mem::size_of::<u8>() + __Child_GAP_0
        + ::core::mem::size_of::<u64>();
    let __align: usize = {
        let mut __a = 1usize;
        let __b = ::core::mem::align_of::<u8>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u64>();
        if __b > __a {
            __a = __b;
        }
        __a
    };
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
const _: () = {
    assert!(
        ::core::mem::size_of:: < Child > () == (::core::mem::size_of:: < u8 > () +
        __Child_GAP_0 + ::core::mem::size_of:: < u64 > () + __Child_GAP_1),
        "defined_type/#[component]: `Child`'s auto-computed internal padding doesn't match the real compiler layout — this indicates a bug in naclac's own padding computation (naclac-client-gen's pod_struct_checks.rs / naclac-macros/src/pod_struct_checks.rs), not a field ordering issue for you to fix",
    );
};
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
const _: fn() = || {
    fn assert_impl<T: crate::sdk_core_offchain::bytemuck::Pod>() {}
    assert_impl::<u8>();
    assert_impl::<u64>();
};

#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Zeroable for Child {}
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Pod for Child {}
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
impl core::default::Default for Child {
    fn default() -> Self {
        crate::sdk_core_offchain::bytemuck::Zeroable::zeroed()
    }
}

#[cfg(feature = "cpi")]
#[cfg(feature = "borsh")]
#[derive(Clone, Debug, BorshSerialize, BorshDeserialize)]
#[borsh(crate = "crate::sdk_core_cpi::borsh")]
pub struct ChildCpi {
    pub bump: u8,
    pub value: u64,
}

#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
#[derive(Copy, Clone, Debug)]
#[repr(C)]
pub struct ChildCpi {
    pub bump: u8,
    pub __naclac_padding_0: [u8; __ChildCpi_GAP_0],
    pub value: u64,
    pub __naclac_padding_1: [u8; __ChildCpi_GAP_1],
}

#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __ChildCpi_GAP_0: usize = {
    let __offset: usize = ::core::mem::size_of::<u8>();
    let __align: usize = ::core::mem::align_of::<u64>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __ChildCpi_GAP_1: usize = {
    let __offset: usize = ::core::mem::size_of::<u8>() + __ChildCpi_GAP_0
        + ::core::mem::size_of::<u64>();
    let __align: usize = {
        let mut __a = 1usize;
        let __b = ::core::mem::align_of::<u8>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u64>();
        if __b > __a {
            __a = __b;
        }
        __a
    };
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
const _: () = {
    assert!(
        ::core::mem::size_of:: < ChildCpi > () == (::core::mem::size_of:: < u8 > () +
        __ChildCpi_GAP_0 + ::core::mem::size_of:: < u64 > () + __ChildCpi_GAP_1),
        "defined_type/#[component]: `ChildCpi`'s auto-computed internal padding doesn't match the real compiler layout — this indicates a bug in naclac's own padding computation (naclac-client-gen's pod_struct_checks.rs / naclac-macros/src/pod_struct_checks.rs), not a field ordering issue for you to fix",
    );
};
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
const _: fn() = || {
    fn assert_impl<T: crate::sdk_core_cpi::bytemuck::Pod>() {}
    assert_impl::<u8>();
    assert_impl::<u64>();
};

#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Zeroable for ChildCpi {}
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Pod for ChildCpi {}
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
impl core::default::Default for ChildCpi {
    fn default() -> Self {
        crate::sdk_core_cpi::bytemuck::Zeroable::zeroed()
    }
}


/// 8-byte on-chain discriminator for `Child` accounts.
pub const CHILD_DISCRIMINATOR: [u8; 8] = [161, 191, 179, 184, 153, 88, 25, 203];
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
impl naclac_client::NaclacDecode for Child {
    const DISCRIMINATOR: Option<[u8; 8]> = Some(CHILD_DISCRIMINATOR);
    fn naclac_decode(data: &[u8]) -> Result<Self, naclac_client::NaclacClientError> {
        naclac_client::decode_pod_checked::<Self>(data, CHILD_DISCRIMINATOR)
    }
}

#[cfg(feature = "offchain")]
#[cfg(feature = "borsh")]
impl naclac_client::NaclacDecode for Child {
    const DISCRIMINATOR: Option<[u8; 8]> = Some(CHILD_DISCRIMINATOR);
    fn naclac_decode(data: &[u8]) -> Result<Self, naclac_client::NaclacClientError> {
        naclac_client::decode_borsh_checked::<Self>(data, CHILD_DISCRIMINATOR)
    }
}
#[cfg(feature = "offchain")]
/// Fetches and decodes a `Child` account from the chain.
pub fn fetch_child(
    provider: &naclac_client::NaclacProvider,
    address: &naclac_client::Address,
) -> Result<Child, naclac_client::NaclacClientError> {
    let raw = provider.get_account_data(address)?;
    <Child as naclac_client::NaclacDecode>::naclac_decode(&raw)
}

#[cfg(feature = "offchain")]
/// Fetches a `Child` account. Returns `None` if the account does not exist.
pub fn fetch_maybe_child(
    provider: &naclac_client::NaclacProvider,
    address: &naclac_client::Address,
) -> Result<Option<Child>, naclac_client::NaclacClientError> {
    match fetch_child(provider, address) {
        Ok(a) => Ok(Some(a)),
        Err(naclac_client::NaclacClientError::AccountNotFound(_)) => Ok(None),
        Err(e) => Err(e),
    }
}

#[cfg(feature = "offchain")]
/// Fetches and decodes every on-chain `Child` account owned by `program_id`.
pub fn fetch_all_child(
    provider: &naclac_client::NaclacProvider,
    program_id: &naclac_client::Address,
) -> Result<crate::sdk_core_offchain::Vec<(naclac_client::Address, Child)>, naclac_client::NaclacClientError> {
    let raw_accounts = provider.get_program_accounts(program_id, Some(&CHILD_DISCRIMINATOR))?;
    let mut results = crate::sdk_core_offchain::Vec::new();
    for (address, data) in raw_accounts {
        if let Ok(value) = <Child as naclac_client::NaclacDecode>::naclac_decode(&data) {
            results.push((address, value));
        }
    }
    Ok(results)
}
