// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "borsh")]
use crate::sdk_core::borsh::{BorshDeserialize, BorshSerialize};

#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize, BorshDeserialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Copy, Clone, Debug))]
#[cfg_attr(not(feature = "borsh"), repr(C))]
pub struct Entry {
    pub bump: u8,
    pub value: u64,
}

/// 8-byte on-chain discriminator for `Entry` accounts.
pub const ENTRY_DISCRIMINATOR: [u8; 8] = [63, 18, 152, 113, 215, 246, 221, 250];
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
impl naclac_client::NaclacDecode for Entry {
    const DISCRIMINATOR: Option<[u8; 8]> = Some(ENTRY_DISCRIMINATOR);
    fn naclac_decode(data: &[u8]) -> Result<Self, naclac_client::NaclacClientError> {
        naclac_client::decode_pod_checked::<Self>(data, ENTRY_DISCRIMINATOR)
    }
}

#[cfg(feature = "offchain")]
#[cfg(feature = "borsh")]
impl naclac_client::NaclacDecode for Entry {
    const DISCRIMINATOR: Option<[u8; 8]> = Some(ENTRY_DISCRIMINATOR);
    fn naclac_decode(data: &[u8]) -> Result<Self, naclac_client::NaclacClientError> {
        naclac_client::decode_borsh_checked::<Self>(data, ENTRY_DISCRIMINATOR)
    }
}
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core::bytemuck::Zeroable for Entry {}
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core::bytemuck::Pod for Entry {}
#[cfg(feature = "offchain")]
/// Fetches and decodes a `Entry` account from the chain.
pub fn fetch_entry(
    provider: &naclac_client::NaclacProvider,
    address: &naclac_client::Address,
) -> Result<Entry, naclac_client::NaclacClientError> {
    let raw = provider.get_account_data(address)?;
    <Entry as naclac_client::NaclacDecode>::naclac_decode(&raw)
}

#[cfg(feature = "offchain")]
/// Fetches a `Entry` account. Returns `None` if the account does not exist.
pub fn fetch_maybe_entry(
    provider: &naclac_client::NaclacProvider,
    address: &naclac_client::Address,
) -> Result<Option<Entry>, naclac_client::NaclacClientError> {
    match fetch_entry(provider, address) {
        Ok(a) => Ok(Some(a)),
        Err(naclac_client::NaclacClientError::AccountNotFound(_)) => Ok(None),
        Err(e) => Err(e),
    }
}

#[cfg(feature = "offchain")]
/// Fetches and decodes every on-chain `Entry` account owned by `program_id`.
pub fn fetch_all_entry(
    provider: &naclac_client::NaclacProvider,
    program_id: &naclac_client::Address,
) -> Result<crate::sdk_core::Vec<(naclac_client::Address, Entry)>, naclac_client::NaclacClientError> {
    let raw_accounts = provider.get_program_accounts(program_id, Some(&ENTRY_DISCRIMINATOR))?;
    let mut results = crate::sdk_core::Vec::new();
    for (address, data) in raw_accounts {
        if let Ok(value) = <Entry as naclac_client::NaclacDecode>::naclac_decode(&data) {
            results.push((address, value));
        }
    }
    Ok(results)
}
