[package]
name = "dup_mut_borsh"
version = "0.1.0"
description = "Regression test: duplicate mutable account aliasing guard (solana-borsh backend)"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]
custom-heap = []
custom-panic = []
debug-mode = []

[dependencies]
naclac-lang = { version = "0.1.0", path = "../../../../naclac-lang", features = ["borsh"] }

[dev-dependencies]
naclac-client = { version = "0.1.0", path = "../../../../naclac-client" }
dup-mut-borsh-client = { version = "0.1.0", path = "../../clients/rust/dup_mut_borsh" }

[lints]
workspace = true
