// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
pub struct InitSeededAccounts {
    pub payer: naclac_client::Address,
    pub seeded: naclac_client::Address,
    pub system_program: naclac_client::Address,
}

#[cfg(feature = "offchain")]
pub fn build_init_seeded<'a>(
    provider: &'a naclac_client::NaclacProvider,
    program_id: naclac_client::Address,
    accounts: InitSeededAccounts,
) -> naclac_client::InstructionBuilder<'a> {
    let ix_data = crate::sdk_core::vec![194, 72, 3, 113, 154, 190, 21, 206];
    naclac_client::InstructionBuilder::new(provider, program_id, ix_data)
        .account(naclac_client::AccountMeta { address: accounts.payer, is_signer: true, is_writable: true }, "payer")
        .account(naclac_client::AccountMeta { address: accounts.seeded, is_signer: false, is_writable: true }, "seeded")
        .account(naclac_client::AccountMeta { address: accounts.system_program, is_signer: false, is_writable: false }, "systemProgram")
}

#[cfg(feature = "cpi")]
pub struct InitSeededCpiAccounts<'a> {
    pub payer: crate::sdk_core::CpiHandleMut<'a>,
    pub seeded: crate::sdk_core::CpiHandleMut<'a>,
    pub system_program: crate::sdk_core::CpiHandle<'a>,
}

#[cfg(feature = "cpi")]
pub trait InitSeededCpi<'info> {
    fn init_seeded<'a>(
        &self,
        accounts: InitSeededCpiAccounts<'a>
    ) -> crate::sdk_core::Result<()> {
        self.init_seeded_with_remaining_accounts(accounts, &[], &[])
    }

    fn init_seeded_signed<'a>(
        &self,
        accounts: InitSeededCpiAccounts<'a>,
        signer_seeds: &[&[&[u8]]]
    ) -> crate::sdk_core::Result<()> {
        self.init_seeded_with_remaining_accounts(accounts, signer_seeds, &[])
    }

    fn init_seeded_with_remaining_accounts<'a>(
        &self,
        accounts: InitSeededCpiAccounts<'a>,
        signer_seeds: &[&[&[u8]]],
        remaining_accounts: &[(crate::sdk_core::AccountInfo, bool, bool)]
    ) -> crate::sdk_core::Result<()>;

}

#[cfg(feature = "cpi")]
impl<'info> InitSeededCpi<'info> for crate::sdk_core::Program<crate::AccountsConstraints> {
    fn init_seeded_with_remaining_accounts<'a>(
        &self,
        accounts: InitSeededCpiAccounts<'a>,
        signer_seeds: &[&[&[u8]]],
        remaining_accounts: &[(crate::sdk_core::AccountInfo, bool, bool)]
    ) -> crate::sdk_core::Result<()> {
        let mut ix_data = crate::sdk_core::Vec::new();
        ix_data.extend_from_slice(&[194, 72, 3, 113, 154, 190, 21, 206]);
        #[cfg(feature = "pinocchio")]
        {
            let mut metas_arr = [const { core::mem::MaybeUninit::<crate::sdk_core::pinocchio::instruction::InstructionAccount>::uninit() }; 32];
            let mut idx = 0;
            metas_arr[idx].write(crate::sdk_core::pinocchio::instruction::InstructionAccount::writable_signer(accounts.payer.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core::pinocchio::instruction::InstructionAccount::writable(accounts.seeded.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core::pinocchio::instruction::InstructionAccount::readonly(accounts.system_program.info.view.address()));
            idx += 1;
            for (acc, is_writable, is_signer) in remaining_accounts {
                if idx >= 32 { break; }
                let meta = if *is_writable {
                    if *is_signer {
                        crate::sdk_core::pinocchio::instruction::InstructionAccount::writable_signer(acc.view.address())
                    } else {
                        crate::sdk_core::pinocchio::instruction::InstructionAccount::writable(acc.view.address())
                    }
                } else {
                    if *is_signer {
                        crate::sdk_core::pinocchio::instruction::InstructionAccount::readonly_signer(acc.view.address())
                    } else {
                        crate::sdk_core::pinocchio::instruction::InstructionAccount::readonly(acc.view.address())
                    }
                };
                metas_arr[idx].write(meta);
                idx += 1;
            }
            let account_metas = unsafe { core::slice::from_raw_parts(metas_arr.as_ptr() as *const crate::sdk_core::pinocchio::instruction::InstructionAccount, idx) };
            let program_id_address = self.address();
            let instruction = crate::sdk_core::pinocchio::instruction::InstructionView {
                program_id: program_id_address.as_address(),
                accounts: account_metas,
                data: &ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(crate::sdk_core::CpiHandle::from(accounts.payer));
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core::CpiHandle::from(accounts.seeded));
            h_idx += 1;
            handles_arr[h_idx].write(accounts.system_program);
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core::CpiHandle, h_idx) };
            crate::sdk_core::cpi::invoke_signed_pinocchio_handles(&instruction, account_handles, signer_seeds)
        }
        #[cfg(not(feature = "pinocchio"))]
        {
            use crate::sdk_core::ToAddress;
            let mut account_metas = crate::sdk_core::vec![
                ::naclac_lang::solana_program::instruction::AccountMeta::new(accounts.payer.address(), true),
                ::naclac_lang::solana_program::instruction::AccountMeta::new(accounts.seeded.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.system_program.address(), false),
            ];
            for (acc, is_writable, is_signer) in remaining_accounts {
                let meta = if *is_writable {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new(acc.address(), *is_signer)
                } else {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(acc.address(), *is_signer)
                };
                account_metas.push(meta);
            }
            let instruction = ::naclac_lang::solana_program::instruction::Instruction {
                program_id: self.address(),
                accounts: account_metas,
                data: ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(crate::sdk_core::CpiHandle::from(accounts.payer));
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core::CpiHandle::from(accounts.seeded));
            h_idx += 1;
            handles_arr[h_idx].write(accounts.system_program);
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core::CpiHandle, h_idx) };
            crate::sdk_core::cpi::invoke_signed(&instruction, account_handles, signer_seeds)
        }
    }
}

