// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
pub struct TouchMutVaultAccounts {
    pub vault: naclac_client::Address,
}

#[cfg(feature = "offchain")]
pub fn build_touch_mut_vault<'a>(
    provider: &'a naclac_client::NaclacProvider,
    program_id: naclac_client::Address,
    accounts: TouchMutVaultAccounts,
) -> naclac_client::InstructionBuilder<'a> {
    let ix_data = crate::sdk_core_offchain::vec![70, 22, 63, 237, 108, 82, 188, 171];
    naclac_client::InstructionBuilder::new(provider, program_id, ix_data)
        .account(naclac_client::AccountMeta { address: accounts.vault, is_signer: false, is_writable: true }, "vault")
}

#[cfg(feature = "cpi")]
pub struct TouchMutVaultCpiAccounts<'a> {
    pub vault: crate::sdk_core_cpi::CpiHandleMut<'a>,
}

#[cfg(feature = "cpi")]
pub struct TouchMutVaultCpiCall<'a> {
    pub accounts: TouchMutVaultCpiAccounts<'a>,
    pub signer_seeds: &'a [&'a [&'a [u8]]],
    pub remaining_accounts: &'a [(crate::sdk_core_cpi::AccountInfo, bool, bool)],
}

#[cfg(feature = "cpi")]
pub trait TouchMutVaultCpi<'info> {
    fn touch_mut_vault<'a>(
        &self,
        accounts: TouchMutVaultCpiAccounts<'a>
    ) -> crate::sdk_core_cpi::Result<()> {
        self.touch_mut_vault_with_remaining_accounts(TouchMutVaultCpiCall {
        accounts,
        signer_seeds: &[],
        remaining_accounts: &[],
    })
    }

    fn touch_mut_vault_signed<'a>(
        &self,
        accounts: TouchMutVaultCpiAccounts<'a>,
        signer_seeds: &[&[&[u8]]]
    ) -> crate::sdk_core_cpi::Result<()> {
        self.touch_mut_vault_with_remaining_accounts(TouchMutVaultCpiCall {
        accounts,
        signer_seeds,
        remaining_accounts: &[],
    })
    }

    fn touch_mut_vault_with_remaining_accounts<'a>(
        &self,
        call: TouchMutVaultCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()>;

}

#[cfg(feature = "cpi")]
impl<'info> TouchMutVaultCpi<'info> for crate::sdk_core_cpi::Program<crate::AccountsConstraints> {
    fn touch_mut_vault_with_remaining_accounts<'a>(
        &self,
        call: TouchMutVaultCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()> {
        let TouchMutVaultCpiCall { accounts, signer_seeds, remaining_accounts } = call;
        let mut ix_data = crate::sdk_core_cpi::Vec::new();
        ix_data.extend_from_slice(&[70, 22, 63, 237, 108, 82, 188, 171]);
        #[cfg(feature = "pinocchio")]
        {
            let mut metas_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount>::uninit() }; 32];
            let mut idx = 0;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(accounts.vault.info.view.address()));
            idx += 1;
            for (acc, is_writable, is_signer) in remaining_accounts {
                if idx >= 32 { break; }
                let meta = if *is_writable {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(acc.view.address())
                    }
                } else {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(acc.view.address())
                    }
                };
                metas_arr[idx].write(meta);
                idx += 1;
            }
            let account_metas = unsafe { core::slice::from_raw_parts(metas_arr.as_ptr() as *const crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount, idx) };
            let program_id_address = self.address();
            let instruction = crate::sdk_core_cpi::pinocchio::instruction::InstructionView {
                program_id: program_id_address.as_address(),
                accounts: account_metas,
                data: &ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.vault));
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed_pinocchio_handles(&instruction, account_handles, signer_seeds)
        }
        #[cfg(not(feature = "pinocchio"))]
        {
            use crate::sdk_core_cpi::ToAddress;
            let mut account_metas = crate::sdk_core_cpi::vec![
                ::naclac_lang::solana_program::instruction::AccountMeta::new(accounts.vault.address(), false),
            ];
            for (acc, is_writable, is_signer) in remaining_accounts {
                let meta = if *is_writable {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new(acc.address(), *is_signer)
                } else {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(acc.address(), *is_signer)
                };
                account_metas.push(meta);
            }
            let instruction = ::naclac_lang::solana_program::instruction::Instruction {
                program_id: self.address(),
                accounts: account_metas,
                data: ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.vault));
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed(&instruction, account_handles, signer_seeds)
        }
    }
}

