// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "borsh")]
use crate::sdk_core::borsh::BorshSerialize;

#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Copy, Clone, Debug))]
#[cfg_attr(not(feature = "borsh"), repr(C, packed))]
pub struct TouchSeededIxArgs {
    pub bump: u8,
}

#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core::bytemuck::Zeroable for TouchSeededIxArgs {}
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core::bytemuck::Pod for TouchSeededIxArgs {}

#[cfg(feature = "offchain")]
pub struct TouchSeededAccounts {
    pub seeded: naclac_client::Address,
}

#[cfg(feature = "offchain")]
pub fn build_touch_seeded<'a>(
    provider: &'a naclac_client::NaclacProvider,
    program_id: naclac_client::Address,
    bump: u8,
    accounts: TouchSeededAccounts,
) -> naclac_client::InstructionBuilder<'a> {
    let mut ix_data = crate::sdk_core::vec![113, 221, 0, 65, 190, 116, 9, 205];
    let args = TouchSeededIxArgs {
        bump,
    };
    #[cfg(not(feature = "borsh"))]
    {
        ix_data.extend_from_slice(crate::sdk_core::bytemuck::bytes_of(&args));
    }
    #[cfg(feature = "borsh")]
    {
        crate::sdk_core::borsh::BorshSerialize::serialize(&args, &mut ix_data).unwrap();
    }
    naclac_client::InstructionBuilder::new(provider, program_id, ix_data)
        .account(naclac_client::AccountMeta { address: accounts.seeded, is_signer: false, is_writable: true }, "seeded")
}

#[cfg(feature = "cpi")]
pub struct TouchSeededCpiAccounts<'a> {
    pub seeded: crate::sdk_core::CpiHandleMut<'a>,
}

#[cfg(feature = "cpi")]
pub trait TouchSeededCpi<'info> {
    fn touch_seeded<'a>(
        &self,
        accounts: TouchSeededCpiAccounts<'a>,
        bump: u8
    ) -> crate::sdk_core::Result<()> {
        self.touch_seeded_with_remaining_accounts(accounts, bump, &[], &[])
    }

    fn touch_seeded_signed<'a>(
        &self,
        accounts: TouchSeededCpiAccounts<'a>,
        bump: u8,
        signer_seeds: &[&[&[u8]]]
    ) -> crate::sdk_core::Result<()> {
        self.touch_seeded_with_remaining_accounts(accounts, bump, signer_seeds, &[])
    }

    fn touch_seeded_with_remaining_accounts<'a>(
        &self,
        accounts: TouchSeededCpiAccounts<'a>,
        bump: u8,
        signer_seeds: &[&[&[u8]]],
        remaining_accounts: &[(crate::sdk_core::AccountInfo, bool, bool)]
    ) -> crate::sdk_core::Result<()>;

}

#[cfg(feature = "cpi")]
impl<'info> TouchSeededCpi<'info> for crate::sdk_core::Program<crate::AccountsConstraints> {
    fn touch_seeded_with_remaining_accounts<'a>(
        &self,
        accounts: TouchSeededCpiAccounts<'a>,
        bump: u8,
        signer_seeds: &[&[&[u8]]],
        remaining_accounts: &[(crate::sdk_core::AccountInfo, bool, bool)]
    ) -> crate::sdk_core::Result<()> {
        let args = TouchSeededIxArgs {
            bump,
        };
        let mut ix_data = crate::sdk_core::Vec::new();
        ix_data.extend_from_slice(&[113, 221, 0, 65, 190, 116, 9, 205]);
        #[cfg(not(feature = "borsh"))]
        {
            ix_data.extend_from_slice(crate::sdk_core::bytemuck::bytes_of(&args));
        }
        #[cfg(feature = "borsh")]
        {
            crate::sdk_core::borsh::BorshSerialize::serialize(&args, &mut ix_data).unwrap();
        }
        #[cfg(feature = "pinocchio")]
        {
            let mut metas_arr = [const { core::mem::MaybeUninit::<crate::sdk_core::pinocchio::instruction::InstructionAccount>::uninit() }; 32];
            let mut idx = 0;
            metas_arr[idx].write(crate::sdk_core::pinocchio::instruction::InstructionAccount::writable(accounts.seeded.info.view.address()));
            idx += 1;
            for (acc, is_writable, is_signer) in remaining_accounts {
                if idx >= 32 { break; }
                let meta = if *is_writable {
                    if *is_signer {
                        crate::sdk_core::pinocchio::instruction::InstructionAccount::writable_signer(acc.view.address())
                    } else {
                        crate::sdk_core::pinocchio::instruction::InstructionAccount::writable(acc.view.address())
                    }
                } else {
                    if *is_signer {
                        crate::sdk_core::pinocchio::instruction::InstructionAccount::readonly_signer(acc.view.address())
                    } else {
                        crate::sdk_core::pinocchio::instruction::InstructionAccount::readonly(acc.view.address())
                    }
                };
                metas_arr[idx].write(meta);
                idx += 1;
            }
            let account_metas = unsafe { core::slice::from_raw_parts(metas_arr.as_ptr() as *const crate::sdk_core::pinocchio::instruction::InstructionAccount, idx) };
            let program_id_address = self.address();
            let instruction = crate::sdk_core::pinocchio::instruction::InstructionView {
                program_id: program_id_address.as_address(),
                accounts: account_metas,
                data: &ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(crate::sdk_core::CpiHandle::from(accounts.seeded));
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core::CpiHandle, h_idx) };
            crate::sdk_core::cpi::invoke_signed_pinocchio_handles(&instruction, account_handles, signer_seeds)
        }
        #[cfg(not(feature = "pinocchio"))]
        {
            use crate::sdk_core::ToAddress;
            let mut account_metas = crate::sdk_core::vec![
                ::naclac_lang::solana_program::instruction::AccountMeta::new(accounts.seeded.address(), false),
            ];
            for (acc, is_writable, is_signer) in remaining_accounts {
                let meta = if *is_writable {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new(acc.address(), *is_signer)
                } else {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(acc.address(), *is_signer)
                };
                account_metas.push(meta);
            }
            let instruction = ::naclac_lang::solana_program::instruction::Instruction {
                program_id: self.address(),
                accounts: account_metas,
                data: ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(crate::sdk_core::CpiHandle::from(accounts.seeded));
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core::CpiHandle, h_idx) };
            crate::sdk_core::cpi::invoke_signed(&instruction, account_handles, signer_seeds)
        }
    }
}

