// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
pub struct CallSetupCounterAccounts {
    pub payer: naclac_client::Address,
    /// SAFETY: this is `cpi_callee`'s own PDA, owned and validated by that
    /// program, not ours — we only ever forward it as a CPI account.
    pub counter: naclac_client::Address,
    pub caller_authority: naclac_client::Address,
    pub callee_program: naclac_client::Address,
    pub system_program: naclac_client::Address,
}

#[cfg(feature = "offchain")]
pub fn build_call_setup_counter<'a>(
    provider: &'a naclac_client::NaclacProvider,
    program_id: naclac_client::Address,
    accounts: CallSetupCounterAccounts,
) -> naclac_client::InstructionBuilder<'a> {
    let ix_data = crate::sdk_core_offchain::vec![236, 176, 98, 70, 9, 231, 21, 147];
    naclac_client::InstructionBuilder::new(provider, program_id, ix_data)
        .account(naclac_client::AccountMeta { address: accounts.payer, is_signer: true, is_writable: true }, "payer")
        .account(naclac_client::AccountMeta { address: accounts.counter, is_signer: false, is_writable: true }, "counter")
        .account(naclac_client::AccountMeta { address: accounts.caller_authority, is_signer: false, is_writable: false }, "caller_authority")
        .account(naclac_client::AccountMeta { address: accounts.callee_program, is_signer: false, is_writable: false }, "callee_program")
        .account(naclac_client::AccountMeta { address: accounts.system_program, is_signer: false, is_writable: false }, "system_program")
}

#[cfg(feature = "cpi")]
pub struct CallSetupCounterCpiAccounts<'a> {
    pub payer: crate::sdk_core_cpi::CpiHandleMut<'a>,
    /// SAFETY: this is `cpi_callee`'s own PDA, owned and validated by that
    /// program, not ours — we only ever forward it as a CPI account.
    pub counter: crate::sdk_core_cpi::CpiHandleMut<'a>,
    pub caller_authority: crate::sdk_core_cpi::CpiHandle<'a>,
    pub callee_program: crate::sdk_core_cpi::CpiHandle<'a>,
    pub system_program: crate::sdk_core_cpi::CpiHandle<'a>,
}

#[cfg(feature = "cpi")]
pub struct CallSetupCounterCpiCall<'a> {
    pub accounts: CallSetupCounterCpiAccounts<'a>,
    pub signer_seeds: &'a [&'a [&'a [u8]]],
    pub remaining_accounts: &'a [(crate::sdk_core_cpi::AccountInfo, bool, bool)],
}

#[cfg(feature = "cpi")]
pub trait CallSetupCounterCpi<'info> {
    fn call_setup_counter<'a>(
        &self,
        accounts: CallSetupCounterCpiAccounts<'a>
    ) -> crate::sdk_core_cpi::Result<()> {
        self.call_setup_counter_with_remaining_accounts(CallSetupCounterCpiCall {
        accounts,
        signer_seeds: &[],
        remaining_accounts: &[],
    })
    }

    fn call_setup_counter_signed<'a>(
        &self,
        accounts: CallSetupCounterCpiAccounts<'a>,
        signer_seeds: &[&[&[u8]]]
    ) -> crate::sdk_core_cpi::Result<()> {
        self.call_setup_counter_with_remaining_accounts(CallSetupCounterCpiCall {
        accounts,
        signer_seeds,
        remaining_accounts: &[],
    })
    }

    fn call_setup_counter_with_remaining_accounts<'a>(
        &self,
        call: CallSetupCounterCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()>;

}

#[cfg(feature = "cpi")]
impl<'info> CallSetupCounterCpi<'info> for crate::sdk_core_cpi::Program<crate::CpiCaller> {
    fn call_setup_counter_with_remaining_accounts<'a>(
        &self,
        call: CallSetupCounterCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()> {
        let CallSetupCounterCpiCall { accounts, signer_seeds, remaining_accounts } = call;
        let mut ix_data = crate::sdk_core_cpi::Vec::new();
        ix_data.extend_from_slice(&[236, 176, 98, 70, 9, 231, 21, 147]);
        #[cfg(feature = "pinocchio")]
        {
            let mut metas_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount>::uninit() }; 32];
            let mut idx = 0;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable_signer(accounts.payer.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(accounts.counter.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.caller_authority.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.callee_program.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.system_program.info.view.address()));
            idx += 1;
            for (acc, is_writable, is_signer) in remaining_accounts {
                if idx >= 32 { break; }
                let meta = if *is_writable {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(acc.view.address())
                    }
                } else {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(acc.view.address())
                    }
                };
                metas_arr[idx].write(meta);
                idx += 1;
            }
            let account_metas = unsafe { core::slice::from_raw_parts(metas_arr.as_ptr() as *const crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount, idx) };
            let program_id_address = self.address();
            let instruction = crate::sdk_core_cpi::pinocchio::instruction::InstructionView {
                program_id: program_id_address.as_address(),
                accounts: account_metas,
                data: &ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.payer));
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.counter));
            h_idx += 1;
            handles_arr[h_idx].write(accounts.caller_authority);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.callee_program);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.system_program);
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed_pinocchio_handles(&instruction, account_handles, signer_seeds)
        }
        #[cfg(not(feature = "pinocchio"))]
        {
            use crate::sdk_core_cpi::ToAddress;
            let mut account_metas = crate::sdk_core_cpi::vec![
                ::naclac_lang::solana_program::instruction::AccountMeta::new(accounts.payer.address(), true),
                ::naclac_lang::solana_program::instruction::AccountMeta::new(accounts.counter.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.caller_authority.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.callee_program.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.system_program.address(), false),
            ];
            for (acc, is_writable, is_signer) in remaining_accounts {
                let meta = if *is_writable {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new(acc.address(), *is_signer)
                } else {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(acc.address(), *is_signer)
                };
                account_metas.push(meta);
            }
            let instruction = ::naclac_lang::solana_program::instruction::Instruction {
                program_id: self.address(),
                accounts: account_metas,
                data: ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.payer));
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.counter));
            h_idx += 1;
            handles_arr[h_idx].write(accounts.caller_authority);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.callee_program);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.system_program);
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed(&instruction, account_handles, signer_seeds)
        }
    }
}

