use crate::Idl;
use heck::AsSnakeCase;
use std::fs;
use std::path::Path;

pub mod components;
pub mod instructions;
pub mod lib_generator;
pub mod types;

// Map IDL type to Rust type
pub fn map_type_to_rust_with_prefix(
    idl_type: &serde_json::Value,
    is_zero_copy: bool,
    defined_prefix: &str,
) -> String {
    match idl_type {
        serde_json::Value::String(s) => match s.as_str() {
            "u8" | "u16" | "u32" | "u64" | "u128" | "i8" | "i16" | "i32" | "i64" | "i128"
            | "f32" | "f64" | "usize" | "isize" | "bool" => s.to_string(),
            "string" | "String" => "String".to_string(),
            "publicKey" => "crate::sdk_core::Address".to_string(),
            "bytes" | "&[u8]" | "[u8]" => {
                if is_zero_copy {
                    "&[u8]".to_string()
                } else {
                    "Vec<u8>".to_string()
                }
            }
            _ => {
                if !defined_prefix.is_empty() {
                    format!("{}{}", defined_prefix, s)
                } else {
                    s.to_string()
                }
            }
        },
        serde_json::Value::Object(o) => {
            if let Some(inner) = o.get("option") {
                return format!(
                    "Option<{}>",
                    map_type_to_rust_with_prefix(inner, is_zero_copy, defined_prefix)
                );
            }
            if let Some(inner) = o.get("vec") {
                return format!(
                    "Vec<{}>",
                    map_type_to_rust_with_prefix(inner, is_zero_copy, defined_prefix)
                );
            }
            if let Some(arr) = o.get("array") {
                if let Some(inner) = arr.get(0) {
                    if let Some(len) = arr.get(1).and_then(|v| v.as_u64()) {
                        return format!(
                            "[{}; {}]",
                            map_type_to_rust_with_prefix(inner, is_zero_copy, defined_prefix),
                            len
                        );
                    }
                }
            }
            if let Some(defined) = o.get("defined").and_then(|d| d.as_str()) {
                if !defined_prefix.is_empty() {
                    return format!("{}{}", defined_prefix, defined);
                }
                return defined.to_string();
            }
            "serde_json::Value".to_string()
        }
        _ => "serde_json::Value".to_string(),
    }
}

pub fn map_type_to_rust(idl_type: &serde_json::Value, is_zero_copy: bool) -> String {
    map_type_to_rust_with_prefix(idl_type, is_zero_copy, "")
}

pub fn generate_rust_sdk(
    idl_json: &str,
    program_name: &str,
    workspace_root: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    println!("⚙️ Generating Rust Client SDK for '{}'...", program_name);
    let mut idl: Idl = serde_json::from_str(idl_json)?;
    let temp_marker = workspace_root.join(format!("target/.{}-zero-copy", program_name));
    if temp_marker.exists() {
        idl.is_zero_copy = true;
    }

    let program_name_snake = AsSnakeCase(program_name).to_string();
    let program_name_kebab = program_name.replace("_", "-");

    let clients_dir = workspace_root.join(format!("clients/rust/{}", program_name_snake));

    if clients_dir.exists() {
        fs::remove_dir_all(&clients_dir).unwrap();
    }

    fs::create_dir_all(clients_dir.join("src/types")).unwrap();

    if !idl.accounts.is_empty() {
        fs::create_dir_all(clients_dir.join("src/components")).unwrap();
    }
    if !idl.instructions.is_empty() {
        fs::create_dir_all(clients_dir.join("src/instructions")).unwrap();
    }

    let header = "// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC\n// Re-run `naclac generate` to refresh this file.\n\n";

    let default_features = if idl.is_zero_copy {
        r#"default = ["offchain"]"#
    } else {
        r#"default = ["offchain", "borsh"]"#
    };

    // 1. Generate Cargo.toml with custom feature flags
    let cargo_toml_content = format!(
        r#"[package]
name = "{}-client"
version = "0.1.0"
edition = "2021"

[features]
{}
offchain = ["dep:naclac-client"]
cpi = ["dep:naclac-lang"]
zero_copy = ["naclac-lang/solana"]
pinocchio = ["naclac-lang/pinocchio"]
borsh = ["naclac-lang/borsh", "zero_copy"]

[dependencies]
naclac-client = {{ path = "../../../../../naclac-client", version = "0.1.0", optional = true }}
naclac-lang = {{ path = "../../../../../naclac-lang", version = "0.1.0", optional = true, default-features = false }}
"#,
        program_name_kebab, default_features
    );
    fs::write(clients_dir.join("Cargo.toml"), cargo_toml_content).unwrap();

    let decoded_address = bs58::decode(&idl.address).into_vec()?;
    let address_bytes_str = decoded_address
        .iter()
        .map(|b| b.to_string())
        .collect::<Vec<_>>()
        .join(", ");

    // 2. Generate Components
    components::generate_components(&idl, &clients_dir, header)?;

    // 3. Generate Instructions
    instructions::generate_instructions(&idl, &clients_dir, header)?;

    // 4. Generate Types
    types::generate_types(&idl, &clients_dir, header, &address_bytes_str)?;

    // 5. Generate lib.rs
    lib_generator::generate_lib(&idl, &clients_dir, header)?;

    println!(
        "✅ Rust Client SDK successfully generated in clients/rust/{}",
        program_name_snake
    );
    Ok(())
}
