[package]
name = "metadata-solana-client"
version = "0.1.0"
edition = "2021"

[features]
default = ["offchain"]
offchain = ["dep:naclac-client"]
cpi = ["dep:naclac-lang"]
zero_copy = ["naclac-lang/solana"]
pinocchio = ["naclac-lang/pinocchio"]
borsh = ["naclac-lang/borsh", "zero_copy"]

[dependencies]
naclac-client = { version = "0.1.0", optional = true, path = "../../../../../naclac-client" }
naclac-lang = { version = "0.1.0", optional = true, default-features = false, path = "../../../../../naclac-lang" }
