// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "borsh")]
use crate::sdk_core::borsh::{BorshDeserialize, BorshSerialize};

#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize, BorshDeserialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Copy, Clone, Debug))]
#[cfg_attr(not(feature = "borsh"), repr(C))]
pub struct PoolInitialized {
    pub token_a_mint: crate::sdk_core::Address,
    pub token_b_mint: crate::sdk_core::Address,
    pub lp_amount: u64,
}

#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core::bytemuck::Zeroable for PoolInitialized {}
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core::bytemuck::Pod for PoolInitialized {}

#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize, BorshDeserialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Copy, Clone, Debug))]
#[cfg_attr(not(feature = "borsh"), repr(C))]
pub struct SwapExecuted {
    pub user: crate::sdk_core::Address,
    pub amount_in: u64,
    pub amount_out: u64,
}

#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core::bytemuck::Zeroable for SwapExecuted {}
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core::bytemuck::Pod for SwapExecuted {}

#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize, BorshDeserialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Copy, Clone, Debug))]
#[cfg_attr(not(feature = "borsh"), repr(C))]
pub struct LiquidityAdded {
    pub token_a_mint: crate::sdk_core::Address,
    pub token_b_mint: crate::sdk_core::Address,
    pub amount_a: u64,
    pub amount_b: u64,
    pub lp_minted: u64,
}

#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core::bytemuck::Zeroable for LiquidityAdded {}
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core::bytemuck::Pod for LiquidityAdded {}

#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize, BorshDeserialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Copy, Clone, Debug))]
#[cfg_attr(not(feature = "borsh"), repr(C))]
pub struct LiquidityRemoved {
    pub token_a_mint: crate::sdk_core::Address,
    pub token_b_mint: crate::sdk_core::Address,
    pub amount_a: u64,
    pub amount_b: u64,
    pub lp_burned: u64,
}

#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core::bytemuck::Zeroable for LiquidityRemoved {}
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core::bytemuck::Pod for LiquidityRemoved {}

