// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
#[cfg(feature = "borsh")]
use crate::sdk_core_offchain::borsh::BorshSerialize;
#[cfg(feature = "offchain")]
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_offchain::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Copy, Clone, Debug))]
#[cfg_attr(not(feature = "borsh"), repr(C, packed))]
pub struct CollectCreatorFeeIxArgs {
    pub creator_vault_bump: u8,
}

#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Zeroable for CollectCreatorFeeIxArgs {}
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Pod for CollectCreatorFeeIxArgs {}

#[cfg(feature = "cpi")]
#[cfg(feature = "borsh")]
use crate::sdk_core_cpi::borsh::BorshSerialize;
#[cfg(feature = "cpi")]
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_cpi::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Copy, Clone, Debug))]
#[cfg_attr(not(feature = "borsh"), repr(C, packed))]
pub struct CollectCreatorFeeCpiIxArgs {
    pub creator_vault_bump: u8,
}

#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Zeroable for CollectCreatorFeeCpiIxArgs {}
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Pod for CollectCreatorFeeCpiIxArgs {}

#[cfg(feature = "offchain")]
/// Sweeps `creator_vault` down to its rent-exempt minimum, paying the full
/// swept amount to `creator` — the native-SOL sibling of
/// `distribute_creator_fees`'s own rent-exempt-floor sweep, just without a
/// shareholder split (100% to `creator`). Permissionless: anyone may crank
/// it, funds always land at the fixed `creator_vault` -> `creator` PDA pair.
pub struct CollectCreatorFeeAccounts {
    /// SAFETY: only a native-lamport transfer destination and PDA seed
    /// material for `creator_vault` below; never deserialized.
    pub creator: naclac_client::Address,
    /// SAFETY: the `seeds`/`bump` constraint already verifies its address;
    /// it's a lamport-only PDA (no stored data) — only ever a lamport source
    /// below via a signed System Program transfer, never deserialized.
    pub creator_vault: naclac_client::Address,
    pub system_program: naclac_client::Address,
}

#[cfg(feature = "offchain")]
/// Sweeps `creator_vault` down to its rent-exempt minimum, paying the full
/// swept amount to `creator` — the native-SOL sibling of
/// `distribute_creator_fees`'s own rent-exempt-floor sweep, just without a
/// shareholder split (100% to `creator`). Permissionless: anyone may crank
/// it, funds always land at the fixed `creator_vault` -> `creator` PDA pair.
pub fn build_collect_creator_fee<'a>(
    provider: &'a naclac_client::NaclacProvider,
    program_id: naclac_client::Address,
    creator_vault_bump: u8,
    accounts: CollectCreatorFeeAccounts,
) -> naclac_client::InstructionBuilder<'a> {
    let mut ix_data = crate::sdk_core_offchain::vec![20, 22, 86, 123, 198, 28, 219, 132];
    let args = CollectCreatorFeeIxArgs {
        creator_vault_bump,
    };
    #[cfg(not(feature = "borsh"))]
    {
        ix_data.extend_from_slice(crate::sdk_core_offchain::bytemuck::bytes_of(&args));
    }
    #[cfg(feature = "borsh")]
    {
        crate::sdk_core_offchain::borsh::BorshSerialize::serialize(&args, &mut ix_data).unwrap();
    }
    naclac_client::InstructionBuilder::new(provider, program_id, ix_data)
        .account(naclac_client::AccountMeta { address: accounts.creator, is_signer: false, is_writable: true }, "creator")
        .account(naclac_client::AccountMeta { address: accounts.creator_vault, is_signer: false, is_writable: true }, "creator_vault")
        .account(naclac_client::AccountMeta { address: accounts.system_program, is_signer: false, is_writable: false }, "system_program")
}

#[cfg(feature = "cpi")]
/// Sweeps `creator_vault` down to its rent-exempt minimum, paying the full
/// swept amount to `creator` — the native-SOL sibling of
/// `distribute_creator_fees`'s own rent-exempt-floor sweep, just without a
/// shareholder split (100% to `creator`). Permissionless: anyone may crank
/// it, funds always land at the fixed `creator_vault` -> `creator` PDA pair.
pub struct CollectCreatorFeeCpiAccounts<'a> {
    /// SAFETY: only a native-lamport transfer destination and PDA seed
    /// material for `creator_vault` below; never deserialized.
    pub creator: crate::sdk_core_cpi::CpiHandleMut<'a>,
    /// SAFETY: the `seeds`/`bump` constraint already verifies its address;
    /// it's a lamport-only PDA (no stored data) — only ever a lamport source
    /// below via a signed System Program transfer, never deserialized.
    pub creator_vault: crate::sdk_core_cpi::CpiHandleMut<'a>,
    pub system_program: crate::sdk_core_cpi::CpiHandle<'a>,
}

#[cfg(feature = "cpi")]
pub struct CollectCreatorFeeCpiCall<'a> {
    pub accounts: CollectCreatorFeeCpiAccounts<'a>,
    pub creator_vault_bump: u8,
    pub signer_seeds: &'a [&'a [&'a [u8]]],
    pub remaining_accounts: &'a [(crate::sdk_core_cpi::AccountInfo, bool, bool)],
}

#[cfg(feature = "cpi")]
pub trait CollectCreatorFeeCpi<'info> {
    /// Sweeps `creator_vault` down to its rent-exempt minimum, paying the full
    /// swept amount to `creator` — the native-SOL sibling of
    /// `distribute_creator_fees`'s own rent-exempt-floor sweep, just without a
    /// shareholder split (100% to `creator`). Permissionless: anyone may crank
    /// it, funds always land at the fixed `creator_vault` -> `creator` PDA pair.
    fn collect_creator_fee<'a>(
        &self,
        accounts: CollectCreatorFeeCpiAccounts<'a>,
        creator_vault_bump: u8
    ) -> crate::sdk_core_cpi::Result<()> {
        self.collect_creator_fee_with_remaining_accounts(CollectCreatorFeeCpiCall {
        accounts,
        creator_vault_bump,
        signer_seeds: &[],
        remaining_accounts: &[],
    })
    }

    fn collect_creator_fee_signed<'a>(
        &self,
        accounts: CollectCreatorFeeCpiAccounts<'a>,
        creator_vault_bump: u8,
        signer_seeds: &[&[&[u8]]]
    ) -> crate::sdk_core_cpi::Result<()> {
        self.collect_creator_fee_with_remaining_accounts(CollectCreatorFeeCpiCall {
        accounts,
        creator_vault_bump,
        signer_seeds,
        remaining_accounts: &[],
    })
    }

    fn collect_creator_fee_with_remaining_accounts<'a>(
        &self,
        call: CollectCreatorFeeCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()>;

}

#[cfg(feature = "cpi")]
impl<'info> CollectCreatorFeeCpi<'info> for crate::sdk_core_cpi::Program<crate::Pump> {
    fn collect_creator_fee_with_remaining_accounts<'a>(
        &self,
        call: CollectCreatorFeeCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()> {
        let CollectCreatorFeeCpiCall { accounts, creator_vault_bump, signer_seeds, remaining_accounts } = call;
        let args = CollectCreatorFeeCpiIxArgs {
            creator_vault_bump,
        };
        let mut ix_data = crate::sdk_core_cpi::Vec::new();
        ix_data.extend_from_slice(&[20, 22, 86, 123, 198, 28, 219, 132]);
        #[cfg(not(feature = "borsh"))]
        {
        ix_data.extend_from_slice(crate::sdk_core_cpi::bytemuck::bytes_of(&args));
        }
        #[cfg(feature = "borsh")]
        {
            crate::sdk_core_cpi::borsh::BorshSerialize::serialize(&args, &mut ix_data).unwrap();
        }
        #[cfg(feature = "pinocchio")]
        {
            let mut metas_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount>::uninit() }; 32];
            let mut idx = 0;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(accounts.creator.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(accounts.creator_vault.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.system_program.info.view.address()));
            idx += 1;
            for (acc, is_writable, is_signer) in remaining_accounts {
                if idx >= 32 { break; }
                let meta = if *is_writable {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(acc.view.address())
                    }
                } else {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(acc.view.address())
                    }
                };
                metas_arr[idx].write(meta);
                idx += 1;
            }
            let account_metas = unsafe { core::slice::from_raw_parts(metas_arr.as_ptr() as *const crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount, idx) };
            let program_id_address = self.address();
            let instruction = crate::sdk_core_cpi::pinocchio::instruction::InstructionView {
                program_id: program_id_address.as_address(),
                accounts: account_metas,
                data: &ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.creator));
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.creator_vault));
            h_idx += 1;
            handles_arr[h_idx].write(accounts.system_program);
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed_pinocchio_handles(&instruction, account_handles, signer_seeds)
        }
        #[cfg(not(feature = "pinocchio"))]
        {
            use crate::sdk_core_cpi::ToAddress;
            let mut account_metas = crate::sdk_core_cpi::vec![
                ::naclac_lang::solana_program::instruction::AccountMeta::new(accounts.creator.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new(accounts.creator_vault.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.system_program.address(), false),
            ];
            for (acc, is_writable, is_signer) in remaining_accounts {
                let meta = if *is_writable {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new(acc.address(), *is_signer)
                } else {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(acc.address(), *is_signer)
                };
                account_metas.push(meta);
            }
            let instruction = ::naclac_lang::solana_program::instruction::Instruction {
                program_id: self.address(),
                accounts: account_metas,
                data: ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.creator));
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.creator_vault));
            h_idx += 1;
            handles_arr[h_idx].write(accounts.system_program);
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed(&instruction, account_handles, signer_seeds)
        }
    }
}

