// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
#[cfg(feature = "borsh")]
use crate::sdk_core_offchain::borsh::BorshSerialize;
#[cfg(feature = "offchain")]
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_offchain::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Clone, Debug))]
pub struct CreateIxArgs {
    pub name: crate::sdk_core_offchain::String,
    pub symbol: crate::sdk_core_offchain::String,
    pub uri: crate::sdk_core_offchain::String,
    pub creator: crate::sdk_core_offchain::Address,
    pub bonding_curve_bump: u8,
    pub metadata_bump: u8,
}

#[cfg(feature = "cpi")]
#[cfg(feature = "borsh")]
use crate::sdk_core_cpi::borsh::BorshSerialize;
#[cfg(feature = "cpi")]
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_cpi::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Clone, Debug))]
pub struct CreateCpiIxArgs {
    pub name: crate::sdk_core_cpi::ZcString,
    pub symbol: crate::sdk_core_cpi::ZcString,
    pub uri: crate::sdk_core_cpi::ZcString,
    pub creator: crate::sdk_core_cpi::Address,
    pub bonding_curve_bump: u8,
    pub metadata_bump: u8,
}

#[cfg(feature = "offchain")]
pub struct CreateAccounts {
    pub user: naclac_client::Address,
    /// SAFETY: the `seeds`/`bump` constraint fully validates this; it's a
    /// lamport-only PDA (no stored data) — only ever used as the mint's
    /// authority, signed via its own seeds for the `mint_to` CPI below.
    pub mint_authority: naclac_client::Address,
    pub mint: naclac_client::Address,
    pub bonding_curve: naclac_client::Address,
    pub associated_bonding_curve: naclac_client::Address,
    pub global: naclac_client::Address,
    /// SAFETY: the `address` constraint fully validates this; only used as
    /// the target program of the `create_metadata_via_cpi` call below, never
    /// deserialized.
    pub mpl_token_metadata: naclac_client::Address,
    /// SAFETY: the `seeds`/`bump`/`seeds::program` constraint fully verifies
    /// this is the real Metaplex metadata PDA for `mint`; never deserialized
    /// here — `mpl_token_metadata`'s own `CreateMetadataAccountV3` handler
    /// initializes it during the CPI below.
    pub metadata: naclac_client::Address,
    pub system_program: naclac_client::Address,
    pub token_program: naclac_client::Address,
    pub associated_token_program: naclac_client::Address,
}

#[cfg(feature = "offchain")]
pub fn build_create<'a>(
    provider: &'a naclac_client::NaclacProvider,
    program_id: naclac_client::Address,
    name: crate::sdk_core_offchain::String,
    symbol: crate::sdk_core_offchain::String,
    uri: crate::sdk_core_offchain::String,
    creator: crate::sdk_core_offchain::Address,
    bonding_curve_bump: u8,
    metadata_bump: u8,
    accounts: CreateAccounts,
) -> naclac_client::InstructionBuilder<'a> {
    let mut ix_data = crate::sdk_core_offchain::vec![24, 30, 200, 40, 5, 28, 7, 119];
    let args = CreateIxArgs {
        name,
        symbol,
        uri,
        creator,
        bonding_curve_bump,
        metadata_bump,
    };
    #[cfg(not(feature = "borsh"))]
    {
        ix_data.extend_from_slice(&(args.name.len() as u32).to_le_bytes());
        ix_data.extend_from_slice(args.name.as_bytes());
        ix_data.extend_from_slice(&(args.symbol.len() as u32).to_le_bytes());
        ix_data.extend_from_slice(args.symbol.as_bytes());
        ix_data.extend_from_slice(&(args.uri.len() as u32).to_le_bytes());
        ix_data.extend_from_slice(args.uri.as_bytes());
        ix_data.extend_from_slice(crate::sdk_core_offchain::bytemuck::bytes_of(&args.creator));
        ix_data.extend_from_slice(crate::sdk_core_offchain::bytemuck::bytes_of(&args.bonding_curve_bump));
        ix_data.extend_from_slice(crate::sdk_core_offchain::bytemuck::bytes_of(&args.metadata_bump));
    }
    #[cfg(feature = "borsh")]
    {
        crate::sdk_core_offchain::borsh::BorshSerialize::serialize(&args, &mut ix_data).unwrap();
    }
    naclac_client::InstructionBuilder::new(provider, program_id, ix_data)
        .account(naclac_client::AccountMeta { address: accounts.user, is_signer: true, is_writable: true }, "user")
        .account(naclac_client::AccountMeta { address: accounts.mint_authority, is_signer: false, is_writable: false }, "mint_authority")
        .account(naclac_client::AccountMeta { address: accounts.mint, is_signer: true, is_writable: true }, "mint")
        .account(naclac_client::AccountMeta { address: accounts.bonding_curve, is_signer: false, is_writable: true }, "bonding_curve")
        .account(naclac_client::AccountMeta { address: accounts.associated_bonding_curve, is_signer: false, is_writable: true }, "associated_bonding_curve")
        .account(naclac_client::AccountMeta { address: accounts.global, is_signer: false, is_writable: false }, "global")
        .account(naclac_client::AccountMeta { address: accounts.mpl_token_metadata, is_signer: false, is_writable: false }, "mpl_token_metadata")
        .account(naclac_client::AccountMeta { address: accounts.metadata, is_signer: false, is_writable: true }, "metadata")
        .account(naclac_client::AccountMeta { address: accounts.system_program, is_signer: false, is_writable: false }, "system_program")
        .account(naclac_client::AccountMeta { address: accounts.token_program, is_signer: false, is_writable: false }, "token_program")
        .account(naclac_client::AccountMeta { address: accounts.associated_token_program, is_signer: false, is_writable: false }, "associated_token_program")
}

#[cfg(feature = "cpi")]
pub struct CreateCpiAccounts<'a> {
    pub user: crate::sdk_core_cpi::CpiHandleMut<'a>,
    /// SAFETY: the `seeds`/`bump` constraint fully validates this; it's a
    /// lamport-only PDA (no stored data) — only ever used as the mint's
    /// authority, signed via its own seeds for the `mint_to` CPI below.
    pub mint_authority: crate::sdk_core_cpi::CpiHandle<'a>,
    pub mint: crate::sdk_core_cpi::CpiHandleMut<'a>,
    pub bonding_curve: crate::sdk_core_cpi::CpiHandleMut<'a>,
    pub associated_bonding_curve: crate::sdk_core_cpi::CpiHandleMut<'a>,
    pub global: crate::sdk_core_cpi::CpiHandle<'a>,
    /// SAFETY: the `address` constraint fully validates this; only used as
    /// the target program of the `create_metadata_via_cpi` call below, never
    /// deserialized.
    pub mpl_token_metadata: crate::sdk_core_cpi::CpiHandle<'a>,
    /// SAFETY: the `seeds`/`bump`/`seeds::program` constraint fully verifies
    /// this is the real Metaplex metadata PDA for `mint`; never deserialized
    /// here — `mpl_token_metadata`'s own `CreateMetadataAccountV3` handler
    /// initializes it during the CPI below.
    pub metadata: crate::sdk_core_cpi::CpiHandleMut<'a>,
    pub system_program: crate::sdk_core_cpi::CpiHandle<'a>,
    pub token_program: crate::sdk_core_cpi::CpiHandle<'a>,
    pub associated_token_program: crate::sdk_core_cpi::CpiHandle<'a>,
}

#[cfg(feature = "cpi")]
pub struct CreateCpiCall<'a> {
    pub accounts: CreateCpiAccounts<'a>,
    pub name: crate::sdk_core_cpi::ZcString,
    pub symbol: crate::sdk_core_cpi::ZcString,
    pub uri: crate::sdk_core_cpi::ZcString,
    pub creator: crate::sdk_core_cpi::Address,
    pub bonding_curve_bump: u8,
    pub metadata_bump: u8,
    pub signer_seeds: &'a [&'a [&'a [u8]]],
    pub remaining_accounts: &'a [(crate::sdk_core_cpi::AccountInfo, bool, bool)],
}

#[cfg(feature = "cpi")]
pub trait CreateCpi<'info> {
    fn create<'a>(
        &self,
        accounts: CreateCpiAccounts<'a>,
        name: crate::sdk_core_cpi::ZcString,
        symbol: crate::sdk_core_cpi::ZcString,
        uri: crate::sdk_core_cpi::ZcString,
        creator: crate::sdk_core_cpi::Address,
        bonding_curve_bump: u8,
        metadata_bump: u8
    ) -> crate::sdk_core_cpi::Result<()> {
        self.create_with_remaining_accounts(CreateCpiCall {
        accounts,
        name,
        symbol,
        uri,
        creator,
        bonding_curve_bump,
        metadata_bump,
        signer_seeds: &[],
        remaining_accounts: &[],
    })
    }

    fn create_signed<'a>(
        &self,
        accounts: CreateCpiAccounts<'a>,
        name: crate::sdk_core_cpi::ZcString,
        symbol: crate::sdk_core_cpi::ZcString,
        uri: crate::sdk_core_cpi::ZcString,
        creator: crate::sdk_core_cpi::Address,
        bonding_curve_bump: u8,
        metadata_bump: u8,
        signer_seeds: &[&[&[u8]]]
    ) -> crate::sdk_core_cpi::Result<()> {
        self.create_with_remaining_accounts(CreateCpiCall {
        accounts,
        name,
        symbol,
        uri,
        creator,
        bonding_curve_bump,
        metadata_bump,
        signer_seeds,
        remaining_accounts: &[],
    })
    }

    fn create_with_remaining_accounts<'a>(
        &self,
        call: CreateCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()>;

}

#[cfg(feature = "cpi")]
impl<'info> CreateCpi<'info> for crate::sdk_core_cpi::Program<crate::Pump> {
    fn create_with_remaining_accounts<'a>(
        &self,
        call: CreateCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()> {
        let CreateCpiCall { accounts, name, symbol, uri, creator, bonding_curve_bump, metadata_bump, signer_seeds, remaining_accounts } = call;
        let args = CreateCpiIxArgs {
            name,
            symbol,
            uri,
            creator,
            bonding_curve_bump,
            metadata_bump,
        };
        let mut ix_data = crate::sdk_core_cpi::Vec::new();
        ix_data.extend_from_slice(&[24, 30, 200, 40, 5, 28, 7, 119]);
        #[cfg(not(feature = "borsh"))]
        {
        ix_data.extend_from_slice(&(args.name.len() as u32).to_le_bytes());
        ix_data.extend_from_slice(args.name.as_bytes());
        ix_data.extend_from_slice(&(args.symbol.len() as u32).to_le_bytes());
        ix_data.extend_from_slice(args.symbol.as_bytes());
        ix_data.extend_from_slice(&(args.uri.len() as u32).to_le_bytes());
        ix_data.extend_from_slice(args.uri.as_bytes());
        ix_data.extend_from_slice(crate::sdk_core_cpi::bytemuck::bytes_of(&args.creator));
        ix_data.extend_from_slice(crate::sdk_core_cpi::bytemuck::bytes_of(&args.bonding_curve_bump));
        ix_data.extend_from_slice(crate::sdk_core_cpi::bytemuck::bytes_of(&args.metadata_bump));
        }
        #[cfg(feature = "borsh")]
        {
            crate::sdk_core_cpi::borsh::BorshSerialize::serialize(&args, &mut ix_data).unwrap();
        }
        #[cfg(feature = "pinocchio")]
        {
            let mut metas_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount>::uninit() }; 32];
            let mut idx = 0;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable_signer(accounts.user.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.mint_authority.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable_signer(accounts.mint.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(accounts.bonding_curve.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(accounts.associated_bonding_curve.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.global.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.mpl_token_metadata.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(accounts.metadata.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.system_program.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.token_program.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.associated_token_program.info.view.address()));
            idx += 1;
            for (acc, is_writable, is_signer) in remaining_accounts {
                if idx >= 32 { break; }
                let meta = if *is_writable {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(acc.view.address())
                    }
                } else {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(acc.view.address())
                    }
                };
                metas_arr[idx].write(meta);
                idx += 1;
            }
            let account_metas = unsafe { core::slice::from_raw_parts(metas_arr.as_ptr() as *const crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount, idx) };
            let program_id_address = self.address();
            let instruction = crate::sdk_core_cpi::pinocchio::instruction::InstructionView {
                program_id: program_id_address.as_address(),
                accounts: account_metas,
                data: &ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.user));
            h_idx += 1;
            handles_arr[h_idx].write(accounts.mint_authority);
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.mint));
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.bonding_curve));
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.associated_bonding_curve));
            h_idx += 1;
            handles_arr[h_idx].write(accounts.global);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.mpl_token_metadata);
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.metadata));
            h_idx += 1;
            handles_arr[h_idx].write(accounts.system_program);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.token_program);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.associated_token_program);
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed_pinocchio_handles(&instruction, account_handles, signer_seeds)
        }
        #[cfg(not(feature = "pinocchio"))]
        {
            use crate::sdk_core_cpi::ToAddress;
            let mut account_metas = crate::sdk_core_cpi::vec![
                ::naclac_lang::solana_program::instruction::AccountMeta::new(accounts.user.address(), true),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.mint_authority.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new(accounts.mint.address(), true),
                ::naclac_lang::solana_program::instruction::AccountMeta::new(accounts.bonding_curve.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new(accounts.associated_bonding_curve.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.global.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.mpl_token_metadata.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new(accounts.metadata.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.system_program.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.token_program.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.associated_token_program.address(), false),
            ];
            for (acc, is_writable, is_signer) in remaining_accounts {
                let meta = if *is_writable {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new(acc.address(), *is_signer)
                } else {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(acc.address(), *is_signer)
                };
                account_metas.push(meta);
            }
            let instruction = ::naclac_lang::solana_program::instruction::Instruction {
                program_id: self.address(),
                accounts: account_metas,
                data: ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.user));
            h_idx += 1;
            handles_arr[h_idx].write(accounts.mint_authority);
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.mint));
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.bonding_curve));
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.associated_bonding_curve));
            h_idx += 1;
            handles_arr[h_idx].write(accounts.global);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.mpl_token_metadata);
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.metadata));
            h_idx += 1;
            handles_arr[h_idx].write(accounts.system_program);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.token_program);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.associated_token_program);
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed(&instruction, account_handles, signer_seeds)
        }
    }
}

