[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
donation_relay = "8MWkme4Dfe5NBPh17itoSro62n4FTGLmPNXYFRCUzu7A"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test-rust = "cargo test -- --show-output"
test-node = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
