// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(all(feature = "borsh", feature = "offchain"))]
use crate::sdk_core_offchain::borsh::{BorshDeserialize, BorshSerialize};
#[cfg(all(feature = "borsh", not(feature = "offchain")))]
use crate::sdk_core_cpi::borsh::{BorshDeserialize, BorshSerialize};

#[cfg(feature = "offchain")]
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize, BorshDeserialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_offchain::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Copy, Clone, Debug))]
#[cfg_attr(not(feature = "borsh"), repr(C))]
pub struct EpochTracker {
    pub bump: u8,
    pub state: u8,
    pub config_id: crate::sdk_core_offchain::Address,
    pub mint: crate::sdk_core_offchain::Address,
    pub current_epoch: u64,
}

#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Zeroable for EpochTracker {}
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Pod for EpochTracker {}
#[cfg(feature = "cpi")]
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize, BorshDeserialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_cpi::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Copy, Clone, Debug))]
#[cfg_attr(not(feature = "borsh"), repr(C))]
pub struct EpochTrackerCpi {
    pub bump: u8,
    pub state: u8,
    pub config_id: crate::sdk_core_cpi::Address,
    pub mint: crate::sdk_core_cpi::Address,
    pub current_epoch: u64,
}

#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Zeroable for EpochTrackerCpi {}
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Pod for EpochTrackerCpi {}
#[cfg(all(feature = "cpi", not(feature = "offchain")))]
pub type EpochTracker = EpochTrackerCpi;


/// 8-byte on-chain discriminator for `EpochTracker` accounts.
pub const EPOCHTRACKER_DISCRIMINATOR: [u8; 8] = [224, 134, 45, 78, 214, 142, 233, 244];
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
impl naclac_client::NaclacDecode for EpochTracker {
    const DISCRIMINATOR: Option<[u8; 8]> = Some(EPOCHTRACKER_DISCRIMINATOR);
    fn naclac_decode(data: &[u8]) -> Result<Self, naclac_client::NaclacClientError> {
        naclac_client::decode_pod_checked::<Self>(data, EPOCHTRACKER_DISCRIMINATOR)
    }
}

#[cfg(feature = "offchain")]
#[cfg(feature = "borsh")]
impl naclac_client::NaclacDecode for EpochTracker {
    const DISCRIMINATOR: Option<[u8; 8]> = Some(EPOCHTRACKER_DISCRIMINATOR);
    fn naclac_decode(data: &[u8]) -> Result<Self, naclac_client::NaclacClientError> {
        naclac_client::decode_borsh_checked::<Self>(data, EPOCHTRACKER_DISCRIMINATOR)
    }
}
#[cfg(feature = "offchain")]
/// Fetches and decodes a `EpochTracker` account from the chain.
pub fn fetch_epoch_tracker(
    provider: &naclac_client::NaclacProvider,
    address: &naclac_client::Address,
) -> Result<EpochTracker, naclac_client::NaclacClientError> {
    let raw = provider.get_account_data(address)?;
    <EpochTracker as naclac_client::NaclacDecode>::naclac_decode(&raw)
}

#[cfg(feature = "offchain")]
/// Fetches a `EpochTracker` account. Returns `None` if the account does not exist.
pub fn fetch_maybe_epoch_tracker(
    provider: &naclac_client::NaclacProvider,
    address: &naclac_client::Address,
) -> Result<Option<EpochTracker>, naclac_client::NaclacClientError> {
    match fetch_epoch_tracker(provider, address) {
        Ok(a) => Ok(Some(a)),
        Err(naclac_client::NaclacClientError::AccountNotFound(_)) => Ok(None),
        Err(e) => Err(e),
    }
}

#[cfg(feature = "offchain")]
/// Fetches and decodes every on-chain `EpochTracker` account owned by `program_id`.
pub fn fetch_all_epoch_tracker(
    provider: &naclac_client::NaclacProvider,
    program_id: &naclac_client::Address,
) -> Result<crate::sdk_core_offchain::Vec<(naclac_client::Address, EpochTracker)>, naclac_client::NaclacClientError> {
    let raw_accounts = provider.get_program_accounts(program_id, Some(&EPOCHTRACKER_DISCRIMINATOR))?;
    let mut results = crate::sdk_core_offchain::Vec::new();
    for (address, data) in raw_accounts {
        if let Ok(value) = <EpochTracker as naclac_client::NaclacDecode>::naclac_decode(&data) {
            results.push((address, value));
        }
    }
    Ok(results)
}
