// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
pub const PROGRAM_ID: naclac_client::Address = naclac_client::Address::new_from_array([
    36, 6, 36, 109, 148, 0, 58, 29, 125, 215, 52, 200, 39, 197, 130, 152, 236, 54, 80, 154, 47, 252, 16, 224, 253, 173, 91, 83, 65, 105, 106, 202
]);

#[cfg(not(feature = "offchain"))]
pub const PROGRAM_ID: crate::sdk_core::Address = crate::sdk_core::Address::new_from_array([
    36, 6, 36, 109, 148, 0, 58, 29, 125, 215, 52, 200, 39, 197, 130, 152, 236, 54, 80, 154, 47, 252, 16, 224, 253, 173, 91, 83, 65, 105, 106, 202
]);

pub const SEED_VAULT: &[u8] = &[118, 97, 117, 108, 116];
pub const SEED_USER_ACCOUNT: &[u8] = &[117, 115, 101, 114, 95, 118, 97, 117, 108, 116];
