// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#![cfg_attr(all(feature = "cpi", feature = "pinocchio"), no_std)]

#[cfg(feature = "cpi")]
pub use naclac_lang::prelude as sdk_core;
#[cfg(all(feature = "offchain", not(feature = "cpi")))]
pub use naclac_client as sdk_core;

#[cfg(feature = "offchain")]
pub mod components;
pub mod instructions;
pub mod types;

#[cfg(feature = "offchain")]
pub use components::*;
pub use instructions::*;
pub use types::*;

#[macro_export]
macro_rules! declare_id {
    ($id:expr) => {};
}

declare_id!("2Zy945UvutdjBUTq6xrpuW86jYzbGtiPogMGhGUQWX4m");

#[cfg(feature = "offchain")]
pub fn get_config_pda(
    program_id: &naclac_client::Address
) -> (naclac_client::Address, u8) {
    naclac_client::Address::find_program_address(
        &[
            &[99, 111, 110, 102, 105, 103],
        ],
        program_id,
    )
}

#[cfg(feature = "offchain")]
pub fn get_vault_pda(
    program_id: &naclac_client::Address
) -> (naclac_client::Address, u8) {
    naclac_client::Address::find_program_address(
        &[
            &[118, 97, 117, 108, 116],
        ],
        program_id,
    )
}

#[cfg(feature = "cpi")]
#[derive(Clone, Copy)]
pub struct DiscriminatorZc;

#[cfg(feature = "cpi")]
impl sdk_core::Id for DiscriminatorZc {
    fn id() -> sdk_core::Address {
        sdk_core::Address::new_from_array([23, 77, 191, 204, 92, 163, 198, 34, 8, 111, 181, 117, 87, 69, 198, 106, 126, 252, 92, 71, 178, 231, 218, 36, 185, 15, 112, 228, 236, 175, 90, 170])
    }
}

