// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
pub const PROGRAM_ID: naclac_client::Address = naclac_client::Address::new_from_array([
    220, 191, 145, 180, 52, 26, 5, 24, 164, 79, 39, 18, 54, 152, 88, 115, 239, 167, 40, 41, 221, 74, 25, 5, 211, 165, 218, 234, 238, 117, 251, 38
]);

#[cfg(not(feature = "offchain"))]
pub const PROGRAM_ID: crate::sdk_core::Address = crate::sdk_core::Address::new_from_array([
    220, 191, 145, 180, 52, 26, 5, 24, 164, 79, 39, 18, 54, 152, 88, 115, 239, 167, 40, 41, 221, 74, 25, 5, 211, 165, 218, 234, 238, 117, 251, 38
]);

pub const SEED_VAULT: &[u8] = &[118, 97, 117, 108, 116];
pub const SEED_LEDGER: &[u8] = &[108, 101, 100, 103, 101, 114];
pub const SEED_SEEDED: &[u8] = &[115, 101, 101, 100, 101, 100];
