// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
pub const PROGRAM_ID: naclac_client::Address = naclac_client::Address::new_from_array([
    123, 159, 85, 117, 61, 191, 37, 235, 151, 189, 246, 158, 253, 240, 1, 123, 204, 76, 215, 48, 217, 20, 189, 201, 65, 196, 255, 157, 61, 147, 35, 193
]);

#[cfg(not(feature = "offchain"))]
pub const PROGRAM_ID: crate::sdk_core::Address = crate::sdk_core::Address::new_from_array([
    123, 159, 85, 117, 61, 191, 37, 235, 151, 189, 246, 158, 253, 240, 1, 123, 204, 76, 215, 48, 217, 20, 189, 201, 65, 196, 255, 157, 61, 147, 35, 193
]);

