// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ProgramError {
    InvalidMint,
    Unauthorized,
    Overflow,
    ZeroAmount,
}

impl ProgramError {
    pub fn from_code(code: u32) -> Option<Self> {
        match code {
            6000 => Some(Self::InvalidMint),
            6001 => Some(Self::Unauthorized),
            6002 => Some(Self::Overflow),
            6003 => Some(Self::ZeroAmount),
            _ => None,
        }
    }

    pub fn message(&self) -> &'static str {
        match self {
            Self::InvalidMint => "Invalid mint for the trade.",
            Self::Unauthorized => "Unauthorized action.",
            Self::Overflow => "Overflow or math error.",
            Self::ZeroAmount => "The amount provided must be greater than zero.",
        }
    }
}

