[package]
name = "donation_relay"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]
custom-heap = []
custom-panic = []
debug-mode = []
default = ["pinocchio"]
pinocchio = ["naclac-lang/pinocchio"]

[dependencies]
naclac-lang = { version = "0.1.0", path = "../../../../naclac-lang", default-features = false, features = ["token"] }

[lints]
workspace = true
