[package]
name = "token"
version = "0.1.0"
description = "Regression test: token::*/mint::* account constraints and real SPL token CPI (pinocchio backend)"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]
custom-heap = []
custom-panic = []
debug-mode = []
default = ["pinocchio"]
pinocchio = ["naclac-lang/pinocchio"]

[dependencies]
naclac-lang = { version = "0.1.0", path = "../../../../naclac-lang", default-features = false, features = ["token"] }
pinocchio-memo = "^0.4"

[dev-dependencies]
naclac-client = { version = "0.1.0", path = "../../../../naclac-client" }
token-client = { version = "0.1.0", path = "../../clients/rust/token" }
spl-token-metadata-interface = "1.0.1"
spl-type-length-value = "0.9.1"
spl-token-2022-interface = "3.1.1"
solana-message = "^4"

[lints]
workspace = true
