// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ProgramError {
    /// the provided authority does not match `vault.admin`
    WrongAdmin,
}

impl ProgramError {
    pub fn from_code(code: u32) -> Option<Self> {
        match code {
            6000 => Some(Self::WrongAdmin),
            _ => None,
        }
    }

    pub fn message(&self) -> &'static str {
        match self {
            Self::WrongAdmin => "the provided authority does not match `vault.admin`",
        }
    }
}

