// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#![cfg_attr(all(feature = "cpi", feature = "pinocchio"), no_std)]

#[cfg(feature = "cpi")]
pub use naclac_lang::prelude as sdk_core_cpi;
#[cfg(feature = "offchain")]
pub use naclac_client as sdk_core_offchain;

#[cfg(feature = "offchain")]
pub mod components;
pub mod instructions;
pub mod types;

#[cfg(feature = "offchain")]
pub use components::*;
pub use instructions::*;
pub use types::*;

#[macro_export]
macro_rules! declare_id {
    ($id:expr) => {};
}

declare_id!("2tRXuaWn92zA5D4ftmsu693hXg3FXUVymLcqDkPrE27A");

#[cfg(feature = "offchain")]
pub fn get_child_pda(
    program_id: &naclac_client::Address,
    registry_bump: u8
) -> (naclac_client::Address, u8) {
    let registry_bump_arr = [registry_bump];
    naclac_client::Address::find_program_address(
        &[
            &[99, 104, 105, 108, 100],
            &registry_bump_arr,
        ],
        program_id,
    )
}

#[cfg(feature = "offchain")]
pub fn get_child_safe_pda(
    program_id: &naclac_client::Address,
    registry_bump: u8
) -> (naclac_client::Address, u8) {
    let registry_bump_arr = [registry_bump];
    naclac_client::Address::find_program_address(
        &[
            &[99, 104, 105, 108, 100, 95, 115, 97, 102, 101],
            &registry_bump_arr,
        ],
        program_id,
    )
}

#[cfg(feature = "offchain")]
pub fn get_config_entry_pda(
    program_id: &naclac_client::Address,
    config_program_id: &naclac_client::Address
) -> (naclac_client::Address, u8) {
    naclac_client::Address::find_program_address(
        &[
            &[99, 111, 110, 102, 105, 103, 95, 101, 110, 116, 114, 121],
            config_program_id.as_ref(),
        ],
        program_id,
    )
}

#[cfg(feature = "offchain")]
pub fn get_entry_pda(
    program_id: &naclac_client::Address,
    registry: &naclac_client::Address
) -> (naclac_client::Address, u8) {
    naclac_client::Address::find_program_address(
        &[
            &[101, 110, 116, 114, 121],
            registry.as_ref(),
        ],
        program_id,
    )
}

#[cfg(feature = "offchain")]
pub fn get_registry_pda(
    program_id: &naclac_client::Address
) -> (naclac_client::Address, u8) {
    naclac_client::Address::find_program_address(
        &[
            &[114, 101, 103, 105, 115, 116, 114, 121],
        ],
        program_id,
    )
}

// get_tagged_child_pda intentionally not generated: this PDA's seeds include
// `registry.label`, a field read from another account whose type is not a plain
// primitive (e.g. a nested/defined type) — naclac-syn couldn't resolve
// it from the backing component's struct definition, so there's no
// reliable way to generate correct code. Derive it manually — fetch the
// account, read the field, and call Address::find_program_address
// yourself with the correct byte conversion for that field's type.

#[cfg(feature = "cpi")]
#[derive(Clone, Copy)]
pub struct PdaSeeds;

#[cfg(feature = "cpi")]
impl sdk_core_cpi::Id for PdaSeeds {
    fn id() -> sdk_core_cpi::Address {
        sdk_core_cpi::Address::new_from_array([28, 8, 12, 47, 43, 221, 201, 216, 61, 75, 102, 183, 13, 148, 254, 225, 62, 238, 5, 40, 118, 202, 137, 12, 139, 40, 4, 57, 175, 0, 147, 33])
    }
}

