// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
pub const PROGRAM_ID: naclac_client::Address = naclac_client::Address::new_from_array([
    129, 168, 87, 235, 165, 26, 209, 14, 195, 11, 185, 244, 99, 186, 240, 248, 163, 178, 182, 218, 44, 247, 238, 5, 124, 105, 182, 30, 178, 101, 162, 248
]);

#[cfg(not(feature = "offchain"))]
pub const PROGRAM_ID: crate::sdk_core::Address = crate::sdk_core::Address::new_from_array([
    129, 168, 87, 235, 165, 26, 209, 14, 195, 11, 185, 244, 99, 186, 240, 248, 163, 178, 182, 218, 44, 247, 238, 5, 124, 105, 182, 30, 178, 101, 162, 248
]);

pub const SEED_MINT: &[u8] = &[109, 105, 110, 116];
