// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
pub const PROGRAM_ID: naclac_client::Address = naclac_client::Address::new_from_array([
    116, 160, 86, 82, 248, 105, 32, 166, 17, 57, 245, 99, 88, 171, 78, 132, 34, 207, 106, 105, 27, 23, 177, 13, 84, 100, 151, 96, 23, 63, 63, 197
]);

#[cfg(feature = "cpi")]
pub const PROGRAM_ID_CPI: crate::sdk_core_cpi::Address = crate::sdk_core_cpi::Address::new_from_array([
    116, 160, 86, 82, 248, 105, 32, 166, 17, 57, 245, 99, 88, 171, 78, 132, 34, 207, 106, 105, 27, 23, 177, 13, 84, 100, 151, 96, 23, 63, 63, 197
]);

pub const FEE_CONFIG_SEED: &[u8] = &[102, 101, 101, 95, 99, 111, 110, 102, 105, 103];
pub const FEE_PROGRAM_GLOBAL_SEED: [u8; 18] = [102, 101, 101, 45, 112, 114, 111, 103, 114, 97, 109, 45, 103, 108, 111, 98, 97, 108];
pub const SHARING_CONFIG_SEED: [u8; 14] = [115, 104, 97, 114, 105, 110, 103, 45, 99, 111, 110, 102, 105, 103];
pub const SOCIAL_FEE_PDA_SEED: [u8; 14] = [115, 111, 99, 105, 97, 108, 45, 102, 101, 101, 45, 112, 100, 97];
pub const DONATION_FEE_PDA_SEED: [u8; 16] = [100, 111, 110, 97, 116, 105, 111, 110, 45, 102, 101, 101, 45, 112, 100, 97];
pub const BUYBACK_VAULT_SEED: [u8; 13] = [98, 117, 121, 98, 97, 99, 107, 45, 118, 97, 117, 108, 116];
/// Bonding Curve Program Global Seed
pub const PUMP_GLOBAL_SEED: [u8; 6] = [103, 108, 111, 98, 97, 108];
/// Signer-only PDA (no stored data) that `pump_fees` CPI-signs with to prove
/// to `pump::migrate_bonding_curve_creator` that the call genuinely came
/// from this program, not an untrusted direct caller. Must match `pump`'s
/// own `PUMP_FEES_AUTHORITY_SEED` exactly.
pub const PUMP_FEES_AUTHORITY_SEED: &[u8] = &[112, 117, 109, 112, 45, 102, 101, 101, 115, 45, 97, 117, 116, 104, 111, 114, 105, 116, 121];
/// `pump`'s own signer-only authority PDA — proves a CPI into `get_fees`
/// genuinely came from `pump`, not an untrusted direct caller. Must match
/// `pump`'s own `PUMP_AUTHORITY_SEED` exactly.
pub const PUMP_AUTHORITY_SEED: &[u8] = &[112, 117, 109, 112, 45, 97, 117, 116, 104, 111, 114, 105, 116, 121];
pub const BONDING_CURVE_SEED: &[u8] = &[98, 111, 110, 100, 105, 110, 103, 45, 99, 117, 114, 118, 101];
/// pump-amm's per-mint pool-authority seed (migration-time canonical pool owner).
pub const POOL_AUTHORITY_SEED: &[u8] = &[112, 111, 111, 108, 45, 97, 117, 116, 104, 111, 114, 105, 116, 121];
/// pump-amm's pool seed: `[POOL_SEED, index, pool_authority, base_mint, quote_mint]`.
pub const POOL_SEED: &[u8] = &[112, 111, 111, 108];
/// Pump AMM's creator-vault-authority seed.
pub const AMM_CREATOR_VAULT_AUTHORITY_SEED: [u8; 13] = [99, 114, 101, 97, 116, 111, 114, 95, 118, 97, 117, 108, 116];
/// Pump bonding curve's creator-vault seed.
pub const PUMP_CREATOR_VAULT_SEED: [u8; 13] = [99, 114, 101, 97, 116, 111, 114, 45, 118, 97, 117, 108, 116];
/// `donation_relay_program`'s epoch-tracker satellite-account seed.
pub const EPOCH_TRACKER_V1: &[u8] = &[101, 112, 111, 99, 104, 95, 116, 114, 97, 99, 107, 101, 114, 95, 118, 49];
/// `donation_relay_program`'s debouncer satellite-account seed.
pub const DEBOUNCER_V1: &[u8] = &[100, 101, 98, 111, 117, 110, 99, 101, 114, 95, 118, 49];
/// `donation_relay_program`'s mint-whitelist satellite-account seed.
pub const MINT_WHITELIST_V1: &[u8] = &[109, 105, 110, 116, 95, 119, 104, 105, 116, 101, 108, 105, 115, 116, 95, 118, 49];
/// `donation_relay_program`'s `donate_pubkey_config_id_with_payer` instruction discriminator.
pub const IX_DONATE_PUBKEY_CONFIG_ID_WITH_PAYER_V1: [u8; 8] = [120, 217, 57, 241, 135, 104, 139, 184];
pub const MAX_BUYBACK_INDEX: u8 = 8;
#[cfg(feature = "offchain")]
pub const PUMP_PROGRAM_ID: naclac_client::Address = naclac_client::Address::new_from_array([219, 228, 38, 61, 197, 238, 49, 67, 254, 52, 90, 137, 137, 108, 51, 148, 9, 123, 135, 93, 203, 217, 165, 115, 223, 190, 144, 135, 242, 216, 223, 192]);
#[cfg(feature = "cpi")]
pub const PUMP_PROGRAM_ID_CPI: crate::sdk_core_cpi::Address = crate::sdk_core_cpi::Address::new_from_array([219, 228, 38, 61, 197, 238, 49, 67, 254, 52, 90, 137, 137, 108, 51, 148, 9, 123, 135, 93, 203, 217, 165, 115, 223, 190, 144, 135, 242, 216, 223, 192]);
#[cfg(feature = "offchain")]
pub const PUMP_AMM_PROGRAM_ID: naclac_client::Address = naclac_client::Address::new_from_array([252, 69, 211, 229, 209, 250, 91, 185, 95, 119, 96, 125, 211, 65, 169, 106, 209, 112, 144, 171, 161, 186, 45, 122, 136, 122, 226, 73, 138, 146, 134, 211]);
#[cfg(feature = "cpi")]
pub const PUMP_AMM_PROGRAM_ID_CPI: crate::sdk_core_cpi::Address = crate::sdk_core_cpi::Address::new_from_array([252, 69, 211, 229, 209, 250, 91, 185, 95, 119, 96, 125, 211, 65, 169, 106, 209, 112, 144, 171, 161, 186, 45, 122, 136, 122, 226, 73, 138, 146, 134, 211]);
#[cfg(feature = "offchain")]
pub const DONATION_RELAY_PROGRAM_ID: naclac_client::Address = naclac_client::Address::new_from_array([23, 118, 164, 191, 192, 201, 243, 51, 32, 226, 179, 109, 83, 249, 158, 252, 119, 104, 39, 62, 96, 34, 156, 219, 131, 24, 131, 100, 36, 174, 205, 212]);
#[cfg(feature = "cpi")]
pub const DONATION_RELAY_PROGRAM_ID_CPI: crate::sdk_core_cpi::Address = crate::sdk_core_cpi::Address::new_from_array([23, 118, 164, 191, 192, 201, 243, 51, 32, 226, 179, 109, 83, 249, 158, 252, 119, 104, 39, 62, 96, 34, 156, 219, 131, 24, 131, 100, 36, 174, 205, 212]);
#[cfg(feature = "offchain")]
pub const WSOL_MINT: naclac_client::Address = naclac_client::Address::new_from_array([6, 155, 136, 87, 254, 171, 129, 132, 251, 104, 127, 99, 70, 24, 192, 53, 218, 196, 57, 220, 26, 235, 59, 85, 152, 160, 240, 0, 0, 0, 0, 1]);
#[cfg(feature = "cpi")]
pub const WSOL_MINT_CPI: crate::sdk_core_cpi::Address = crate::sdk_core_cpi::Address::new_from_array([6, 155, 136, 87, 254, 171, 129, 132, 251, 104, 127, 99, 70, 24, 192, 53, 218, 196, 57, 220, 26, 235, 59, 85, 152, 160, 240, 0, 0, 0, 0, 1]);
