// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
#[cfg(feature = "borsh")]
use crate::sdk_core_offchain::borsh::BorshSerialize;
#[cfg(feature = "offchain")]
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_offchain::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Copy, Clone, Debug))]
#[cfg_attr(not(feature = "borsh"), repr(C, packed))]
pub struct CreateDonationFeePdaIxArgs {
    pub bonding_curve_bump: u8,
    pub pool_authority_bump: u8,
    pub pool_bump: u8,
    pub donation_fee_pda_bump: u8,
}

#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Zeroable for CreateDonationFeePdaIxArgs {}
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Pod for CreateDonationFeePdaIxArgs {}

#[cfg(feature = "cpi")]
#[cfg(feature = "borsh")]
use crate::sdk_core_cpi::borsh::BorshSerialize;
#[cfg(feature = "cpi")]
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_cpi::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Copy, Clone, Debug))]
#[cfg_attr(not(feature = "borsh"), repr(C, packed))]
pub struct CreateDonationFeePdaCpiIxArgs {
    pub bonding_curve_bump: u8,
    pub pool_authority_bump: u8,
    pub pool_bump: u8,
    pub donation_fee_pda_bump: u8,
}

#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Zeroable for CreateDonationFeePdaCpiIxArgs {}
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Pod for CreateDonationFeePdaCpiIxArgs {}

#[cfg(feature = "offchain")]
pub struct CreateDonationFeePdaAccounts {
    pub payer: naclac_client::Address,
    pub system_program: naclac_client::Address,
    pub fee_program_global: naclac_client::Address,
    /// SAFETY: only used as PDA seed material below; not deserialized.
    pub base_mint: naclac_client::Address,
    pub bonding_curve: naclac_client::Address,
    /// SAFETY: only used as PDA seed material for `pool` below; not deserialized.
    pub pool_authority: naclac_client::Address,
    /// SAFETY: address is always verified via seeds; owner/content are only
    /// checked when `bonding_curve.complete` (see module comment above).
    pub pool: naclac_client::Address,
    /// SAFETY: dead — see module comment above. Kept for account-shape parity only.
    pub sharing_config: naclac_client::Address,
    /// SAFETY: plain address material distinguishing donation campaigns for
    /// the same `base_mint`; not a signer, never deserialized.
    pub config_id: naclac_client::Address,
    pub donation_fee_pda: naclac_client::Address,
}

#[cfg(feature = "offchain")]
pub fn build_create_donation_fee_pda<'a>(
    provider: &'a naclac_client::NaclacProvider,
    program_id: naclac_client::Address,
    bonding_curve_bump: u8,
    pool_authority_bump: u8,
    pool_bump: u8,
    donation_fee_pda_bump: u8,
    accounts: CreateDonationFeePdaAccounts,
) -> naclac_client::InstructionBuilder<'a> {
    let mut ix_data = crate::sdk_core_offchain::vec![244, 139, 16, 88, 14, 255, 122, 26];
    let args = CreateDonationFeePdaIxArgs {
        bonding_curve_bump,
        pool_authority_bump,
        pool_bump,
        donation_fee_pda_bump,
    };
    #[cfg(not(feature = "borsh"))]
    {
        ix_data.extend_from_slice(crate::sdk_core_offchain::bytemuck::bytes_of(&args));
    }
    #[cfg(feature = "borsh")]
    {
        crate::sdk_core_offchain::borsh::BorshSerialize::serialize(&args, &mut ix_data).unwrap();
    }
    naclac_client::InstructionBuilder::new(provider, program_id, ix_data)
        .account(naclac_client::AccountMeta { address: accounts.payer, is_signer: true, is_writable: true }, "payer")
        .account(naclac_client::AccountMeta { address: accounts.system_program, is_signer: false, is_writable: false }, "system_program")
        .account(naclac_client::AccountMeta { address: accounts.fee_program_global, is_signer: false, is_writable: false }, "fee_program_global")
        .account(naclac_client::AccountMeta { address: accounts.base_mint, is_signer: false, is_writable: false }, "base_mint")
        .account(naclac_client::AccountMeta { address: accounts.bonding_curve, is_signer: false, is_writable: false }, "bonding_curve")
        .account(naclac_client::AccountMeta { address: accounts.pool_authority, is_signer: false, is_writable: false }, "pool_authority")
        .account(naclac_client::AccountMeta { address: accounts.pool, is_signer: false, is_writable: false }, "pool")
        .account(naclac_client::AccountMeta { address: accounts.sharing_config, is_signer: false, is_writable: false }, "sharing_config")
        .account(naclac_client::AccountMeta { address: accounts.config_id, is_signer: false, is_writable: false }, "config_id")
        .account(naclac_client::AccountMeta { address: accounts.donation_fee_pda, is_signer: false, is_writable: true }, "donation_fee_pda")
}

#[cfg(feature = "cpi")]
pub struct CreateDonationFeePdaCpiAccounts<'a> {
    pub payer: crate::sdk_core_cpi::CpiHandleMut<'a>,
    pub system_program: crate::sdk_core_cpi::CpiHandle<'a>,
    pub fee_program_global: crate::sdk_core_cpi::CpiHandle<'a>,
    /// SAFETY: only used as PDA seed material below; not deserialized.
    pub base_mint: crate::sdk_core_cpi::CpiHandle<'a>,
    pub bonding_curve: crate::sdk_core_cpi::CpiHandle<'a>,
    /// SAFETY: only used as PDA seed material for `pool` below; not deserialized.
    pub pool_authority: crate::sdk_core_cpi::CpiHandle<'a>,
    /// SAFETY: address is always verified via seeds; owner/content are only
    /// checked when `bonding_curve.complete` (see module comment above).
    pub pool: crate::sdk_core_cpi::CpiHandle<'a>,
    /// SAFETY: dead — see module comment above. Kept for account-shape parity only.
    pub sharing_config: crate::sdk_core_cpi::CpiHandle<'a>,
    /// SAFETY: plain address material distinguishing donation campaigns for
    /// the same `base_mint`; not a signer, never deserialized.
    pub config_id: crate::sdk_core_cpi::CpiHandle<'a>,
    pub donation_fee_pda: crate::sdk_core_cpi::CpiHandleMut<'a>,
}

#[cfg(feature = "cpi")]
pub struct CreateDonationFeePdaCpiCall<'a> {
    pub accounts: CreateDonationFeePdaCpiAccounts<'a>,
    pub bonding_curve_bump: u8,
    pub pool_authority_bump: u8,
    pub pool_bump: u8,
    pub donation_fee_pda_bump: u8,
    pub signer_seeds: &'a [&'a [&'a [u8]]],
    pub remaining_accounts: &'a [(crate::sdk_core_cpi::AccountInfo, bool, bool)],
}

#[cfg(feature = "cpi")]
pub trait CreateDonationFeePdaCpi<'info> {
    fn create_donation_fee_pda<'a>(
        &self,
        accounts: CreateDonationFeePdaCpiAccounts<'a>,
        bonding_curve_bump: u8,
        pool_authority_bump: u8,
        pool_bump: u8,
        donation_fee_pda_bump: u8
    ) -> crate::sdk_core_cpi::Result<()> {
        self.create_donation_fee_pda_with_remaining_accounts(CreateDonationFeePdaCpiCall {
        accounts,
        bonding_curve_bump,
        pool_authority_bump,
        pool_bump,
        donation_fee_pda_bump,
        signer_seeds: &[],
        remaining_accounts: &[],
    })
    }

    fn create_donation_fee_pda_signed<'a>(
        &self,
        accounts: CreateDonationFeePdaCpiAccounts<'a>,
        bonding_curve_bump: u8,
        pool_authority_bump: u8,
        pool_bump: u8,
        donation_fee_pda_bump: u8,
        signer_seeds: &[&[&[u8]]]
    ) -> crate::sdk_core_cpi::Result<()> {
        self.create_donation_fee_pda_with_remaining_accounts(CreateDonationFeePdaCpiCall {
        accounts,
        bonding_curve_bump,
        pool_authority_bump,
        pool_bump,
        donation_fee_pda_bump,
        signer_seeds,
        remaining_accounts: &[],
    })
    }

    fn create_donation_fee_pda_with_remaining_accounts<'a>(
        &self,
        call: CreateDonationFeePdaCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()>;

}

#[cfg(feature = "cpi")]
impl<'info> CreateDonationFeePdaCpi<'info> for crate::sdk_core_cpi::Program<crate::PumpFees> {
    fn create_donation_fee_pda_with_remaining_accounts<'a>(
        &self,
        call: CreateDonationFeePdaCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()> {
        let CreateDonationFeePdaCpiCall { accounts, bonding_curve_bump, pool_authority_bump, pool_bump, donation_fee_pda_bump, signer_seeds, remaining_accounts } = call;
        let args = CreateDonationFeePdaCpiIxArgs {
            bonding_curve_bump,
            pool_authority_bump,
            pool_bump,
            donation_fee_pda_bump,
        };
        let mut ix_data = crate::sdk_core_cpi::Vec::new();
        ix_data.extend_from_slice(&[244, 139, 16, 88, 14, 255, 122, 26]);
        #[cfg(not(feature = "borsh"))]
        {
        ix_data.extend_from_slice(crate::sdk_core_cpi::bytemuck::bytes_of(&args));
        }
        #[cfg(feature = "borsh")]
        {
            crate::sdk_core_cpi::borsh::BorshSerialize::serialize(&args, &mut ix_data).unwrap();
        }
        #[cfg(feature = "pinocchio")]
        {
            let mut metas_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount>::uninit() }; 32];
            let mut idx = 0;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable_signer(accounts.payer.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.system_program.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.fee_program_global.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.base_mint.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.bonding_curve.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.pool_authority.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.pool.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.sharing_config.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.config_id.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(accounts.donation_fee_pda.info.view.address()));
            idx += 1;
            for (acc, is_writable, is_signer) in remaining_accounts {
                if idx >= 32 { break; }
                let meta = if *is_writable {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(acc.view.address())
                    }
                } else {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(acc.view.address())
                    }
                };
                metas_arr[idx].write(meta);
                idx += 1;
            }
            let account_metas = unsafe { core::slice::from_raw_parts(metas_arr.as_ptr() as *const crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount, idx) };
            let program_id_address = self.address();
            let instruction = crate::sdk_core_cpi::pinocchio::instruction::InstructionView {
                program_id: program_id_address.as_address(),
                accounts: account_metas,
                data: &ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.payer));
            h_idx += 1;
            handles_arr[h_idx].write(accounts.system_program);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.fee_program_global);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.base_mint);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.bonding_curve);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.pool_authority);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.pool);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.sharing_config);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.config_id);
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.donation_fee_pda));
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed_pinocchio_handles(&instruction, account_handles, signer_seeds)
        }
        #[cfg(not(feature = "pinocchio"))]
        {
            use crate::sdk_core_cpi::ToAddress;
            let mut account_metas = crate::sdk_core_cpi::vec![
                ::naclac_lang::solana_program::instruction::AccountMeta::new(accounts.payer.address(), true),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.system_program.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.fee_program_global.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.base_mint.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.bonding_curve.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.pool_authority.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.pool.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.sharing_config.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.config_id.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new(accounts.donation_fee_pda.address(), false),
            ];
            for (acc, is_writable, is_signer) in remaining_accounts {
                let meta = if *is_writable {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new(acc.address(), *is_signer)
                } else {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(acc.address(), *is_signer)
                };
                account_metas.push(meta);
            }
            let instruction = ::naclac_lang::solana_program::instruction::Instruction {
                program_id: self.address(),
                accounts: account_metas,
                data: ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.payer));
            h_idx += 1;
            handles_arr[h_idx].write(accounts.system_program);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.fee_program_global);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.base_mint);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.bonding_curve);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.pool_authority);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.pool);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.sharing_config);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.config_id);
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.donation_fee_pda));
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed(&instruction, account_handles, signer_seeds)
        }
    }
}

