// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
#[cfg(feature = "borsh")]
use crate::sdk_core_offchain::borsh::BorshSerialize;
#[cfg(feature = "offchain")]
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_offchain::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Copy, Clone, Debug))]
#[cfg_attr(not(feature = "borsh"), repr(C, packed))]
pub struct GetFeesIxArgs {
    pub is_pump_pool: crate::sdk_core_offchain::Bool,
    pub market_cap_lamports: u128,
    pub trade_size_lamports: u64,
    pub is_new_quote_mint: crate::sdk_core_offchain::Bool,
}

#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Zeroable for GetFeesIxArgs {}
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Pod for GetFeesIxArgs {}

#[cfg(feature = "cpi")]
#[cfg(feature = "borsh")]
use crate::sdk_core_cpi::borsh::BorshSerialize;
#[cfg(feature = "cpi")]
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_cpi::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Copy, Clone, Debug))]
#[cfg_attr(not(feature = "borsh"), repr(C, packed))]
pub struct GetFeesCpiIxArgs {
    pub is_pump_pool: crate::sdk_core_cpi::Bool,
    pub market_cap_lamports: u128,
    pub trade_size_lamports: u64,
    pub is_new_quote_mint: crate::sdk_core_cpi::Bool,
}

#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Zeroable for GetFeesCpiIxArgs {}
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Pod for GetFeesCpiIxArgs {}

#[cfg(feature = "offchain")]
/// Get Fees
pub struct GetFeesAccounts {
    /// SAFETY: only used as PDA seed material for `fee_config` below; never
    /// deserialized, invoked, or otherwise trusted for its own contents.
    pub config_program_id: naclac_client::Address,
    pub fee_config: naclac_client::Address,
    /// SAFETY: `signer` + the `seeds`/`seeds::program` constraint together
    /// prove this call was CPI'd (via `invoke_signed`) by `pump` itself —
    /// only that program can ever produce a valid signature for its own
    /// `PUMP_AUTHORITY_SEED` PDA. This is the entire authorization model
    /// for this instruction; never deserialized.
    pub pump_authority: naclac_client::Address,
}

#[cfg(feature = "offchain")]
/// Get Fees
pub fn build_get_fees<'a>(
    provider: &'a naclac_client::NaclacProvider,
    program_id: naclac_client::Address,
    is_pump_pool: crate::sdk_core_offchain::Bool,
    market_cap_lamports: u128,
    trade_size_lamports: u64,
    is_new_quote_mint: crate::sdk_core_offchain::Bool,
    accounts: GetFeesAccounts,
) -> naclac_client::InstructionBuilder<'a> {
    let mut ix_data = crate::sdk_core_offchain::vec![231, 37, 126, 85, 207, 91, 63, 52];
    let args = GetFeesIxArgs {
        is_pump_pool,
        market_cap_lamports,
        trade_size_lamports,
        is_new_quote_mint,
    };
    #[cfg(not(feature = "borsh"))]
    {
        ix_data.extend_from_slice(crate::sdk_core_offchain::bytemuck::bytes_of(&args));
    }
    #[cfg(feature = "borsh")]
    {
        crate::sdk_core_offchain::borsh::BorshSerialize::serialize(&args, &mut ix_data).unwrap();
    }
    naclac_client::InstructionBuilder::new(provider, program_id, ix_data)
        .account(naclac_client::AccountMeta { address: accounts.config_program_id, is_signer: false, is_writable: false }, "config_program_id")
        .account(naclac_client::AccountMeta { address: accounts.fee_config, is_signer: false, is_writable: false }, "fee_config")
        .account(naclac_client::AccountMeta { address: accounts.pump_authority, is_signer: true, is_writable: false }, "pump_authority")
}

#[cfg(feature = "cpi")]
/// Get Fees
pub struct GetFeesCpiAccounts<'a> {
    /// SAFETY: only used as PDA seed material for `fee_config` below; never
    /// deserialized, invoked, or otherwise trusted for its own contents.
    pub config_program_id: crate::sdk_core_cpi::CpiHandle<'a>,
    pub fee_config: crate::sdk_core_cpi::CpiHandle<'a>,
    /// SAFETY: `signer` + the `seeds`/`seeds::program` constraint together
    /// prove this call was CPI'd (via `invoke_signed`) by `pump` itself —
    /// only that program can ever produce a valid signature for its own
    /// `PUMP_AUTHORITY_SEED` PDA. This is the entire authorization model
    /// for this instruction; never deserialized.
    pub pump_authority: crate::sdk_core_cpi::CpiHandle<'a>,
}

#[cfg(feature = "cpi")]
pub struct GetFeesCpiCall<'a> {
    pub accounts: GetFeesCpiAccounts<'a>,
    pub is_pump_pool: crate::sdk_core_cpi::Bool,
    pub market_cap_lamports: u128,
    pub trade_size_lamports: u64,
    pub is_new_quote_mint: crate::sdk_core_cpi::Bool,
    pub signer_seeds: &'a [&'a [&'a [u8]]],
    pub remaining_accounts: &'a [(crate::sdk_core_cpi::AccountInfo, bool, bool)],
}

#[cfg(feature = "cpi")]
pub trait GetFeesCpi<'info> {
    /// Get Fees
    fn get_fees<'a>(
        &self,
        accounts: GetFeesCpiAccounts<'a>,
        is_pump_pool: crate::sdk_core_cpi::Bool,
        market_cap_lamports: u128,
        trade_size_lamports: u64,
        is_new_quote_mint: crate::sdk_core_cpi::Bool
    ) -> crate::sdk_core_cpi::Result<()> {
        self.get_fees_with_remaining_accounts(GetFeesCpiCall {
        accounts,
        is_pump_pool,
        market_cap_lamports,
        trade_size_lamports,
        is_new_quote_mint,
        signer_seeds: &[],
        remaining_accounts: &[],
    })
    }

    fn get_fees_signed<'a>(
        &self,
        accounts: GetFeesCpiAccounts<'a>,
        is_pump_pool: crate::sdk_core_cpi::Bool,
        market_cap_lamports: u128,
        trade_size_lamports: u64,
        is_new_quote_mint: crate::sdk_core_cpi::Bool,
        signer_seeds: &[&[&[u8]]]
    ) -> crate::sdk_core_cpi::Result<()> {
        self.get_fees_with_remaining_accounts(GetFeesCpiCall {
        accounts,
        is_pump_pool,
        market_cap_lamports,
        trade_size_lamports,
        is_new_quote_mint,
        signer_seeds,
        remaining_accounts: &[],
    })
    }

    fn get_fees_with_remaining_accounts<'a>(
        &self,
        call: GetFeesCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()>;

}

#[cfg(feature = "cpi")]
impl<'info> GetFeesCpi<'info> for crate::sdk_core_cpi::Program<crate::PumpFees> {
    fn get_fees_with_remaining_accounts<'a>(
        &self,
        call: GetFeesCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()> {
        let GetFeesCpiCall { accounts, is_pump_pool, market_cap_lamports, trade_size_lamports, is_new_quote_mint, signer_seeds, remaining_accounts } = call;
        let args = GetFeesCpiIxArgs {
            is_pump_pool,
            market_cap_lamports,
            trade_size_lamports,
            is_new_quote_mint,
        };
        let mut ix_data = crate::sdk_core_cpi::Vec::new();
        ix_data.extend_from_slice(&[231, 37, 126, 85, 207, 91, 63, 52]);
        #[cfg(not(feature = "borsh"))]
        {
        ix_data.extend_from_slice(crate::sdk_core_cpi::bytemuck::bytes_of(&args));
        }
        #[cfg(feature = "borsh")]
        {
            crate::sdk_core_cpi::borsh::BorshSerialize::serialize(&args, &mut ix_data).unwrap();
        }
        #[cfg(feature = "pinocchio")]
        {
            let mut metas_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount>::uninit() }; 32];
            let mut idx = 0;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.config_program_id.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.fee_config.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly_signer(accounts.pump_authority.info.view.address()));
            idx += 1;
            for (acc, is_writable, is_signer) in remaining_accounts {
                if idx >= 32 { break; }
                let meta = if *is_writable {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(acc.view.address())
                    }
                } else {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(acc.view.address())
                    }
                };
                metas_arr[idx].write(meta);
                idx += 1;
            }
            let account_metas = unsafe { core::slice::from_raw_parts(metas_arr.as_ptr() as *const crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount, idx) };
            let program_id_address = self.address();
            let instruction = crate::sdk_core_cpi::pinocchio::instruction::InstructionView {
                program_id: program_id_address.as_address(),
                accounts: account_metas,
                data: &ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(accounts.config_program_id);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.fee_config);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.pump_authority);
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed_pinocchio_handles(&instruction, account_handles, signer_seeds)
        }
        #[cfg(not(feature = "pinocchio"))]
        {
            use crate::sdk_core_cpi::ToAddress;
            let mut account_metas = crate::sdk_core_cpi::vec![
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.config_program_id.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.fee_config.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.pump_authority.address(), true),
            ];
            for (acc, is_writable, is_signer) in remaining_accounts {
                let meta = if *is_writable {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new(acc.address(), *is_signer)
                } else {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(acc.address(), *is_signer)
                };
                account_metas.push(meta);
            }
            let instruction = ::naclac_lang::solana_program::instruction::Instruction {
                program_id: self.address(),
                accounts: account_metas,
                data: ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(accounts.config_program_id);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.fee_config);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.pump_authority);
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed(&instruction, account_handles, signer_seeds)
        }
    }
}

