// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
#[cfg(feature = "borsh")]
use crate::sdk_core_offchain::borsh::BorshSerialize;
#[cfg(feature = "offchain")]
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_offchain::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Copy, Clone, Debug))]
#[cfg_attr(not(feature = "borsh"), repr(C, packed))]
pub struct UpdateBuybackAuthorityIxArgs {
    pub index: u8,
    pub buyback_vault_bump: u8,
    pub new_authority: crate::sdk_core_offchain::Address,
}

#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Zeroable for UpdateBuybackAuthorityIxArgs {}
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Pod for UpdateBuybackAuthorityIxArgs {}

#[cfg(feature = "cpi")]
#[cfg(feature = "borsh")]
use crate::sdk_core_cpi::borsh::BorshSerialize;
#[cfg(feature = "cpi")]
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_cpi::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Copy, Clone, Debug))]
#[cfg_attr(not(feature = "borsh"), repr(C, packed))]
pub struct UpdateBuybackAuthorityCpiIxArgs {
    pub index: u8,
    pub buyback_vault_bump: u8,
    pub new_authority: crate::sdk_core_cpi::Address,
}

#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Zeroable for UpdateBuybackAuthorityCpiIxArgs {}
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Pod for UpdateBuybackAuthorityCpiIxArgs {}

#[cfg(feature = "offchain")]
/// Gated by the *global* `fee_program_global.authority`, not the vault's own
/// `authority` — an intentional admin-override design (fees-05).
pub struct UpdateBuybackAuthorityAccounts {
    pub authority: naclac_client::Address,
    pub fee_program_global: naclac_client::Address,
    pub buyback_vault: naclac_client::Address,
}

#[cfg(feature = "offchain")]
/// Gated by the *global* `fee_program_global.authority`, not the vault's own
/// `authority` — an intentional admin-override design (fees-05).
pub fn build_update_buyback_authority<'a>(
    provider: &'a naclac_client::NaclacProvider,
    program_id: naclac_client::Address,
    index: u8,
    buyback_vault_bump: u8,
    new_authority: crate::sdk_core_offchain::Address,
    accounts: UpdateBuybackAuthorityAccounts,
) -> naclac_client::InstructionBuilder<'a> {
    let mut ix_data = crate::sdk_core_offchain::vec![66, 98, 113, 202, 121, 37, 219, 107];
    let args = UpdateBuybackAuthorityIxArgs {
        index,
        buyback_vault_bump,
        new_authority,
    };
    #[cfg(not(feature = "borsh"))]
    {
        ix_data.extend_from_slice(crate::sdk_core_offchain::bytemuck::bytes_of(&args));
    }
    #[cfg(feature = "borsh")]
    {
        crate::sdk_core_offchain::borsh::BorshSerialize::serialize(&args, &mut ix_data).unwrap();
    }
    naclac_client::InstructionBuilder::new(provider, program_id, ix_data)
        .account(naclac_client::AccountMeta { address: accounts.authority, is_signer: true, is_writable: true }, "authority")
        .account(naclac_client::AccountMeta { address: accounts.fee_program_global, is_signer: false, is_writable: true }, "fee_program_global")
        .account(naclac_client::AccountMeta { address: accounts.buyback_vault, is_signer: false, is_writable: true }, "buyback_vault")
}

#[cfg(feature = "cpi")]
/// Gated by the *global* `fee_program_global.authority`, not the vault's own
/// `authority` — an intentional admin-override design (fees-05).
pub struct UpdateBuybackAuthorityCpiAccounts<'a> {
    pub authority: crate::sdk_core_cpi::CpiHandleMut<'a>,
    pub fee_program_global: crate::sdk_core_cpi::CpiHandleMut<'a>,
    pub buyback_vault: crate::sdk_core_cpi::CpiHandleMut<'a>,
}

#[cfg(feature = "cpi")]
pub struct UpdateBuybackAuthorityCpiCall<'a> {
    pub accounts: UpdateBuybackAuthorityCpiAccounts<'a>,
    pub index: u8,
    pub buyback_vault_bump: u8,
    pub new_authority: crate::sdk_core_cpi::Address,
    pub signer_seeds: &'a [&'a [&'a [u8]]],
    pub remaining_accounts: &'a [(crate::sdk_core_cpi::AccountInfo, bool, bool)],
}

#[cfg(feature = "cpi")]
pub trait UpdateBuybackAuthorityCpi<'info> {
    /// Gated by the *global* `fee_program_global.authority`, not the vault's own
    /// `authority` — an intentional admin-override design (fees-05).
    fn update_buyback_authority<'a>(
        &self,
        accounts: UpdateBuybackAuthorityCpiAccounts<'a>,
        index: u8,
        buyback_vault_bump: u8,
        new_authority: crate::sdk_core_cpi::Address
    ) -> crate::sdk_core_cpi::Result<()> {
        self.update_buyback_authority_with_remaining_accounts(UpdateBuybackAuthorityCpiCall {
        accounts,
        index,
        buyback_vault_bump,
        new_authority,
        signer_seeds: &[],
        remaining_accounts: &[],
    })
    }

    fn update_buyback_authority_signed<'a>(
        &self,
        accounts: UpdateBuybackAuthorityCpiAccounts<'a>,
        index: u8,
        buyback_vault_bump: u8,
        new_authority: crate::sdk_core_cpi::Address,
        signer_seeds: &[&[&[u8]]]
    ) -> crate::sdk_core_cpi::Result<()> {
        self.update_buyback_authority_with_remaining_accounts(UpdateBuybackAuthorityCpiCall {
        accounts,
        index,
        buyback_vault_bump,
        new_authority,
        signer_seeds,
        remaining_accounts: &[],
    })
    }

    fn update_buyback_authority_with_remaining_accounts<'a>(
        &self,
        call: UpdateBuybackAuthorityCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()>;

}

#[cfg(feature = "cpi")]
impl<'info> UpdateBuybackAuthorityCpi<'info> for crate::sdk_core_cpi::Program<crate::PumpFees> {
    fn update_buyback_authority_with_remaining_accounts<'a>(
        &self,
        call: UpdateBuybackAuthorityCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()> {
        let UpdateBuybackAuthorityCpiCall { accounts, index, buyback_vault_bump, new_authority, signer_seeds, remaining_accounts } = call;
        let args = UpdateBuybackAuthorityCpiIxArgs {
            index,
            buyback_vault_bump,
            new_authority,
        };
        let mut ix_data = crate::sdk_core_cpi::Vec::new();
        ix_data.extend_from_slice(&[66, 98, 113, 202, 121, 37, 219, 107]);
        #[cfg(not(feature = "borsh"))]
        {
        ix_data.extend_from_slice(crate::sdk_core_cpi::bytemuck::bytes_of(&args));
        }
        #[cfg(feature = "borsh")]
        {
            crate::sdk_core_cpi::borsh::BorshSerialize::serialize(&args, &mut ix_data).unwrap();
        }
        #[cfg(feature = "pinocchio")]
        {
            let mut metas_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount>::uninit() }; 32];
            let mut idx = 0;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable_signer(accounts.authority.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(accounts.fee_program_global.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(accounts.buyback_vault.info.view.address()));
            idx += 1;
            for (acc, is_writable, is_signer) in remaining_accounts {
                if idx >= 32 { break; }
                let meta = if *is_writable {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(acc.view.address())
                    }
                } else {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(acc.view.address())
                    }
                };
                metas_arr[idx].write(meta);
                idx += 1;
            }
            let account_metas = unsafe { core::slice::from_raw_parts(metas_arr.as_ptr() as *const crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount, idx) };
            let program_id_address = self.address();
            let instruction = crate::sdk_core_cpi::pinocchio::instruction::InstructionView {
                program_id: program_id_address.as_address(),
                accounts: account_metas,
                data: &ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.authority));
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.fee_program_global));
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.buyback_vault));
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed_pinocchio_handles(&instruction, account_handles, signer_seeds)
        }
        #[cfg(not(feature = "pinocchio"))]
        {
            use crate::sdk_core_cpi::ToAddress;
            let mut account_metas = crate::sdk_core_cpi::vec![
                ::naclac_lang::solana_program::instruction::AccountMeta::new(accounts.authority.address(), true),
                ::naclac_lang::solana_program::instruction::AccountMeta::new(accounts.fee_program_global.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new(accounts.buyback_vault.address(), false),
            ];
            for (acc, is_writable, is_signer) in remaining_accounts {
                let meta = if *is_writable {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new(acc.address(), *is_signer)
                } else {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(acc.address(), *is_signer)
                };
                account_metas.push(meta);
            }
            let instruction = ::naclac_lang::solana_program::instruction::Instruction {
                program_id: self.address(),
                accounts: account_metas,
                data: ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.authority));
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.fee_program_global));
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.buyback_vault));
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed(&instruction, account_handles, signer_seeds)
        }
    }
}

