// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
/// Update admin (only callable by admin)
pub struct UpdateAdminAccounts {
    pub admin: naclac_client::Address,
    /// SAFETY: only used as PDA seed material for `fee_config`; not
    /// deserialized or invoked.
    pub config_program_id: naclac_client::Address,
    pub fee_config: naclac_client::Address,
    /// SAFETY: new admin is passed as an account (not instruction data);
    /// its pubkey is only stored, never deserialized or invoked.
    pub new_admin: naclac_client::Address,
}

#[cfg(feature = "offchain")]
/// Update admin (only callable by admin)
pub fn build_update_admin<'a>(
    provider: &'a naclac_client::NaclacProvider,
    program_id: naclac_client::Address,
    accounts: UpdateAdminAccounts,
) -> naclac_client::InstructionBuilder<'a> {
    let ix_data = crate::sdk_core_offchain::vec![161, 176, 40, 213, 60, 184, 179, 228];
    naclac_client::InstructionBuilder::new(provider, program_id, ix_data)
        .account(naclac_client::AccountMeta { address: accounts.admin, is_signer: true, is_writable: false }, "admin")
        .account(naclac_client::AccountMeta { address: accounts.config_program_id, is_signer: false, is_writable: false }, "config_program_id")
        .account(naclac_client::AccountMeta { address: accounts.fee_config, is_signer: false, is_writable: true }, "fee_config")
        .account(naclac_client::AccountMeta { address: accounts.new_admin, is_signer: false, is_writable: false }, "new_admin")
}

#[cfg(feature = "cpi")]
/// Update admin (only callable by admin)
pub struct UpdateAdminCpiAccounts<'a> {
    pub admin: crate::sdk_core_cpi::CpiHandle<'a>,
    /// SAFETY: only used as PDA seed material for `fee_config`; not
    /// deserialized or invoked.
    pub config_program_id: crate::sdk_core_cpi::CpiHandle<'a>,
    pub fee_config: crate::sdk_core_cpi::CpiHandleMut<'a>,
    /// SAFETY: new admin is passed as an account (not instruction data);
    /// its pubkey is only stored, never deserialized or invoked.
    pub new_admin: crate::sdk_core_cpi::CpiHandle<'a>,
}

#[cfg(feature = "cpi")]
pub struct UpdateAdminCpiCall<'a> {
    pub accounts: UpdateAdminCpiAccounts<'a>,
    pub signer_seeds: &'a [&'a [&'a [u8]]],
    pub remaining_accounts: &'a [(crate::sdk_core_cpi::AccountInfo, bool, bool)],
}

#[cfg(feature = "cpi")]
pub trait UpdateAdminCpi<'info> {
    /// Update admin (only callable by admin)
    fn update_admin<'a>(
        &self,
        accounts: UpdateAdminCpiAccounts<'a>
    ) -> crate::sdk_core_cpi::Result<()> {
        self.update_admin_with_remaining_accounts(UpdateAdminCpiCall {
        accounts,
        signer_seeds: &[],
        remaining_accounts: &[],
    })
    }

    fn update_admin_signed<'a>(
        &self,
        accounts: UpdateAdminCpiAccounts<'a>,
        signer_seeds: &[&[&[u8]]]
    ) -> crate::sdk_core_cpi::Result<()> {
        self.update_admin_with_remaining_accounts(UpdateAdminCpiCall {
        accounts,
        signer_seeds,
        remaining_accounts: &[],
    })
    }

    fn update_admin_with_remaining_accounts<'a>(
        &self,
        call: UpdateAdminCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()>;

}

#[cfg(feature = "cpi")]
impl<'info> UpdateAdminCpi<'info> for crate::sdk_core_cpi::Program<crate::PumpFees> {
    fn update_admin_with_remaining_accounts<'a>(
        &self,
        call: UpdateAdminCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()> {
        let UpdateAdminCpiCall { accounts, signer_seeds, remaining_accounts } = call;
        let mut ix_data = crate::sdk_core_cpi::Vec::new();
        ix_data.extend_from_slice(&[161, 176, 40, 213, 60, 184, 179, 228]);
        #[cfg(feature = "pinocchio")]
        {
            let mut metas_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount>::uninit() }; 32];
            let mut idx = 0;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly_signer(accounts.admin.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.config_program_id.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(accounts.fee_config.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.new_admin.info.view.address()));
            idx += 1;
            for (acc, is_writable, is_signer) in remaining_accounts {
                if idx >= 32 { break; }
                let meta = if *is_writable {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(acc.view.address())
                    }
                } else {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(acc.view.address())
                    }
                };
                metas_arr[idx].write(meta);
                idx += 1;
            }
            let account_metas = unsafe { core::slice::from_raw_parts(metas_arr.as_ptr() as *const crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount, idx) };
            let program_id_address = self.address();
            let instruction = crate::sdk_core_cpi::pinocchio::instruction::InstructionView {
                program_id: program_id_address.as_address(),
                accounts: account_metas,
                data: &ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(accounts.admin);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.config_program_id);
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.fee_config));
            h_idx += 1;
            handles_arr[h_idx].write(accounts.new_admin);
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed_pinocchio_handles(&instruction, account_handles, signer_seeds)
        }
        #[cfg(not(feature = "pinocchio"))]
        {
            use crate::sdk_core_cpi::ToAddress;
            let mut account_metas = crate::sdk_core_cpi::vec![
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.admin.address(), true),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.config_program_id.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new(accounts.fee_config.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.new_admin.address(), false),
            ];
            for (acc, is_writable, is_signer) in remaining_accounts {
                let meta = if *is_writable {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new(acc.address(), *is_signer)
                } else {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(acc.address(), *is_signer)
                };
                account_metas.push(meta);
            }
            let instruction = ::naclac_lang::solana_program::instruction::Instruction {
                program_id: self.address(),
                accounts: account_metas,
                data: ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(accounts.admin);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.config_program_id);
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.fee_config));
            h_idx += 1;
            handles_arr[h_idx].write(accounts.new_admin);
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed(&instruction, account_handles, signer_seeds)
        }
    }
}

