// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
pub const PROGRAM_ID: naclac_client::Address = naclac_client::Address::new_from_array([
    37, 106, 205, 54, 221, 134, 227, 5, 142, 160, 248, 7, 24, 150, 182, 188, 246, 250, 36, 22, 39, 46, 72, 227, 63, 138, 181, 185, 1, 235, 249, 219
]);

#[cfg(not(feature = "offchain"))]
pub const PROGRAM_ID: crate::sdk_core::Address = crate::sdk_core::Address::new_from_array([
    37, 106, 205, 54, 221, 134, 227, 5, 142, 160, 248, 7, 24, 150, 182, 188, 246, 250, 36, 22, 39, 46, 72, 227, 63, 138, 181, 185, 1, 235, 249, 219
]);

pub const SEED_VAULT: &[u8] = &[118, 97, 117, 108, 116];
pub const SEED_USER_ACCOUNT: &[u8] = &[117, 115, 101, 114];
