// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(all(feature = "borsh", feature = "offchain"))]
use crate::sdk_core_offchain::borsh::{BorshDeserialize, BorshSerialize};
#[cfg(all(feature = "borsh", not(feature = "offchain")))]
use crate::sdk_core_cpi::borsh::{BorshDeserialize, BorshSerialize};

#[cfg(feature = "offchain")]
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize, BorshDeserialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_offchain::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Clone, Debug))]
pub struct CheckInterestBearingMintArgs {
    pub expected_rate_authority: Option<crate::sdk_core_offchain::Address>,
    pub expected_current_rate: i16,
}

#[cfg(feature = "cpi")]
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize, BorshDeserialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_cpi::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Clone, Debug))]
pub struct CheckInterestBearingMintArgsCpi {
    pub expected_rate_authority: Option<crate::sdk_core_cpi::Address>,
    pub expected_current_rate: i16,
}

#[cfg(feature = "offchain")]
#[cfg(feature = "borsh")]
#[derive(Clone, Debug, BorshSerialize, BorshDeserialize)]
#[borsh(crate = "crate::sdk_core_offchain::borsh")]
pub struct CheckTransferFeeConfigArgs {
    pub expected_withheld_amount: u64,
    pub expected_newer_basis_points: u16,
    pub expected_newer_maximum_fee: u64,
    pub current_epoch: u64,
    pub transfer_amount: u64,
    pub expected_fee: u64,
    pub expected_post_fee_amount: u64,
}

#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
#[derive(Copy, Clone, Debug)]
#[repr(C)]
pub struct CheckTransferFeeConfigArgs {
    pub expected_withheld_amount: u64,
    pub __naclac_padding_0: [u8; __CheckTransferFeeConfigArgs_GAP_0],
    pub expected_newer_basis_points: u16,
    pub __naclac_padding_1: [u8; __CheckTransferFeeConfigArgs_GAP_1],
    pub expected_newer_maximum_fee: u64,
    pub __naclac_padding_2: [u8; __CheckTransferFeeConfigArgs_GAP_2],
    pub current_epoch: u64,
    pub __naclac_padding_3: [u8; __CheckTransferFeeConfigArgs_GAP_3],
    pub transfer_amount: u64,
    pub __naclac_padding_4: [u8; __CheckTransferFeeConfigArgs_GAP_4],
    pub expected_fee: u64,
    pub __naclac_padding_5: [u8; __CheckTransferFeeConfigArgs_GAP_5],
    pub expected_post_fee_amount: u64,
    pub __naclac_padding_6: [u8; __CheckTransferFeeConfigArgs_GAP_6],
}

#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CheckTransferFeeConfigArgs_GAP_0: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>();
    let __align: usize = ::core::mem::align_of::<u16>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CheckTransferFeeConfigArgs_GAP_1: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgs_GAP_0 + ::core::mem::size_of::<u16>();
    let __align: usize = ::core::mem::align_of::<u64>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CheckTransferFeeConfigArgs_GAP_2: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgs_GAP_0 + ::core::mem::size_of::<u16>()
        + __CheckTransferFeeConfigArgs_GAP_1 + ::core::mem::size_of::<u64>();
    let __align: usize = ::core::mem::align_of::<u64>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CheckTransferFeeConfigArgs_GAP_3: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgs_GAP_0 + ::core::mem::size_of::<u16>()
        + __CheckTransferFeeConfigArgs_GAP_1 + ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgs_GAP_2 + ::core::mem::size_of::<u64>();
    let __align: usize = ::core::mem::align_of::<u64>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CheckTransferFeeConfigArgs_GAP_4: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgs_GAP_0 + ::core::mem::size_of::<u16>()
        + __CheckTransferFeeConfigArgs_GAP_1 + ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgs_GAP_2 + ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgs_GAP_3 + ::core::mem::size_of::<u64>();
    let __align: usize = ::core::mem::align_of::<u64>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CheckTransferFeeConfigArgs_GAP_5: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgs_GAP_0 + ::core::mem::size_of::<u16>()
        + __CheckTransferFeeConfigArgs_GAP_1 + ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgs_GAP_2 + ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgs_GAP_3 + ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgs_GAP_4 + ::core::mem::size_of::<u64>();
    let __align: usize = ::core::mem::align_of::<u64>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CheckTransferFeeConfigArgs_GAP_6: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgs_GAP_0 + ::core::mem::size_of::<u16>()
        + __CheckTransferFeeConfigArgs_GAP_1 + ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgs_GAP_2 + ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgs_GAP_3 + ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgs_GAP_4 + ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgs_GAP_5 + ::core::mem::size_of::<u64>();
    let __align: usize = {
        let mut __a = 1usize;
        let __b = ::core::mem::align_of::<u64>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u16>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u64>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u64>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u64>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u64>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u64>();
        if __b > __a {
            __a = __b;
        }
        __a
    };
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
const _: () = {
    assert!(
        ::core::mem::size_of:: < CheckTransferFeeConfigArgs > () ==
        (::core::mem::size_of:: < u64 > () + __CheckTransferFeeConfigArgs_GAP_0 +
        ::core::mem::size_of:: < u16 > () + __CheckTransferFeeConfigArgs_GAP_1 +
        ::core::mem::size_of:: < u64 > () + __CheckTransferFeeConfigArgs_GAP_2 +
        ::core::mem::size_of:: < u64 > () + __CheckTransferFeeConfigArgs_GAP_3 +
        ::core::mem::size_of:: < u64 > () + __CheckTransferFeeConfigArgs_GAP_4 +
        ::core::mem::size_of:: < u64 > () + __CheckTransferFeeConfigArgs_GAP_5 +
        ::core::mem::size_of:: < u64 > () + __CheckTransferFeeConfigArgs_GAP_6),
        "defined_type/#[component]: `CheckTransferFeeConfigArgs`'s auto-computed internal padding doesn't match the real compiler layout — this indicates a bug in naclac's own padding computation (naclac-client-gen's pod_struct_checks.rs / naclac-macros/src/pod_struct_checks.rs), not a field ordering issue for you to fix",
    );
};
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
const _: fn() = || {
    fn assert_impl<T: crate::sdk_core_offchain::bytemuck::Pod>() {}
    assert_impl::<u64>();
    assert_impl::<u16>();
    assert_impl::<u64>();
    assert_impl::<u64>();
    assert_impl::<u64>();
    assert_impl::<u64>();
    assert_impl::<u64>();
};

#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Zeroable for CheckTransferFeeConfigArgs {}
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Pod for CheckTransferFeeConfigArgs {}
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
impl core::default::Default for CheckTransferFeeConfigArgs {
    fn default() -> Self {
        crate::sdk_core_offchain::bytemuck::Zeroable::zeroed()
    }
}

#[cfg(feature = "cpi")]
#[cfg(feature = "borsh")]
#[derive(Clone, Debug, BorshSerialize, BorshDeserialize)]
#[borsh(crate = "crate::sdk_core_cpi::borsh")]
pub struct CheckTransferFeeConfigArgsCpi {
    pub expected_withheld_amount: u64,
    pub expected_newer_basis_points: u16,
    pub expected_newer_maximum_fee: u64,
    pub current_epoch: u64,
    pub transfer_amount: u64,
    pub expected_fee: u64,
    pub expected_post_fee_amount: u64,
}

#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
#[derive(Copy, Clone, Debug)]
#[repr(C)]
pub struct CheckTransferFeeConfigArgsCpi {
    pub expected_withheld_amount: u64,
    pub __naclac_padding_0: [u8; __CheckTransferFeeConfigArgsCpi_GAP_0],
    pub expected_newer_basis_points: u16,
    pub __naclac_padding_1: [u8; __CheckTransferFeeConfigArgsCpi_GAP_1],
    pub expected_newer_maximum_fee: u64,
    pub __naclac_padding_2: [u8; __CheckTransferFeeConfigArgsCpi_GAP_2],
    pub current_epoch: u64,
    pub __naclac_padding_3: [u8; __CheckTransferFeeConfigArgsCpi_GAP_3],
    pub transfer_amount: u64,
    pub __naclac_padding_4: [u8; __CheckTransferFeeConfigArgsCpi_GAP_4],
    pub expected_fee: u64,
    pub __naclac_padding_5: [u8; __CheckTransferFeeConfigArgsCpi_GAP_5],
    pub expected_post_fee_amount: u64,
    pub __naclac_padding_6: [u8; __CheckTransferFeeConfigArgsCpi_GAP_6],
}

#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CheckTransferFeeConfigArgsCpi_GAP_0: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>();
    let __align: usize = ::core::mem::align_of::<u16>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CheckTransferFeeConfigArgsCpi_GAP_1: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgsCpi_GAP_0 + ::core::mem::size_of::<u16>();
    let __align: usize = ::core::mem::align_of::<u64>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CheckTransferFeeConfigArgsCpi_GAP_2: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgsCpi_GAP_0 + ::core::mem::size_of::<u16>()
        + __CheckTransferFeeConfigArgsCpi_GAP_1 + ::core::mem::size_of::<u64>();
    let __align: usize = ::core::mem::align_of::<u64>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CheckTransferFeeConfigArgsCpi_GAP_3: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgsCpi_GAP_0 + ::core::mem::size_of::<u16>()
        + __CheckTransferFeeConfigArgsCpi_GAP_1 + ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgsCpi_GAP_2 + ::core::mem::size_of::<u64>();
    let __align: usize = ::core::mem::align_of::<u64>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CheckTransferFeeConfigArgsCpi_GAP_4: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgsCpi_GAP_0 + ::core::mem::size_of::<u16>()
        + __CheckTransferFeeConfigArgsCpi_GAP_1 + ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgsCpi_GAP_2 + ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgsCpi_GAP_3 + ::core::mem::size_of::<u64>();
    let __align: usize = ::core::mem::align_of::<u64>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CheckTransferFeeConfigArgsCpi_GAP_5: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgsCpi_GAP_0 + ::core::mem::size_of::<u16>()
        + __CheckTransferFeeConfigArgsCpi_GAP_1 + ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgsCpi_GAP_2 + ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgsCpi_GAP_3 + ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgsCpi_GAP_4 + ::core::mem::size_of::<u64>();
    let __align: usize = ::core::mem::align_of::<u64>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CheckTransferFeeConfigArgsCpi_GAP_6: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgsCpi_GAP_0 + ::core::mem::size_of::<u16>()
        + __CheckTransferFeeConfigArgsCpi_GAP_1 + ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgsCpi_GAP_2 + ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgsCpi_GAP_3 + ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgsCpi_GAP_4 + ::core::mem::size_of::<u64>()
        + __CheckTransferFeeConfigArgsCpi_GAP_5 + ::core::mem::size_of::<u64>();
    let __align: usize = {
        let mut __a = 1usize;
        let __b = ::core::mem::align_of::<u64>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u16>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u64>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u64>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u64>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u64>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u64>();
        if __b > __a {
            __a = __b;
        }
        __a
    };
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
const _: () = {
    assert!(
        ::core::mem::size_of:: < CheckTransferFeeConfigArgsCpi > () ==
        (::core::mem::size_of:: < u64 > () + __CheckTransferFeeConfigArgsCpi_GAP_0 +
        ::core::mem::size_of:: < u16 > () + __CheckTransferFeeConfigArgsCpi_GAP_1 +
        ::core::mem::size_of:: < u64 > () + __CheckTransferFeeConfigArgsCpi_GAP_2 +
        ::core::mem::size_of:: < u64 > () + __CheckTransferFeeConfigArgsCpi_GAP_3 +
        ::core::mem::size_of:: < u64 > () + __CheckTransferFeeConfigArgsCpi_GAP_4 +
        ::core::mem::size_of:: < u64 > () + __CheckTransferFeeConfigArgsCpi_GAP_5 +
        ::core::mem::size_of:: < u64 > () + __CheckTransferFeeConfigArgsCpi_GAP_6),
        "defined_type/#[component]: `CheckTransferFeeConfigArgsCpi`'s auto-computed internal padding doesn't match the real compiler layout — this indicates a bug in naclac's own padding computation (naclac-client-gen's pod_struct_checks.rs / naclac-macros/src/pod_struct_checks.rs), not a field ordering issue for you to fix",
    );
};
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
const _: fn() = || {
    fn assert_impl<T: crate::sdk_core_cpi::bytemuck::Pod>() {}
    assert_impl::<u64>();
    assert_impl::<u16>();
    assert_impl::<u64>();
    assert_impl::<u64>();
    assert_impl::<u64>();
    assert_impl::<u64>();
    assert_impl::<u64>();
};

#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Zeroable for CheckTransferFeeConfigArgsCpi {}
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Pod for CheckTransferFeeConfigArgsCpi {}
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
impl core::default::Default for CheckTransferFeeConfigArgsCpi {
    fn default() -> Self {
        crate::sdk_core_cpi::bytemuck::Zeroable::zeroed()
    }
}

#[cfg(feature = "offchain")]
#[cfg(feature = "borsh")]
/// Real end-to-end proof of `initialize_token_group_member`
/// (`naclac-token/src/extensions/token_group.rs`): allocates a second,
/// member mint PDA, points a self-referential `GroupMemberPointer` at
/// itself, initializes the mint, then joins it to an already-initialized
/// `TokenGroup` on `group_mint` (created by
/// `create_mint2022_with_group_pointer_and_group`), signed by the group's
/// own PDA update authority.
#[derive(Clone, Debug, BorshSerialize, BorshDeserialize)]
#[borsh(crate = "crate::sdk_core_offchain::borsh")]
pub struct CreateMint2022WithGroupMemberPointerAndMemberArgs {
    pub member_seed: u64,
    pub member_mint_bump: u8,
    pub decimals: u8,
}

#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
/// Real end-to-end proof of `initialize_token_group_member`
/// (`naclac-token/src/extensions/token_group.rs`): allocates a second,
/// member mint PDA, points a self-referential `GroupMemberPointer` at
/// itself, initializes the mint, then joins it to an already-initialized
/// `TokenGroup` on `group_mint` (created by
/// `create_mint2022_with_group_pointer_and_group`), signed by the group's
/// own PDA update authority.
#[derive(Copy, Clone, Debug)]
#[repr(C)]
pub struct CreateMint2022WithGroupMemberPointerAndMemberArgs {
    pub member_seed: u64,
    pub __naclac_padding_0: [u8; __CreateMint2022WithGroupMemberPointerAndMemberArgs_GAP_0],
    pub member_mint_bump: u8,
    pub __naclac_padding_1: [u8; __CreateMint2022WithGroupMemberPointerAndMemberArgs_GAP_1],
    pub decimals: u8,
    pub __naclac_padding_2: [u8; __CreateMint2022WithGroupMemberPointerAndMemberArgs_GAP_2],
}

#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CreateMint2022WithGroupMemberPointerAndMemberArgs_GAP_0: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>();
    let __align: usize = ::core::mem::align_of::<u8>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CreateMint2022WithGroupMemberPointerAndMemberArgs_GAP_1: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CreateMint2022WithGroupMemberPointerAndMemberArgs_GAP_0
        + ::core::mem::size_of::<u8>();
    let __align: usize = ::core::mem::align_of::<u8>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CreateMint2022WithGroupMemberPointerAndMemberArgs_GAP_2: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CreateMint2022WithGroupMemberPointerAndMemberArgs_GAP_0
        + ::core::mem::size_of::<u8>()
        + __CreateMint2022WithGroupMemberPointerAndMemberArgs_GAP_1
        + ::core::mem::size_of::<u8>();
    let __align: usize = {
        let mut __a = 1usize;
        let __b = ::core::mem::align_of::<u64>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u8>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u8>();
        if __b > __a {
            __a = __b;
        }
        __a
    };
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
const _: () = {
    assert!(
        ::core::mem::size_of:: < CreateMint2022WithGroupMemberPointerAndMemberArgs > ()
        == (::core::mem::size_of:: < u64 > () +
        __CreateMint2022WithGroupMemberPointerAndMemberArgs_GAP_0 +
        ::core::mem::size_of:: < u8 > () +
        __CreateMint2022WithGroupMemberPointerAndMemberArgs_GAP_1 +
        ::core::mem::size_of:: < u8 > () +
        __CreateMint2022WithGroupMemberPointerAndMemberArgs_GAP_2),
        "defined_type/#[component]: `CreateMint2022WithGroupMemberPointerAndMemberArgs`'s auto-computed internal padding doesn't match the real compiler layout — this indicates a bug in naclac's own padding computation (naclac-client-gen's pod_struct_checks.rs / naclac-macros/src/pod_struct_checks.rs), not a field ordering issue for you to fix",
    );
};
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
const _: fn() = || {
    fn assert_impl<T: crate::sdk_core_offchain::bytemuck::Pod>() {}
    assert_impl::<u64>();
    assert_impl::<u8>();
    assert_impl::<u8>();
};

#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Zeroable for CreateMint2022WithGroupMemberPointerAndMemberArgs {}
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Pod for CreateMint2022WithGroupMemberPointerAndMemberArgs {}
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
impl core::default::Default for CreateMint2022WithGroupMemberPointerAndMemberArgs {
    fn default() -> Self {
        crate::sdk_core_offchain::bytemuck::Zeroable::zeroed()
    }
}

#[cfg(feature = "cpi")]
#[cfg(feature = "borsh")]
/// Real end-to-end proof of `initialize_token_group_member`
/// (`naclac-token/src/extensions/token_group.rs`): allocates a second,
/// member mint PDA, points a self-referential `GroupMemberPointer` at
/// itself, initializes the mint, then joins it to an already-initialized
/// `TokenGroup` on `group_mint` (created by
/// `create_mint2022_with_group_pointer_and_group`), signed by the group's
/// own PDA update authority.
#[derive(Clone, Debug, BorshSerialize, BorshDeserialize)]
#[borsh(crate = "crate::sdk_core_cpi::borsh")]
pub struct CreateMint2022WithGroupMemberPointerAndMemberArgsCpi {
    pub member_seed: u64,
    pub member_mint_bump: u8,
    pub decimals: u8,
}

#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
/// Real end-to-end proof of `initialize_token_group_member`
/// (`naclac-token/src/extensions/token_group.rs`): allocates a second,
/// member mint PDA, points a self-referential `GroupMemberPointer` at
/// itself, initializes the mint, then joins it to an already-initialized
/// `TokenGroup` on `group_mint` (created by
/// `create_mint2022_with_group_pointer_and_group`), signed by the group's
/// own PDA update authority.
#[derive(Copy, Clone, Debug)]
#[repr(C)]
pub struct CreateMint2022WithGroupMemberPointerAndMemberArgsCpi {
    pub member_seed: u64,
    pub __naclac_padding_0: [u8; __CreateMint2022WithGroupMemberPointerAndMemberArgsCpi_GAP_0],
    pub member_mint_bump: u8,
    pub __naclac_padding_1: [u8; __CreateMint2022WithGroupMemberPointerAndMemberArgsCpi_GAP_1],
    pub decimals: u8,
    pub __naclac_padding_2: [u8; __CreateMint2022WithGroupMemberPointerAndMemberArgsCpi_GAP_2],
}

#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CreateMint2022WithGroupMemberPointerAndMemberArgsCpi_GAP_0: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>();
    let __align: usize = ::core::mem::align_of::<u8>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CreateMint2022WithGroupMemberPointerAndMemberArgsCpi_GAP_1: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CreateMint2022WithGroupMemberPointerAndMemberArgsCpi_GAP_0
        + ::core::mem::size_of::<u8>();
    let __align: usize = ::core::mem::align_of::<u8>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CreateMint2022WithGroupMemberPointerAndMemberArgsCpi_GAP_2: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CreateMint2022WithGroupMemberPointerAndMemberArgsCpi_GAP_0
        + ::core::mem::size_of::<u8>()
        + __CreateMint2022WithGroupMemberPointerAndMemberArgsCpi_GAP_1
        + ::core::mem::size_of::<u8>();
    let __align: usize = {
        let mut __a = 1usize;
        let __b = ::core::mem::align_of::<u64>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u8>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u8>();
        if __b > __a {
            __a = __b;
        }
        __a
    };
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
const _: () = {
    assert!(
        ::core::mem::size_of:: < CreateMint2022WithGroupMemberPointerAndMemberArgsCpi >
        () == (::core::mem::size_of:: < u64 > () +
        __CreateMint2022WithGroupMemberPointerAndMemberArgsCpi_GAP_0 +
        ::core::mem::size_of:: < u8 > () +
        __CreateMint2022WithGroupMemberPointerAndMemberArgsCpi_GAP_1 +
        ::core::mem::size_of:: < u8 > () +
        __CreateMint2022WithGroupMemberPointerAndMemberArgsCpi_GAP_2),
        "defined_type/#[component]: `CreateMint2022WithGroupMemberPointerAndMemberArgsCpi`'s auto-computed internal padding doesn't match the real compiler layout — this indicates a bug in naclac's own padding computation (naclac-client-gen's pod_struct_checks.rs / naclac-macros/src/pod_struct_checks.rs), not a field ordering issue for you to fix",
    );
};
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
const _: fn() = || {
    fn assert_impl<T: crate::sdk_core_cpi::bytemuck::Pod>() {}
    assert_impl::<u64>();
    assert_impl::<u8>();
    assert_impl::<u8>();
};

#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Zeroable for CreateMint2022WithGroupMemberPointerAndMemberArgsCpi {}
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Pod for CreateMint2022WithGroupMemberPointerAndMemberArgsCpi {}
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
impl core::default::Default for CreateMint2022WithGroupMemberPointerAndMemberArgsCpi {
    fn default() -> Self {
        crate::sdk_core_cpi::bytemuck::Zeroable::zeroed()
    }
}

#[cfg(feature = "offchain")]
#[cfg(feature = "borsh")]
/// Real end-to-end proof of `initialize_token_group`
/// (`naclac-token/src/extensions/token_group.rs`): allocates the mint PDA by
/// hand, points a self-referential `GroupPointer` at the mint itself
/// (mirrors `TokenMetadata`'s own self-referential requirement), initializes
/// the mint, then initializes `TokenGroup` on it. Despite `TokenGroup` being
/// fixed-size, `InitializeGroup`'s own processor still grows the account
/// itself via the same self-reallocating `alloc_and_serialize` mechanism
/// `TokenMetadata::Initialize` uses (verified against
/// `spl-token-2022-11.0.0`'s real `extension::token_group::processor`) — so
/// the account must be created at exactly its `GroupPointer`-only size, not
/// pre-sized for `TokenGroup` too: `InitializeMint2`'s own validation
/// requires the account's length to exactly equal
/// `ExtensionType::try_calculate_account_len` for whatever extensions are
/// present *at that point* (just `GroupPointer`), rejecting any extra
/// pre-allocated headroom as `InvalidAccountData`.
#[derive(Clone, Debug, BorshSerialize, BorshDeserialize)]
#[borsh(crate = "crate::sdk_core_offchain::borsh")]
pub struct CreateMint2022WithGroupPointerAndGroupArgs {
    pub id: u64,
    pub mint_bump: u8,
    pub decimals: u8,
    pub max_size: u64,
}

#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
/// Real end-to-end proof of `initialize_token_group`
/// (`naclac-token/src/extensions/token_group.rs`): allocates the mint PDA by
/// hand, points a self-referential `GroupPointer` at the mint itself
/// (mirrors `TokenMetadata`'s own self-referential requirement), initializes
/// the mint, then initializes `TokenGroup` on it. Despite `TokenGroup` being
/// fixed-size, `InitializeGroup`'s own processor still grows the account
/// itself via the same self-reallocating `alloc_and_serialize` mechanism
/// `TokenMetadata::Initialize` uses (verified against
/// `spl-token-2022-11.0.0`'s real `extension::token_group::processor`) — so
/// the account must be created at exactly its `GroupPointer`-only size, not
/// pre-sized for `TokenGroup` too: `InitializeMint2`'s own validation
/// requires the account's length to exactly equal
/// `ExtensionType::try_calculate_account_len` for whatever extensions are
/// present *at that point* (just `GroupPointer`), rejecting any extra
/// pre-allocated headroom as `InvalidAccountData`.
#[derive(Copy, Clone, Debug)]
#[repr(C)]
pub struct CreateMint2022WithGroupPointerAndGroupArgs {
    pub id: u64,
    pub __naclac_padding_0: [u8; __CreateMint2022WithGroupPointerAndGroupArgs_GAP_0],
    pub mint_bump: u8,
    pub __naclac_padding_1: [u8; __CreateMint2022WithGroupPointerAndGroupArgs_GAP_1],
    pub decimals: u8,
    pub __naclac_padding_2: [u8; __CreateMint2022WithGroupPointerAndGroupArgs_GAP_2],
    pub max_size: u64,
    pub __naclac_padding_3: [u8; __CreateMint2022WithGroupPointerAndGroupArgs_GAP_3],
}

#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CreateMint2022WithGroupPointerAndGroupArgs_GAP_0: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>();
    let __align: usize = ::core::mem::align_of::<u8>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CreateMint2022WithGroupPointerAndGroupArgs_GAP_1: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CreateMint2022WithGroupPointerAndGroupArgs_GAP_0
        + ::core::mem::size_of::<u8>();
    let __align: usize = ::core::mem::align_of::<u8>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CreateMint2022WithGroupPointerAndGroupArgs_GAP_2: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CreateMint2022WithGroupPointerAndGroupArgs_GAP_0
        + ::core::mem::size_of::<u8>()
        + __CreateMint2022WithGroupPointerAndGroupArgs_GAP_1
        + ::core::mem::size_of::<u8>();
    let __align: usize = ::core::mem::align_of::<u64>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CreateMint2022WithGroupPointerAndGroupArgs_GAP_3: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CreateMint2022WithGroupPointerAndGroupArgs_GAP_0
        + ::core::mem::size_of::<u8>()
        + __CreateMint2022WithGroupPointerAndGroupArgs_GAP_1
        + ::core::mem::size_of::<u8>()
        + __CreateMint2022WithGroupPointerAndGroupArgs_GAP_2
        + ::core::mem::size_of::<u64>();
    let __align: usize = {
        let mut __a = 1usize;
        let __b = ::core::mem::align_of::<u64>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u8>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u8>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u64>();
        if __b > __a {
            __a = __b;
        }
        __a
    };
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
const _: () = {
    assert!(
        ::core::mem::size_of:: < CreateMint2022WithGroupPointerAndGroupArgs > () ==
        (::core::mem::size_of:: < u64 > () +
        __CreateMint2022WithGroupPointerAndGroupArgs_GAP_0 + ::core::mem::size_of:: < u8
        > () + __CreateMint2022WithGroupPointerAndGroupArgs_GAP_1 +
        ::core::mem::size_of:: < u8 > () +
        __CreateMint2022WithGroupPointerAndGroupArgs_GAP_2 + ::core::mem::size_of:: < u64
        > () + __CreateMint2022WithGroupPointerAndGroupArgs_GAP_3),
        "defined_type/#[component]: `CreateMint2022WithGroupPointerAndGroupArgs`'s auto-computed internal padding doesn't match the real compiler layout — this indicates a bug in naclac's own padding computation (naclac-client-gen's pod_struct_checks.rs / naclac-macros/src/pod_struct_checks.rs), not a field ordering issue for you to fix",
    );
};
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
const _: fn() = || {
    fn assert_impl<T: crate::sdk_core_offchain::bytemuck::Pod>() {}
    assert_impl::<u64>();
    assert_impl::<u8>();
    assert_impl::<u8>();
    assert_impl::<u64>();
};

#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Zeroable for CreateMint2022WithGroupPointerAndGroupArgs {}
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Pod for CreateMint2022WithGroupPointerAndGroupArgs {}
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
impl core::default::Default for CreateMint2022WithGroupPointerAndGroupArgs {
    fn default() -> Self {
        crate::sdk_core_offchain::bytemuck::Zeroable::zeroed()
    }
}

#[cfg(feature = "cpi")]
#[cfg(feature = "borsh")]
/// Real end-to-end proof of `initialize_token_group`
/// (`naclac-token/src/extensions/token_group.rs`): allocates the mint PDA by
/// hand, points a self-referential `GroupPointer` at the mint itself
/// (mirrors `TokenMetadata`'s own self-referential requirement), initializes
/// the mint, then initializes `TokenGroup` on it. Despite `TokenGroup` being
/// fixed-size, `InitializeGroup`'s own processor still grows the account
/// itself via the same self-reallocating `alloc_and_serialize` mechanism
/// `TokenMetadata::Initialize` uses (verified against
/// `spl-token-2022-11.0.0`'s real `extension::token_group::processor`) — so
/// the account must be created at exactly its `GroupPointer`-only size, not
/// pre-sized for `TokenGroup` too: `InitializeMint2`'s own validation
/// requires the account's length to exactly equal
/// `ExtensionType::try_calculate_account_len` for whatever extensions are
/// present *at that point* (just `GroupPointer`), rejecting any extra
/// pre-allocated headroom as `InvalidAccountData`.
#[derive(Clone, Debug, BorshSerialize, BorshDeserialize)]
#[borsh(crate = "crate::sdk_core_cpi::borsh")]
pub struct CreateMint2022WithGroupPointerAndGroupArgsCpi {
    pub id: u64,
    pub mint_bump: u8,
    pub decimals: u8,
    pub max_size: u64,
}

#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
/// Real end-to-end proof of `initialize_token_group`
/// (`naclac-token/src/extensions/token_group.rs`): allocates the mint PDA by
/// hand, points a self-referential `GroupPointer` at the mint itself
/// (mirrors `TokenMetadata`'s own self-referential requirement), initializes
/// the mint, then initializes `TokenGroup` on it. Despite `TokenGroup` being
/// fixed-size, `InitializeGroup`'s own processor still grows the account
/// itself via the same self-reallocating `alloc_and_serialize` mechanism
/// `TokenMetadata::Initialize` uses (verified against
/// `spl-token-2022-11.0.0`'s real `extension::token_group::processor`) — so
/// the account must be created at exactly its `GroupPointer`-only size, not
/// pre-sized for `TokenGroup` too: `InitializeMint2`'s own validation
/// requires the account's length to exactly equal
/// `ExtensionType::try_calculate_account_len` for whatever extensions are
/// present *at that point* (just `GroupPointer`), rejecting any extra
/// pre-allocated headroom as `InvalidAccountData`.
#[derive(Copy, Clone, Debug)]
#[repr(C)]
pub struct CreateMint2022WithGroupPointerAndGroupArgsCpi {
    pub id: u64,
    pub __naclac_padding_0: [u8; __CreateMint2022WithGroupPointerAndGroupArgsCpi_GAP_0],
    pub mint_bump: u8,
    pub __naclac_padding_1: [u8; __CreateMint2022WithGroupPointerAndGroupArgsCpi_GAP_1],
    pub decimals: u8,
    pub __naclac_padding_2: [u8; __CreateMint2022WithGroupPointerAndGroupArgsCpi_GAP_2],
    pub max_size: u64,
    pub __naclac_padding_3: [u8; __CreateMint2022WithGroupPointerAndGroupArgsCpi_GAP_3],
}

#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CreateMint2022WithGroupPointerAndGroupArgsCpi_GAP_0: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>();
    let __align: usize = ::core::mem::align_of::<u8>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CreateMint2022WithGroupPointerAndGroupArgsCpi_GAP_1: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CreateMint2022WithGroupPointerAndGroupArgsCpi_GAP_0
        + ::core::mem::size_of::<u8>();
    let __align: usize = ::core::mem::align_of::<u8>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CreateMint2022WithGroupPointerAndGroupArgsCpi_GAP_2: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CreateMint2022WithGroupPointerAndGroupArgsCpi_GAP_0
        + ::core::mem::size_of::<u8>()
        + __CreateMint2022WithGroupPointerAndGroupArgsCpi_GAP_1
        + ::core::mem::size_of::<u8>();
    let __align: usize = ::core::mem::align_of::<u64>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CreateMint2022WithGroupPointerAndGroupArgsCpi_GAP_3: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CreateMint2022WithGroupPointerAndGroupArgsCpi_GAP_0
        + ::core::mem::size_of::<u8>()
        + __CreateMint2022WithGroupPointerAndGroupArgsCpi_GAP_1
        + ::core::mem::size_of::<u8>()
        + __CreateMint2022WithGroupPointerAndGroupArgsCpi_GAP_2
        + ::core::mem::size_of::<u64>();
    let __align: usize = {
        let mut __a = 1usize;
        let __b = ::core::mem::align_of::<u64>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u8>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u8>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u64>();
        if __b > __a {
            __a = __b;
        }
        __a
    };
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
const _: () = {
    assert!(
        ::core::mem::size_of:: < CreateMint2022WithGroupPointerAndGroupArgsCpi > () ==
        (::core::mem::size_of:: < u64 > () +
        __CreateMint2022WithGroupPointerAndGroupArgsCpi_GAP_0 + ::core::mem::size_of:: <
        u8 > () + __CreateMint2022WithGroupPointerAndGroupArgsCpi_GAP_1 +
        ::core::mem::size_of:: < u8 > () +
        __CreateMint2022WithGroupPointerAndGroupArgsCpi_GAP_2 + ::core::mem::size_of:: <
        u64 > () + __CreateMint2022WithGroupPointerAndGroupArgsCpi_GAP_3),
        "defined_type/#[component]: `CreateMint2022WithGroupPointerAndGroupArgsCpi`'s auto-computed internal padding doesn't match the real compiler layout — this indicates a bug in naclac's own padding computation (naclac-client-gen's pod_struct_checks.rs / naclac-macros/src/pod_struct_checks.rs), not a field ordering issue for you to fix",
    );
};
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
const _: fn() = || {
    fn assert_impl<T: crate::sdk_core_cpi::bytemuck::Pod>() {}
    assert_impl::<u64>();
    assert_impl::<u8>();
    assert_impl::<u8>();
    assert_impl::<u64>();
};

#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Zeroable for CreateMint2022WithGroupPointerAndGroupArgsCpi {}
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Pod for CreateMint2022WithGroupPointerAndGroupArgsCpi {}
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
impl core::default::Default for CreateMint2022WithGroupPointerAndGroupArgsCpi {
    fn default() -> Self {
        crate::sdk_core_cpi::bytemuck::Zeroable::zeroed()
    }
}

#[cfg(feature = "offchain")]
/// Real end-to-end proof of `initialize_token_metadata`
/// (`naclac-token/src/extensions/token_metadata.rs`): allocates the mint PDA
/// by hand, points a self-referential `MetadataPointer` at the mint itself
/// (required — Token-2022's own `TokenMetadata::Initialize` processor
/// rejects a metadata account that isn't the mint), initializes the mint,
/// then initializes `TokenMetadata` on it. Funds the account well beyond its
/// initial size: `TokenMetadata::Initialize`/`UpdateField` both grow the
/// account via `AccountInfo::resize` directly (no payer/`system_program`
/// account of their own), and `resize` never adds lamports — only pre-funded
/// headroom keeps a later grow rent-exempt.
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize, BorshDeserialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_offchain::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Clone, Debug))]
pub struct CreateMint2022WithMetadataPointerAndMetadataArgs {
    pub id: u64,
    pub mint_bump: u8,
    pub decimals: u8,
    pub name: crate::sdk_core_offchain::String,
    pub symbol: crate::sdk_core_offchain::String,
    pub uri: crate::sdk_core_offchain::String,
}

#[cfg(feature = "cpi")]
/// Real end-to-end proof of `initialize_token_metadata`
/// (`naclac-token/src/extensions/token_metadata.rs`): allocates the mint PDA
/// by hand, points a self-referential `MetadataPointer` at the mint itself
/// (required — Token-2022's own `TokenMetadata::Initialize` processor
/// rejects a metadata account that isn't the mint), initializes the mint,
/// then initializes `TokenMetadata` on it. Funds the account well beyond its
/// initial size: `TokenMetadata::Initialize`/`UpdateField` both grow the
/// account via `AccountInfo::resize` directly (no payer/`system_program`
/// account of their own), and `resize` never adds lamports — only pre-funded
/// headroom keeps a later grow rent-exempt.
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize, BorshDeserialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_cpi::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Clone, Debug))]
pub struct CreateMint2022WithMetadataPointerAndMetadataArgsCpi {
    pub id: u64,
    pub mint_bump: u8,
    pub decimals: u8,
    pub name: crate::sdk_core_cpi::String,
    pub symbol: crate::sdk_core_cpi::String,
    pub uri: crate::sdk_core_cpi::String,
}

#[cfg(feature = "offchain")]
#[cfg(feature = "borsh")]
/// Real end-to-end proof of `initialize_transfer_hook`
/// (`naclac-token/src/extensions/transfer_hook.rs`), under the
/// non-pinocchio backend specifically — needed so
/// `transfer_checked_with_hook` (non-pinocchio only) can be exercised
/// against a real hook-gated mint; `token_borsh` is the only test program
/// in this workspace that compiles under the non-pinocchio backend.
#[derive(Clone, Debug, BorshSerialize, BorshDeserialize)]
#[borsh(crate = "crate::sdk_core_offchain::borsh")]
pub struct CreateMint2022WithTransferHookArgs {
    pub id: u64,
    pub mint_bump: u8,
    pub decimals: u8,
    pub hook_program_id: crate::sdk_core_offchain::Address,
}

#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
/// Real end-to-end proof of `initialize_transfer_hook`
/// (`naclac-token/src/extensions/transfer_hook.rs`), under the
/// non-pinocchio backend specifically — needed so
/// `transfer_checked_with_hook` (non-pinocchio only) can be exercised
/// against a real hook-gated mint; `token_borsh` is the only test program
/// in this workspace that compiles under the non-pinocchio backend.
#[derive(Copy, Clone, Debug)]
#[repr(C)]
pub struct CreateMint2022WithTransferHookArgs {
    pub id: u64,
    pub __naclac_padding_0: [u8; __CreateMint2022WithTransferHookArgs_GAP_0],
    pub mint_bump: u8,
    pub __naclac_padding_1: [u8; __CreateMint2022WithTransferHookArgs_GAP_1],
    pub decimals: u8,
    pub __naclac_padding_2: [u8; __CreateMint2022WithTransferHookArgs_GAP_2],
    pub hook_program_id: crate::sdk_core_offchain::Address,
    pub __naclac_padding_3: [u8; __CreateMint2022WithTransferHookArgs_GAP_3],
}

#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CreateMint2022WithTransferHookArgs_GAP_0: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>();
    let __align: usize = ::core::mem::align_of::<u8>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CreateMint2022WithTransferHookArgs_GAP_1: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CreateMint2022WithTransferHookArgs_GAP_0 + ::core::mem::size_of::<u8>();
    let __align: usize = ::core::mem::align_of::<u8>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CreateMint2022WithTransferHookArgs_GAP_2: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CreateMint2022WithTransferHookArgs_GAP_0 + ::core::mem::size_of::<u8>()
        + __CreateMint2022WithTransferHookArgs_GAP_1 + ::core::mem::size_of::<u8>();
    let __align: usize = ::core::mem::align_of::<crate::sdk_core_offchain::Address>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CreateMint2022WithTransferHookArgs_GAP_3: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CreateMint2022WithTransferHookArgs_GAP_0 + ::core::mem::size_of::<u8>()
        + __CreateMint2022WithTransferHookArgs_GAP_1 + ::core::mem::size_of::<u8>()
        + __CreateMint2022WithTransferHookArgs_GAP_2
        + ::core::mem::size_of::<crate::sdk_core_offchain::Address>();
    let __align: usize = {
        let mut __a = 1usize;
        let __b = ::core::mem::align_of::<u64>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u8>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u8>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<crate::sdk_core_offchain::Address>();
        if __b > __a {
            __a = __b;
        }
        __a
    };
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
const _: () = {
    assert!(
        ::core::mem::size_of:: < CreateMint2022WithTransferHookArgs > () ==
        (::core::mem::size_of:: < u64 > () + __CreateMint2022WithTransferHookArgs_GAP_0 +
        ::core::mem::size_of:: < u8 > () + __CreateMint2022WithTransferHookArgs_GAP_1 +
        ::core::mem::size_of:: < u8 > () + __CreateMint2022WithTransferHookArgs_GAP_2 +
        ::core::mem::size_of:: < crate ::sdk_core_offchain::Address > () +
        __CreateMint2022WithTransferHookArgs_GAP_3),
        "defined_type/#[component]: `CreateMint2022WithTransferHookArgs`'s auto-computed internal padding doesn't match the real compiler layout — this indicates a bug in naclac's own padding computation (naclac-client-gen's pod_struct_checks.rs / naclac-macros/src/pod_struct_checks.rs), not a field ordering issue for you to fix",
    );
};
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
const _: fn() = || {
    fn assert_impl<T: crate::sdk_core_offchain::bytemuck::Pod>() {}
    assert_impl::<u64>();
    assert_impl::<u8>();
    assert_impl::<u8>();
    assert_impl::<crate::sdk_core_offchain::Address>();
};

#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Zeroable for CreateMint2022WithTransferHookArgs {}
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Pod for CreateMint2022WithTransferHookArgs {}
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
impl core::default::Default for CreateMint2022WithTransferHookArgs {
    fn default() -> Self {
        crate::sdk_core_offchain::bytemuck::Zeroable::zeroed()
    }
}

#[cfg(feature = "cpi")]
#[cfg(feature = "borsh")]
/// Real end-to-end proof of `initialize_transfer_hook`
/// (`naclac-token/src/extensions/transfer_hook.rs`), under the
/// non-pinocchio backend specifically — needed so
/// `transfer_checked_with_hook` (non-pinocchio only) can be exercised
/// against a real hook-gated mint; `token_borsh` is the only test program
/// in this workspace that compiles under the non-pinocchio backend.
#[derive(Clone, Debug, BorshSerialize, BorshDeserialize)]
#[borsh(crate = "crate::sdk_core_cpi::borsh")]
pub struct CreateMint2022WithTransferHookArgsCpi {
    pub id: u64,
    pub mint_bump: u8,
    pub decimals: u8,
    pub hook_program_id: crate::sdk_core_cpi::Address,
}

#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
/// Real end-to-end proof of `initialize_transfer_hook`
/// (`naclac-token/src/extensions/transfer_hook.rs`), under the
/// non-pinocchio backend specifically — needed so
/// `transfer_checked_with_hook` (non-pinocchio only) can be exercised
/// against a real hook-gated mint; `token_borsh` is the only test program
/// in this workspace that compiles under the non-pinocchio backend.
#[derive(Copy, Clone, Debug)]
#[repr(C)]
pub struct CreateMint2022WithTransferHookArgsCpi {
    pub id: u64,
    pub __naclac_padding_0: [u8; __CreateMint2022WithTransferHookArgsCpi_GAP_0],
    pub mint_bump: u8,
    pub __naclac_padding_1: [u8; __CreateMint2022WithTransferHookArgsCpi_GAP_1],
    pub decimals: u8,
    pub __naclac_padding_2: [u8; __CreateMint2022WithTransferHookArgsCpi_GAP_2],
    pub hook_program_id: crate::sdk_core_cpi::Address,
    pub __naclac_padding_3: [u8; __CreateMint2022WithTransferHookArgsCpi_GAP_3],
}

#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CreateMint2022WithTransferHookArgsCpi_GAP_0: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>();
    let __align: usize = ::core::mem::align_of::<u8>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CreateMint2022WithTransferHookArgsCpi_GAP_1: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CreateMint2022WithTransferHookArgsCpi_GAP_0 + ::core::mem::size_of::<u8>();
    let __align: usize = ::core::mem::align_of::<u8>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CreateMint2022WithTransferHookArgsCpi_GAP_2: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CreateMint2022WithTransferHookArgsCpi_GAP_0 + ::core::mem::size_of::<u8>()
        + __CreateMint2022WithTransferHookArgsCpi_GAP_1 + ::core::mem::size_of::<u8>();
    let __align: usize = ::core::mem::align_of::<crate::sdk_core_cpi::Address>();
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
#[allow(non_upper_case_globals)]
const __CreateMint2022WithTransferHookArgsCpi_GAP_3: usize = {
    let __offset: usize = ::core::mem::size_of::<u64>()
        + __CreateMint2022WithTransferHookArgsCpi_GAP_0 + ::core::mem::size_of::<u8>()
        + __CreateMint2022WithTransferHookArgsCpi_GAP_1 + ::core::mem::size_of::<u8>()
        + __CreateMint2022WithTransferHookArgsCpi_GAP_2
        + ::core::mem::size_of::<crate::sdk_core_cpi::Address>();
    let __align: usize = {
        let mut __a = 1usize;
        let __b = ::core::mem::align_of::<u64>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u8>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<u8>();
        if __b > __a {
            __a = __b;
        }
        let __b = ::core::mem::align_of::<crate::sdk_core_cpi::Address>();
        if __b > __a {
            __a = __b;
        }
        __a
    };
    let __rem = __offset % __align;
    if __rem == 0 { 0 } else { __align - __rem }
};
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
const _: () = {
    assert!(
        ::core::mem::size_of:: < CreateMint2022WithTransferHookArgsCpi > () ==
        (::core::mem::size_of:: < u64 > () +
        __CreateMint2022WithTransferHookArgsCpi_GAP_0 + ::core::mem::size_of:: < u8 > ()
        + __CreateMint2022WithTransferHookArgsCpi_GAP_1 + ::core::mem::size_of:: < u8 >
        () + __CreateMint2022WithTransferHookArgsCpi_GAP_2 + ::core::mem::size_of:: <
        crate ::sdk_core_cpi::Address > () +
        __CreateMint2022WithTransferHookArgsCpi_GAP_3),
        "defined_type/#[component]: `CreateMint2022WithTransferHookArgsCpi`'s auto-computed internal padding doesn't match the real compiler layout — this indicates a bug in naclac's own padding computation (naclac-client-gen's pod_struct_checks.rs / naclac-macros/src/pod_struct_checks.rs), not a field ordering issue for you to fix",
    );
};
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
const _: fn() = || {
    fn assert_impl<T: crate::sdk_core_cpi::bytemuck::Pod>() {}
    assert_impl::<u64>();
    assert_impl::<u8>();
    assert_impl::<u8>();
    assert_impl::<crate::sdk_core_cpi::Address>();
};

#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Zeroable for CreateMint2022WithTransferHookArgsCpi {}
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Pod for CreateMint2022WithTransferHookArgsCpi {}
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
impl core::default::Default for CreateMint2022WithTransferHookArgsCpi {
    fn default() -> Self {
        crate::sdk_core_cpi::bytemuck::Zeroable::zeroed()
    }
}

