[package]
name = "vault_borsh"
version = "0.1.0"
description = "Created with Naclac Framework"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]
custom-heap = []
custom-panic = []
debug-mode = []
default = ["borsh"]
borsh = ["naclac-lang/borsh"]

[dependencies]
naclac-lang = { version = "0.1.0", path = "../../../../naclac-lang" }

[dev-dependencies]
naclac-client = { version = "0.1.0", path = "../../../../naclac-client" }
vault-borsh-client = { version = "0.1.0", path = "../../clients/rust/vault_borsh", features = ["borsh"] }

[lints]
workspace = true
