// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#![cfg_attr(all(feature = "cpi", feature = "pinocchio"), no_std)]

#[cfg(feature = "cpi")]
pub use naclac_lang::prelude as sdk_core;
#[cfg(all(feature = "offchain", not(feature = "cpi")))]
pub use naclac_client as sdk_core;

#[cfg(feature = "offchain")]
pub mod components;
pub mod instructions;
pub mod types;

#[cfg(feature = "offchain")]
pub use components::*;
pub use instructions::*;
pub use types::*;

#[macro_export]
macro_rules! declare_id {
    ($id:expr) => {};
}

declare_id!("9j8UexsZ6UFq7B8as4vXPLtzVN4XyBsZzqhfvmGpNfCB");

#[cfg(feature = "offchain")]
pub fn get_launch_record_pda(
    program_id: &naclac_client::Address,
    payer: &naclac_client::Address,
    id: u64
) -> (naclac_client::Address, u8) {
    let id_bytes = id.to_le_bytes();
    naclac_client::Address::find_program_address(
        &[
            &[108, 97, 117, 110, 99, 104],
            payer.as_ref(),
            &id_bytes,
        ],
        program_id,
    )
}

#[cfg(feature = "offchain")]
pub fn get_mint_pda(
    program_id: &naclac_client::Address,
    id: u64
) -> (naclac_client::Address, u8) {
    let id_bytes = id.to_le_bytes();
    naclac_client::Address::find_program_address(
        &[
            &[109, 105, 110, 116],
            &id_bytes,
        ],
        program_id,
    )
}

#[cfg(feature = "cpi")]
#[derive(Clone, Copy)]
pub struct TokenCreator;

#[cfg(feature = "cpi")]
impl sdk_core::Id for TokenCreator {
    fn id() -> sdk_core::Address {
        sdk_core::Address::new_from_array([129, 168, 87, 235, 165, 26, 209, 14, 195, 11, 185, 244, 99, 186, 240, 248, 163, 178, 182, 218, 44, 247, 238, 5, 124, 105, 182, 30, 178, 101, 162, 248])
    }
}

