// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
pub const PROGRAM_ID: naclac_client::Address = naclac_client::Address::new_from_array([
    219, 84, 13, 51, 230, 238, 25, 53, 116, 100, 104, 69, 8, 196, 54, 214, 82, 163, 176, 167, 216, 127, 161, 79, 217, 237, 183, 187, 131, 100, 116, 120
]);

#[cfg(feature = "cpi")]
pub const PROGRAM_ID_CPI: crate::sdk_core_cpi::Address = crate::sdk_core_cpi::Address::new_from_array([
    219, 84, 13, 51, 230, 238, 25, 53, 116, 100, 104, 69, 8, 196, 54, 214, 82, 163, 176, 167, 216, 127, 161, 79, 217, 237, 183, 187, 131, 100, 116, 120
]);

