// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
pub const PROGRAM_ID: naclac_client::Address = naclac_client::Address::new_from_array([
    148, 190, 155, 147, 234, 130, 178, 112, 133, 72, 34, 252, 127, 247, 239, 42, 230, 161, 172, 135, 48, 82, 99, 246, 73, 178, 148, 174, 240, 246, 106, 25
]);

#[cfg(feature = "cpi")]
pub const PROGRAM_ID_CPI: crate::sdk_core_cpi::Address = crate::sdk_core_cpi::Address::new_from_array([
    148, 190, 155, 147, 234, 130, 178, 112, 133, 72, 34, 252, 127, 247, 239, 42, 230, 161, 172, 135, 48, 82, 99, 246, 73, 178, 148, 174, 240, 246, 106, 25
]);

pub const SEED_COUNTER: &[u8] = &[99, 111, 117, 110, 116, 101, 114];
pub const SEED_EVENT_AUTHORITY: &[u8] = &[95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121];
