// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
pub const PROGRAM_ID: naclac_client::Address = naclac_client::Address::new_from_array([
    156, 150, 24, 197, 130, 255, 149, 99, 58, 163, 68, 21, 228, 177, 253, 48, 120, 95, 201, 203, 8, 218, 107, 186, 186, 27, 194, 37, 26, 175, 112, 239
]);

#[cfg(feature = "cpi")]
pub const PROGRAM_ID_CPI: crate::sdk_core_cpi::Address = crate::sdk_core_cpi::Address::new_from_array([
    156, 150, 24, 197, 130, 255, 149, 99, 58, 163, 68, 21, 228, 177, 253, 48, 120, 95, 201, 203, 8, 218, 107, 186, 186, 27, 194, 37, 26, 175, 112, 239
]);

pub const SEED_COUNTER: &[u8] = &[99, 111, 117, 110, 116, 101, 114, 95, 118, 50];
