// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
pub const PROGRAM_ID: naclac_client::Address = naclac_client::Address::new_from_array([
    110, 22, 39, 194, 218, 115, 122, 179, 61, 211, 41, 201, 243, 5, 18, 25, 135, 164, 35, 59, 66, 70, 203, 101, 190, 242, 82, 87, 216, 131, 0, 33
]);

#[cfg(not(feature = "offchain"))]
pub const PROGRAM_ID: crate::sdk_core::Address = crate::sdk_core::Address::new_from_array([
    110, 22, 39, 194, 218, 115, 122, 179, 61, 211, 41, 201, 243, 5, 18, 25, 135, 164, 35, 59, 66, 70, 203, 101, 190, 242, 82, 87, 216, 131, 0, 33
]);

pub const SEED_COUNTER: &[u8] = &[99, 111, 117, 110, 116, 101, 114, 95, 118, 50];
