// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
pub const PROGRAM_ID: naclac_client::Address = naclac_client::Address::new_from_array([
    242, 179, 214, 205, 201, 33, 163, 107, 34, 53, 7, 62, 176, 76, 109, 54, 61, 75, 66, 46, 235, 211, 89, 65, 166, 179, 56, 154, 114, 177, 116, 75
]);

#[cfg(not(feature = "offchain"))]
pub const PROGRAM_ID: crate::sdk_core::Address = crate::sdk_core::Address::new_from_array([
    242, 179, 214, 205, 201, 33, 163, 107, 34, 53, 7, 62, 176, 76, 109, 54, 61, 75, 66, 46, 235, 211, 89, 65, 166, 179, 56, 154, 114, 177, 116, 75
]);

