// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
pub const PROGRAM_ID: naclac_client::Address = naclac_client::Address::new_from_array([
    123, 99, 205, 187, 42, 196, 169, 225, 79, 161, 202, 227, 99, 30, 48, 128, 11, 170, 67, 174, 201, 66, 173, 99, 52, 21, 77, 139, 121, 110, 178, 44
]);

#[cfg(feature = "cpi")]
pub const PROGRAM_ID_CPI: crate::sdk_core_cpi::Address = crate::sdk_core_cpi::Address::new_from_array([
    123, 99, 205, 187, 42, 196, 169, 225, 79, 161, 202, 227, 99, 30, 48, 128, 11, 170, 67, 174, 201, 66, 173, 99, 52, 21, 77, 139, 121, 110, 178, 44
]);

