// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
pub const PROGRAM_ID: naclac_client::Address = naclac_client::Address::new_from_array([
    23, 44, 20, 102, 242, 76, 74, 93, 22, 245, 59, 53, 215, 109, 145, 180, 227, 75, 147, 86, 166, 249, 34, 130, 248, 221, 184, 91, 233, 37, 167, 107
]);

#[cfg(not(feature = "offchain"))]
pub const PROGRAM_ID: crate::sdk_core::Address = crate::sdk_core::Address::new_from_array([
    23, 44, 20, 102, 242, 76, 74, 93, 22, 245, 59, 53, 215, 109, 145, 180, 227, 75, 147, 86, 166, 249, 34, 130, 248, 221, 184, 91, 233, 37, 167, 107
]);

pub const SEED_VAULT: &[u8] = &[118, 97, 117, 108, 116];
pub const SEED_USER_ACCOUNT: &[u8] = &[117, 115, 101, 114, 95, 118, 97, 117, 108, 116];
