// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#![cfg_attr(all(feature = "cpi", feature = "pinocchio"), no_std)]

#[cfg(feature = "cpi")]
pub use naclac_lang::prelude as sdk_core_cpi;
#[cfg(feature = "offchain")]
pub use naclac_client as sdk_core_offchain;

pub mod instructions;
pub mod types;

pub use instructions::*;
pub use types::*;

#[macro_export]
macro_rules! declare_id {
    ($id:expr) => {};
}

declare_id!("AUejAUt7m2v3QFitS8f6v7y9FqAnNtFAP4q1s7tgEVmV");

#[cfg(feature = "cpi")]
#[derive(Clone, Copy)]
pub struct ErrorCodes;

#[cfg(feature = "cpi")]
impl sdk_core_cpi::Id for ErrorCodes {
    fn id() -> sdk_core_cpi::Address {
        sdk_core_cpi::Address::new_from_array([140, 206, 133, 174, 21, 242, 140, 27, 255, 11, 204, 126, 160, 130, 75, 118, 117, 63, 39, 36, 122, 212, 131, 51, 70, 73, 225, 12, 86, 164, 56, 220])
    }
}

