// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#![cfg_attr(all(feature = "cpi", feature = "pinocchio"), no_std)]

#[cfg(feature = "cpi")]
pub use naclac_lang::prelude as sdk_core_cpi;
#[cfg(feature = "offchain")]
pub use naclac_client as sdk_core_offchain;

#[cfg(feature = "offchain")]
pub mod components;
pub mod instructions;
pub mod types;

#[cfg(feature = "offchain")]
pub use components::*;
pub use instructions::*;
pub use types::*;

#[macro_export]
macro_rules! declare_id {
    ($id:expr) => {};
}

declare_id!("9ckKeo7g3MRX7fWNh1obrJfyWcbobGSHFXZwBfvnmHCr");

#[cfg(feature = "offchain")]
pub fn get_vault_a_pda(
    program_id: &naclac_client::Address
) -> (naclac_client::Address, u8) {
    naclac_client::Address::find_program_address(
        &[
            &[118, 97, 117, 108, 116, 95, 97],
        ],
        program_id,
    )
}

#[cfg(feature = "offchain")]
pub fn get_vault_b_pda(
    program_id: &naclac_client::Address
) -> (naclac_client::Address, u8) {
    naclac_client::Address::find_program_address(
        &[
            &[118, 97, 117, 108, 116, 95, 98],
        ],
        program_id,
    )
}

#[cfg(feature = "offchain")]
pub fn get_vault_c_pda(
    program_id: &naclac_client::Address
) -> (naclac_client::Address, u8) {
    naclac_client::Address::find_program_address(
        &[
            &[118, 97, 117, 108, 116, 95, 99],
        ],
        program_id,
    )
}

#[cfg(feature = "cpi")]
#[derive(Clone, Copy)]
pub struct DupMutBorsh;

#[cfg(feature = "cpi")]
impl sdk_core_cpi::Id for DupMutBorsh {
    fn id() -> sdk_core_cpi::Address {
        sdk_core_cpi::Address::new_from_array([128, 5, 206, 190, 141, 126, 3, 70, 92, 169, 187, 200, 131, 205, 25, 227, 8, 50, 2, 124, 176, 136, 113, 40, 95, 207, 73, 123, 145, 213, 174, 63])
    }
}

