[package]
name = "metadata"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]
custom-heap = []
custom-panic = []
debug-mode = []
default = ["pinocchio"]
pinocchio = ["naclac-lang/pinocchio"]

[dependencies]
naclac-lang = { version = "0.1.0", default-features = false, path = "../../../../naclac-lang", features = ["metadata"] }

[dev-dependencies]
naclac-client = { version = "0.1.0", path = "../../../../naclac-client" }
metadata-client = { version = "0.1.0", path = "../../clients/rust/metadata" }
serde_json = "1.0.149"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(target_os, values("solana"))',
    'cfg(feature, values("pinocchio", "solana", "borsh"))'
] }
