// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
/// Creates the singleton `GlobalConfig`, gated by the project's own
/// `ADMIN_PUBKEY` (see its doc comment for why this diverges from real
/// `pump_amm`'s hardcoded admin). Leaves `boost_enabled`/`boost_authority`
/// at their zero-init defaults -- `toggle_boost`/`set_boost_authority`
/// (both gated on `global_config.admin`, set here) enable them separately,
/// matching real `create_config`'s own args, which don't include boost
/// fields at all.
pub struct CreateConfigAccounts {
    pub admin: naclac_client::Address,
    pub global_config: naclac_client::Address,
    pub system_program: naclac_client::Address,
}

#[cfg(feature = "offchain")]
/// Creates the singleton `GlobalConfig`, gated by the project's own
/// `ADMIN_PUBKEY` (see its doc comment for why this diverges from real
/// `pump_amm`'s hardcoded admin). Leaves `boost_enabled`/`boost_authority`
/// at their zero-init defaults -- `toggle_boost`/`set_boost_authority`
/// (both gated on `global_config.admin`, set here) enable them separately,
/// matching real `create_config`'s own args, which don't include boost
/// fields at all.
pub fn build_create_config<'a>(
    provider: &'a naclac_client::NaclacProvider,
    program_id: naclac_client::Address,
    accounts: CreateConfigAccounts,
) -> naclac_client::InstructionBuilder<'a> {
    let ix_data = crate::sdk_core_offchain::vec![201, 207, 243, 114, 75, 111, 47, 189];
    naclac_client::InstructionBuilder::new(provider, program_id, ix_data)
        .account(naclac_client::AccountMeta { address: accounts.admin, is_signer: true, is_writable: true }, "admin")
        .account(naclac_client::AccountMeta { address: accounts.global_config, is_signer: false, is_writable: true }, "global_config")
        .account(naclac_client::AccountMeta { address: accounts.system_program, is_signer: false, is_writable: false }, "system_program")
}

#[cfg(feature = "cpi")]
/// Creates the singleton `GlobalConfig`, gated by the project's own
/// `ADMIN_PUBKEY` (see its doc comment for why this diverges from real
/// `pump_amm`'s hardcoded admin). Leaves `boost_enabled`/`boost_authority`
/// at their zero-init defaults -- `toggle_boost`/`set_boost_authority`
/// (both gated on `global_config.admin`, set here) enable them separately,
/// matching real `create_config`'s own args, which don't include boost
/// fields at all.
pub struct CreateConfigCpiAccounts<'a> {
    pub admin: crate::sdk_core_cpi::CpiHandleMut<'a>,
    pub global_config: crate::sdk_core_cpi::CpiHandleMut<'a>,
    pub system_program: crate::sdk_core_cpi::CpiHandle<'a>,
}

#[cfg(feature = "cpi")]
pub struct CreateConfigCpiCall<'a> {
    pub accounts: CreateConfigCpiAccounts<'a>,
    pub signer_seeds: &'a [&'a [&'a [u8]]],
    pub remaining_accounts: &'a [(crate::sdk_core_cpi::AccountInfo, bool, bool)],
}

#[cfg(feature = "cpi")]
pub trait CreateConfigCpi<'info> {
    /// Creates the singleton `GlobalConfig`, gated by the project's own
    /// `ADMIN_PUBKEY` (see its doc comment for why this diverges from real
    /// `pump_amm`'s hardcoded admin). Leaves `boost_enabled`/`boost_authority`
    /// at their zero-init defaults -- `toggle_boost`/`set_boost_authority`
    /// (both gated on `global_config.admin`, set here) enable them separately,
    /// matching real `create_config`'s own args, which don't include boost
    /// fields at all.
    fn create_config<'a>(
        &self,
        accounts: CreateConfigCpiAccounts<'a>
    ) -> crate::sdk_core_cpi::Result<()> {
        self.create_config_with_remaining_accounts(CreateConfigCpiCall {
        accounts,
        signer_seeds: &[],
        remaining_accounts: &[],
    })
    }

    fn create_config_signed<'a>(
        &self,
        accounts: CreateConfigCpiAccounts<'a>,
        signer_seeds: &[&[&[u8]]]
    ) -> crate::sdk_core_cpi::Result<()> {
        self.create_config_with_remaining_accounts(CreateConfigCpiCall {
        accounts,
        signer_seeds,
        remaining_accounts: &[],
    })
    }

    fn create_config_with_remaining_accounts<'a>(
        &self,
        call: CreateConfigCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()>;

}

#[cfg(feature = "cpi")]
impl<'info> CreateConfigCpi<'info> for crate::sdk_core_cpi::Program<crate::PumpAmm> {
    fn create_config_with_remaining_accounts<'a>(
        &self,
        call: CreateConfigCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()> {
        let CreateConfigCpiCall { accounts, signer_seeds, remaining_accounts } = call;
        let mut ix_data = crate::sdk_core_cpi::Vec::new();
        ix_data.extend_from_slice(&[201, 207, 243, 114, 75, 111, 47, 189]);
        #[cfg(feature = "pinocchio")]
        {
            let mut metas_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount>::uninit() }; 32];
            let mut idx = 0;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable_signer(accounts.admin.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(accounts.global_config.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.system_program.info.view.address()));
            idx += 1;
            for (acc, is_writable, is_signer) in remaining_accounts {
                if idx >= 32 { break; }
                let meta = if *is_writable {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(acc.view.address())
                    }
                } else {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(acc.view.address())
                    }
                };
                metas_arr[idx].write(meta);
                idx += 1;
            }
            let account_metas = unsafe { core::slice::from_raw_parts(metas_arr.as_ptr() as *const crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount, idx) };
            let program_id_address = self.address();
            let instruction = crate::sdk_core_cpi::pinocchio::instruction::InstructionView {
                program_id: program_id_address.as_address(),
                accounts: account_metas,
                data: &ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.admin));
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.global_config));
            h_idx += 1;
            handles_arr[h_idx].write(accounts.system_program);
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed_pinocchio_handles(&instruction, account_handles, signer_seeds)
        }
        #[cfg(not(feature = "pinocchio"))]
        {
            use crate::sdk_core_cpi::ToAddress;
            let mut account_metas = crate::sdk_core_cpi::vec![
                ::naclac_lang::solana_program::instruction::AccountMeta::new(accounts.admin.address(), true),
                ::naclac_lang::solana_program::instruction::AccountMeta::new(accounts.global_config.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.system_program.address(), false),
            ];
            for (acc, is_writable, is_signer) in remaining_accounts {
                let meta = if *is_writable {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new(acc.address(), *is_signer)
                } else {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(acc.address(), *is_signer)
                };
                account_metas.push(meta);
            }
            let instruction = ::naclac_lang::solana_program::instruction::Instruction {
                program_id: self.address(),
                accounts: account_metas,
                data: ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.admin));
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.global_config));
            h_idx += 1;
            handles_arr[h_idx].write(accounts.system_program);
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed(&instruction, account_handles, signer_seeds)
        }
    }
}

