// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
#[cfg(feature = "borsh")]
use crate::sdk_core_offchain::borsh::BorshSerialize;
#[cfg(feature = "offchain")]
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_offchain::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Copy, Clone, Debug))]
#[cfg_attr(not(feature = "borsh"), repr(C, packed))]
pub struct ToggleBoostIxArgs {
    pub enabled: crate::sdk_core_offchain::Bool,
}

#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Zeroable for ToggleBoostIxArgs {}
#[cfg(feature = "offchain")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_offchain::bytemuck::Pod for ToggleBoostIxArgs {}

#[cfg(feature = "cpi")]
#[cfg(feature = "borsh")]
use crate::sdk_core_cpi::borsh::BorshSerialize;
#[cfg(feature = "cpi")]
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_cpi::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Copy, Clone, Debug))]
#[cfg_attr(not(feature = "borsh"), repr(C, packed))]
pub struct ToggleBoostCpiIxArgs {
    pub enabled: crate::sdk_core_cpi::Bool,
}

#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Zeroable for ToggleBoostCpiIxArgs {}
#[cfg(feature = "cpi")]
#[cfg(not(feature = "borsh"))]
unsafe impl crate::sdk_core_cpi::bytemuck::Pod for ToggleBoostCpiIxArgs {}

#[cfg(feature = "offchain")]
pub struct ToggleBoostAccounts {
    pub admin: naclac_client::Address,
    pub global_config: naclac_client::Address,
}

#[cfg(feature = "offchain")]
pub fn build_toggle_boost<'a>(
    provider: &'a naclac_client::NaclacProvider,
    program_id: naclac_client::Address,
    enabled: crate::sdk_core_offchain::Bool,
    accounts: ToggleBoostAccounts,
) -> naclac_client::InstructionBuilder<'a> {
    let mut ix_data = crate::sdk_core_offchain::vec![117, 161, 160, 74, 223, 137, 118, 99];
    let args = ToggleBoostIxArgs {
        enabled,
    };
    #[cfg(not(feature = "borsh"))]
    {
        ix_data.extend_from_slice(crate::sdk_core_offchain::bytemuck::bytes_of(&args));
    }
    #[cfg(feature = "borsh")]
    {
        crate::sdk_core_offchain::borsh::BorshSerialize::serialize(&args, &mut ix_data).unwrap();
    }
    naclac_client::InstructionBuilder::new(provider, program_id, ix_data)
        .account(naclac_client::AccountMeta { address: accounts.admin, is_signer: true, is_writable: false }, "admin")
        .account(naclac_client::AccountMeta { address: accounts.global_config, is_signer: false, is_writable: true }, "global_config")
}

#[cfg(feature = "cpi")]
pub struct ToggleBoostCpiAccounts<'a> {
    pub admin: crate::sdk_core_cpi::CpiHandle<'a>,
    pub global_config: crate::sdk_core_cpi::CpiHandleMut<'a>,
}

#[cfg(feature = "cpi")]
pub struct ToggleBoostCpiCall<'a> {
    pub accounts: ToggleBoostCpiAccounts<'a>,
    pub enabled: crate::sdk_core_cpi::Bool,
    pub signer_seeds: &'a [&'a [&'a [u8]]],
    pub remaining_accounts: &'a [(crate::sdk_core_cpi::AccountInfo, bool, bool)],
}

#[cfg(feature = "cpi")]
pub trait ToggleBoostCpi<'info> {
    fn toggle_boost<'a>(
        &self,
        accounts: ToggleBoostCpiAccounts<'a>,
        enabled: crate::sdk_core_cpi::Bool
    ) -> crate::sdk_core_cpi::Result<()> {
        self.toggle_boost_with_remaining_accounts(ToggleBoostCpiCall {
        accounts,
        enabled,
        signer_seeds: &[],
        remaining_accounts: &[],
    })
    }

    fn toggle_boost_signed<'a>(
        &self,
        accounts: ToggleBoostCpiAccounts<'a>,
        enabled: crate::sdk_core_cpi::Bool,
        signer_seeds: &[&[&[u8]]]
    ) -> crate::sdk_core_cpi::Result<()> {
        self.toggle_boost_with_remaining_accounts(ToggleBoostCpiCall {
        accounts,
        enabled,
        signer_seeds,
        remaining_accounts: &[],
    })
    }

    fn toggle_boost_with_remaining_accounts<'a>(
        &self,
        call: ToggleBoostCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()>;

}

#[cfg(feature = "cpi")]
impl<'info> ToggleBoostCpi<'info> for crate::sdk_core_cpi::Program<crate::PumpAmm> {
    fn toggle_boost_with_remaining_accounts<'a>(
        &self,
        call: ToggleBoostCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()> {
        let ToggleBoostCpiCall { accounts, enabled, signer_seeds, remaining_accounts } = call;
        let args = ToggleBoostCpiIxArgs {
            enabled,
        };
        let mut ix_data = crate::sdk_core_cpi::Vec::new();
        ix_data.extend_from_slice(&[117, 161, 160, 74, 223, 137, 118, 99]);
        #[cfg(not(feature = "borsh"))]
        {
        ix_data.extend_from_slice(crate::sdk_core_cpi::bytemuck::bytes_of(&args));
        }
        #[cfg(feature = "borsh")]
        {
            crate::sdk_core_cpi::borsh::BorshSerialize::serialize(&args, &mut ix_data).unwrap();
        }
        #[cfg(feature = "pinocchio")]
        {
            let mut metas_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount>::uninit() }; 32];
            let mut idx = 0;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly_signer(accounts.admin.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(accounts.global_config.info.view.address()));
            idx += 1;
            for (acc, is_writable, is_signer) in remaining_accounts {
                if idx >= 32 { break; }
                let meta = if *is_writable {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(acc.view.address())
                    }
                } else {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(acc.view.address())
                    }
                };
                metas_arr[idx].write(meta);
                idx += 1;
            }
            let account_metas = unsafe { core::slice::from_raw_parts(metas_arr.as_ptr() as *const crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount, idx) };
            let program_id_address = self.address();
            let instruction = crate::sdk_core_cpi::pinocchio::instruction::InstructionView {
                program_id: program_id_address.as_address(),
                accounts: account_metas,
                data: &ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(accounts.admin);
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.global_config));
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed_pinocchio_handles(&instruction, account_handles, signer_seeds)
        }
        #[cfg(not(feature = "pinocchio"))]
        {
            use crate::sdk_core_cpi::ToAddress;
            let mut account_metas = crate::sdk_core_cpi::vec![
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.admin.address(), true),
                ::naclac_lang::solana_program::instruction::AccountMeta::new(accounts.global_config.address(), false),
            ];
            for (acc, is_writable, is_signer) in remaining_accounts {
                let meta = if *is_writable {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new(acc.address(), *is_signer)
                } else {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(acc.address(), *is_signer)
                };
                account_metas.push(meta);
            }
            let instruction = ::naclac_lang::solana_program::instruction::Instruction {
                program_id: self.address(),
                accounts: account_metas,
                data: ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(accounts.admin);
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.global_config));
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed(&instruction, account_handles, signer_seeds)
        }
    }
}

