// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#![cfg_attr(all(feature = "cpi", feature = "pinocchio"), no_std)]

#[cfg(feature = "cpi")]
pub use naclac_lang::prelude as sdk_core_cpi;
#[cfg(feature = "offchain")]
pub use naclac_client as sdk_core_offchain;

#[cfg(feature = "offchain")]
pub mod components;
pub mod instructions;
pub mod types;

#[cfg(feature = "offchain")]
pub use components::*;
pub use instructions::*;
pub use types::*;

#[macro_export]
macro_rules! declare_id {
    ($id:expr) => {};
}

declare_id!("MqiMRvWB6ZjHwQGQvooZefAhDnEzfNV3JrBCCgZqHg9");

#[cfg(feature = "offchain")]
pub fn get_counter_account_pda(
    program_id: &naclac_client::Address
) -> (naclac_client::Address, u8) {
    naclac_client::Address::find_program_address(
        &[
            &[99, 111, 117, 110, 116, 101, 114, 95, 118, 50],
        ],
        program_id,
    )
}

#[cfg(feature = "cpi")]
#[derive(Clone, Copy)]
pub struct CounterBorsh;

#[cfg(feature = "cpi")]
impl sdk_core_cpi::Id for CounterBorsh {
    fn id() -> sdk_core_cpi::Address {
        sdk_core_cpi::Address::new_from_array([5, 86, 178, 52, 98, 62, 183, 232, 194, 174, 138, 126, 96, 186, 30, 131, 18, 186, 214, 97, 2, 133, 103, 68, 158, 15, 37, 168, 150, 2, 64, 62])
    }
}

