//! # Program Macro Logic
//!
//! Handles the expansion of the `#[program]` macro, serving as the core router
//! and instruction dispatcher for the smart contract across all execution modes.

use proc_macro::TokenStream;
use quote::{format_ident, quote};
use sha2::{Digest, Sha256};
use syn::{parse_macro_input, FnArg, Item, ItemMod, Pat, Type};

/// Extracts `T` from a handler's `-> Result<T>` return type. Bare `Result`
/// (no `<...>` at all, i.e. `T` defaulted to `()`) and an explicit
/// `Result<()>` both mean "no return value" and yield `None`; anything else
/// yields `Some(T)`. Mirrors Anchor v2's own `extract_result_return_type`.
fn extract_result_return_type(output: &syn::ReturnType) -> Option<Type> {
    let syn::ReturnType::Type(_, ty) = output else {
        return None;
    };
    let Type::Path(type_path) = &**ty else {
        return None;
    };
    let segment = type_path.path.segments.last()?;
    if segment.ident != "Result" {
        return None;
    }
    let syn::PathArguments::AngleBracketed(args) = &segment.arguments else {
        // Bare `Result`, no generics written at all — defaults to T = ().
        return None;
    };
    let syn::GenericArgument::Type(return_ty) = args.args.first()? else {
        return None;
    };
    if is_unit_type(return_ty) {
        None
    } else {
        Some(return_ty.clone())
    }
}

fn is_unit_type(ty: &Type) -> bool {
    matches!(ty, Type::Tuple(t) if t.elems.is_empty())
}

/// If `ty` is literally `Option<Inner>`, returns `Inner`.
fn extract_option_inner(ty: &Type) -> Option<&Type> {
    let Type::Path(type_path) = ty else {
        return None;
    };
    let segment = type_path.path.segments.last()?;
    if segment.ident != "Option" {
        return None;
    }
    let syn::PathArguments::AngleBracketed(args) = &segment.arguments else {
        return None;
    };
    let syn::GenericArgument::Type(inner) = args.args.first()? else {
        return None;
    };
    Some(inner)
}

/// Generates the code that serializes `__result`'s `Ok` value (if the
/// handler declared one via `-> Result<T>`) and sets it as the instruction's
/// return data — via `NaclacReturnData::to_return_data`, generated by
/// `#[component]`/`#[event]`/the blanket `Pod` impl. `Option<T>` is detected
/// here, at macro-expansion time, rather than via a blanket `impl<T> for
/// Option<T>` in `naclac-core`, which would conflict with the blanket
/// `impl<T: Pod> for T` under Rust's coherence rules.
fn set_return_data_tokens(
    return_ty: &Option<Type>,
    set_return_data_call: proc_macro2::TokenStream,
) -> proc_macro2::TokenStream {
    let Some(return_ty) = return_ty else {
        return quote! {};
    };
    if let Some(_inner) = extract_option_inner(return_ty) {
        quote! {
            if let Ok(__value) = &__result {
                match __value {
                    Some(__inner) => {
                        let __encoded = naclac_lang::prelude::NaclacReturnData::to_return_data(__inner);
                        let mut __return_data = naclac_lang::prelude::Vec::with_capacity(1 + __encoded.len());
                        __return_data.push(1u8);
                        __return_data.extend_from_slice(&__encoded);
                        #set_return_data_call(&__return_data);
                    }
                    None => {
                        #set_return_data_call(&[0u8]);
                    }
                }
            }
        }
    } else {
        quote! {
            if let Ok(__value) = &__result {
                let __return_data = naclac_lang::prelude::NaclacReturnData::to_return_data(__value);
                #set_return_data_call(&__return_data);
            }
        }
    }
}

/// A helper function to traverse the AST and extract the underlying accounts struct
/// from `Context<MyAccounts>` or `&mut Context<MyAccounts>`.
fn extract_context_struct(ty: &Type) -> Option<syn::Path> {
    // Support both `Context<T>` and `&mut Context<T>`
    let ty_path = match ty {
        Type::Path(p) => Some(p),
        Type::Reference(r) => {
            if let Type::Path(p) = &*r.elem {
                Some(p)
            } else {
                None
            }
        }
        _ => None,
    };

    if let Some(type_path) = ty_path {
        if let Some(segment) = type_path.path.segments.last() {
            if segment.ident == "Context" {
                if let syn::PathArguments::AngleBracketed(args) = &segment.arguments {
                    for arg in &args.args {
                        // Ignore lifetimes, find the actual Type
                        if let syn::GenericArgument::Type(Type::Path(inner_path)) = arg {
                            let mut path = inner_path.path.clone();
                            // Strip any generic arguments (like <'info>) to avoid syntax errors when used in expressions
                            if let Some(last_segment) = path.segments.last_mut() {
                                last_segment.arguments = syn::PathArguments::None;
                            }
                            return Some(path);
                        }
                    }
                }
            }
        }
    }
    None
}

/// Expands the `#[program]` macro.
///
/// This macro traverses the module items, finds public functions representing instructions,
/// and generates a highly optimized `match` dispatcher. It handles routing and signature
/// rewrites across three distinct execution modes:
/// 1. **Solana Program + Borsh**: Emits `BorshDeserialize` logic.
/// 2. **Solana Program + Zero-Copy**: Emits native slicing logic alongside heap allocation for dynamic types.
/// 3. **Pinocchio + Zero-Copy**: Fully zero-copy slicing strictly for `no_std`.
pub fn expand(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let module = parse_macro_input!(item as ItemMod);
    let mod_name = &module.ident;
    let mod_vis = &module.vis;

    let content_items = match &module.content {
        Some((_, items)) => items.clone(),
        None => panic!("Naclac: #[program] requires a module body with items."),
    };

    let mut match_arms = Vec::new();

    // 1. Iterate through all items in the module to find the developer's instructions
    let mut processed_content_items = Vec::new();

    // Zero-copy vs Borsh mode is auto-detected from the `borsh` feature.
    // `#[program]` takes no argument at all — enforced by `lib.rs`'s
    // `reject_nonempty_attr` before this function is ever called.
    let is_program_zero_copy =
        crate::caller_has_feature("pinocchio") || !crate::caller_has_feature("borsh");

    for item in &content_items {
        if let Item::Fn(func) = item {
            let mut new_func = func.clone();

            // Only process public functions (these are the instructions)
            if matches!(func.vis, syn::Visibility::Public(_)) {
                let func_name = &func.sig.ident;

                // Arguments explicitly marked `#[allow_heap]` skip the heap-collection
                // warning below entirely — a purpose-built, macro-native opt-out rather
                // than rustc's generic `#[allow(deprecated)]`, which would also silence
                // unrelated real deprecation warnings anywhere else in the same function.
                // The marker is consumed here (stripped from `pat_type.attrs` before
                // `new_func` is re-emitted) since it isn't a real attribute rustc knows.
                let mut heap_allowed_args: std::collections::HashSet<syn::Ident> =
                    std::collections::HashSet::new();

                // --- SIGNATURE REWRITING (AUTOMATIC LIFETIMES & REFERENCES) ---
                for arg in &mut new_func.sig.inputs {
                    if let FnArg::Typed(pat_type) = arg {
                        let had_allow_heap = pat_type
                            .attrs
                            .iter()
                            .any(|a| a.path().is_ident("allow_heap"));
                        pat_type.attrs.retain(|a| !a.path().is_ident("allow_heap"));
                        if had_allow_heap {
                            if let Pat::Ident(pat_ident) = &*pat_type.pat {
                                heap_allowed_args.insert(pat_ident.ident.clone());
                            }
                        }

                        // Detect if this is a Vec or String to perform type rewriting in Zero-Copy mode
                        let ty = &pat_type.ty;
                        if is_program_zero_copy {
                            if crate::type_classify::is_exactly(ty, "ZcVec") {
                                // ZcVec<T> → Span<T>: explicit zero-copy opt-in
                                let new_ty: syn::Type =
                                    match crate::type_classify::first_generic_type(ty) {
                                        Some(inner) => {
                                            syn::parse_quote! { naclac_lang::prelude::Span<#inner> }
                                        }
                                        None => {
                                            syn::parse_quote! { naclac_lang::prelude::Span<u8> }
                                        }
                                    };
                                *pat_type.ty = new_ty;
                            } else if crate::type_classify::is_exactly(ty, "ZcString") {
                                // ZcString → ZcString: explicit zero-copy opt-in
                                let new_ty: syn::Type =
                                    syn::parse_str("naclac_lang::prelude::ZcString").unwrap();
                                *pat_type.ty = new_ty;
                            }
                            // Standard Vec<T> and String: leave as-is, they use heap allocation
                        }

                        // Strip any references to get to the underlying Context type
                        let mut inner_ty = (*pat_type.ty).clone();

                        if let Type::Reference(r) = &inner_ty {
                            inner_ty = (*r.elem).clone();
                        }

                        if let Type::Path(type_path) = &mut inner_ty {
                            if let Some(segment) = type_path.path.segments.last_mut() {
                                if segment.ident == "Context" {
                                    if let syn::PathArguments::AngleBracketed(args) =
                                        &mut segment.arguments
                                    {
                                        // Find the account struct type arg
                                        let mut type_arg_idx = None;
                                        for (i, arg) in args.args.iter().enumerate() {
                                            if let syn::GenericArgument::Type(_) = arg {
                                                type_arg_idx = Some(i);
                                                break;
                                            }
                                        }

                                        if let Some(idx) = type_arg_idx {
                                            if let syn::GenericArgument::Type(Type::Path(
                                                inner_path,
                                            )) = &mut args.args[idx]
                                            {
                                                if let Some(last_seg) =
                                                    inner_path.path.segments.last_mut()
                                                {
                                                    last_seg.arguments = syn::PathArguments::None;
                                                }
                                            }

                                            // Ensure Context has precisely <T> (lifetime-free)
                                            let mut new_args = syn::punctuated::Punctuated::<
                                                syn::GenericArgument,
                                                syn::Token![,],
                                            >::new(
                                            );
                                            new_args.push(args.args[idx].clone());
                                            args.args = new_args;
                                        }
                                    }

                                    // Standardize the parameter type to Context<T>
                                    // avoiding &mut references to prevent type mismatches in CPI wrappers.
                                    *pat_type.ty = syn::parse_quote! { #inner_ty };
                                }
                            }
                        }
                    }
                }

                // --- DISCRIMINATOR HASH ---
                let func_str = func_name.to_string();
                let preimage = format!("global:{}", func_str);
                let mut hasher = Sha256::new();
                hasher.update(preimage.as_bytes());
                let disc: [u8; 8] = hasher.finalize()[..8].try_into().unwrap();
                let b0 = disc[0];
                let b1 = disc[1];
                let b2 = disc[2];
                let b3 = disc[3];
                let b4 = disc[4];
                let b5 = disc[5];
                let b6 = disc[6];
                let b7 = disc[7];

                // --- SIGNATURE PARSING ---
                let mut context_struct_name = None;
                let mut arg_names = Vec::new();
                let mut arg_types = Vec::new();

                for arg in &func.sig.inputs {
                    if let FnArg::Typed(pat_type) = arg {
                        if let Pat::Ident(pat_ident) = &*pat_type.pat {
                            let arg_name = &pat_ident.ident;
                            if let Some(ctx_path) = extract_context_struct(&pat_type.ty) {
                                context_struct_name = Some(ctx_path);
                            } else {
                                arg_names.push(arg_name);
                                arg_types.push(&pat_type.ty);
                            }
                        }
                    }
                }

                let ctx_struct = match context_struct_name {
                    Some(name) => name,
                    None => panic!(
                        "Naclac: Instruction '{}' must have a Context argument.",
                        func_name
                    ),
                };

                // Zero-copy mode is decided once for the whole program (see
                // `is_program_zero_copy` above) — no per-instruction override.
                // `#[instruction]` itself rejects any argument (lib.rs), so a
                // leftover `#[instruction(zero_copy)]` is a compile error,
                // not a silent no-op here.
                let is_zero_copy = is_program_zero_copy;

                // --- ARGUMENT DESERIALIZATION LOGIC ---
                let mut deserialization_logic = Vec::new();
                let mut arg_tuple_names = Vec::new();
                let mut arg_tuple_types = Vec::new();
                let mut slice_arg_names = Vec::new();

                // __ix_offset is emitted conditionally — only when there are non-slice args.
                // Instructions with no arguments (e.g. increment) get zero dead code.
                let mut has_non_slice_args = false;

                for (name, ty) in arg_names.iter().zip(arg_types.iter()) {
                    if crate::type_classify::is_byte_slice_ref(ty) {
                        slice_arg_names.push(*name);
                        continue;
                    }

                    arg_tuple_names.push(*name);
                    arg_tuple_types.push(*ty);
                    has_non_slice_args = true;

                    use crate::type_classify::DynamicKind;
                    let kind = crate::type_classify::classify_dynamic(ty);
                    let is_zero_copy_vec = matches!(kind, DynamicKind::ZcVec);
                    let is_zero_copy_string = matches!(kind, DynamicKind::ZcString);
                    let is_zero_copy_collection = is_zero_copy_vec || is_zero_copy_string;
                    let is_heap_vec = matches!(kind, DynamicKind::HeapVec);
                    let is_heap_string = matches!(kind, DynamicKind::HeapString);
                    let is_heap_collection = is_heap_vec || is_heap_string;

                    if is_zero_copy && !is_zero_copy_collection && !is_heap_collection {
                        // `NaclacArgs` (not `NaclacPod` directly) — covers both a
                        // plain fixed-size arg (via `NaclacPod`'s blanket
                        // `NaclacArgs` impl) and an `#[instruction_args]`-grouped
                        // struct containing a `ZcString`/`ZcVec` field, whose
                        // encoded length depends on its own content and can
                        // never be read via a single raw `size_of`-based cast.
                        deserialization_logic.push(quote! {
                            let #name = <#ty as naclac_lang::prelude::NaclacArgs>::naclac_deserialize(
                                instruction_data, &mut __ix_offset
                            )?;
                        });
                    } else if is_zero_copy && (is_zero_copy_collection || is_heap_collection) {
                        let inner_ty = crate::type_classify::first_generic_type(ty);

                        let __v_logic = if is_zero_copy_collection {
                            if is_zero_copy_vec {
                                if let Some(inner) = &inner_ty {
                                    quote! {
                                        let __v = <naclac_lang::prelude::Span<#inner>>::from_bytes(&instruction_data[__ix_offset..__ix_offset + __len])?;
                                        __ix_offset += __len;
                                        __v
                                    }
                                } else {
                                    quote! {
                                        let __v = <naclac_lang::prelude::Span<u8>>::from_bytes(&instruction_data[__ix_offset..__ix_offset + __len])?;
                                        __ix_offset += __len;
                                        __v
                                    }
                                }
                            } else {
                                quote! {
                                    let __v = <naclac_lang::prelude::ZcString>::from_bytes(&instruction_data[__ix_offset..__ix_offset + __len])?;
                                    __ix_offset += __len;
                                    __v
                                }
                            }
                        } else {
                            let is_nested_vec = is_heap_vec
                                && inner_ty.is_some_and(|inner| {
                                    crate::type_classify::is_exactly(inner, "Vec")
                                });
                            if is_heap_string {
                                quote! {
                                    let __bytes_len = __len as usize;
                                    if instruction_data.len() < __ix_offset + __bytes_len {
                                        return Err(naclac_lang::prelude::NaclacError::InvalidInstructionData.err(0));
                                    }
                                    let __v = naclac_lang::prelude::String::from_utf8(instruction_data[__ix_offset..__ix_offset+__bytes_len].to_vec())
                                        .map_err(|_| naclac_lang::prelude::NaclacError::InvalidInstructionData.err(0))?;
                                    __ix_offset += __bytes_len;
                                    __v
                                }
                            } else if is_nested_vec {
                                quote! {
                                    let mut __outer_vec = naclac_lang::prelude::Vec::with_capacity(__len as usize);
                                    for _ in 0..__len {
                                        if instruction_data.len() < __ix_offset + 4 {
                                            return Err(naclac_lang::prelude::NaclacError::InvalidInstructionData.err(0));
                                        }
                                        let mut __inner_len_bytes = [0u8; 4];
                                        __inner_len_bytes.copy_from_slice(&instruction_data[__ix_offset..__ix_offset+4]);
                                        let __inner_len = u32::from_le_bytes(__inner_len_bytes) as usize;
                                        __ix_offset += 4;
                                        if instruction_data.len() < __ix_offset + __inner_len {
                                            return Err(naclac_lang::prelude::NaclacError::InvalidInstructionData.err(0));
                                        }
                                        let mut __inner_vec = naclac_lang::prelude::Vec::with_capacity(__inner_len);
                                        __inner_vec.extend_from_slice(&instruction_data[__ix_offset..__ix_offset+__inner_len]);
                                        __outer_vec.push(__inner_vec);
                                        __ix_offset += __inner_len;
                                    }
                                    let __v = __outer_vec;
                                    __v
                                }
                            } else {
                                if let Some(inner) = &inner_ty {
                                    if crate::type_classify::is_exactly(inner, "u8") {
                                        quote! {
                                            let __bytes_len = __len as usize;
                                            if instruction_data.len() < __ix_offset + __bytes_len {
                                                return Err(naclac_lang::prelude::NaclacError::InvalidInstructionData.err(0));
                                            }
                                            let mut __v = naclac_lang::prelude::Vec::with_capacity(__bytes_len);
                                            __v.extend_from_slice(&instruction_data[__ix_offset..__ix_offset+__bytes_len]);
                                            __ix_offset += __bytes_len;
                                            __v
                                        }
                                    } else {
                                        quote! {
                                            let mut __v = naclac_lang::prelude::Vec::with_capacity(__len as usize);
                                            let __sz = <#inner as naclac_lang::prelude::NaclacPod>::naclac_size();
                                            for _ in 0..__len {
                                                if instruction_data.len() < __ix_offset + __sz {
                                                    return Err(naclac_lang::prelude::NaclacError::InvalidInstructionData.err(0));
                                                }
                                                let __item = <#inner as naclac_lang::prelude::NaclacPod>::naclac_from_bytes(
                                                    &instruction_data[__ix_offset..__ix_offset + __sz]
                                                );
                                                __v.push(__item);
                                                __ix_offset += __sz;
                                            }
                                            __v
                                        }
                                    }
                                } else {
                                    quote! {
                                        return Err(naclac_lang::prelude::NaclacError::InvalidInstructionData.err(0));
                                    }
                                }
                            }
                        };

                        if is_heap_collection && !heap_allowed_args.contains(*name) {
                            let found_ty = if is_heap_vec { "Vec<T>" } else { "String" };
                            let suggested_ty = if is_heap_vec { "ZcVec<T>" } else { "ZcString" };
                            deserialization_logic.push(crate::heap_collection_warning(
                                &name.to_string(),
                                found_ty,
                                suggested_ty,
                            ));
                        }

                        deserialization_logic.push(quote! {
                            let #name = {
                                if instruction_data.len() < __ix_offset + 4 {
                                    return Err(naclac_lang::prelude::NaclacError::InvalidInstructionData.err(0));
                                }
                                let mut __len_bytes = [0u8; 4];
                                __len_bytes.copy_from_slice(&instruction_data[__ix_offset..__ix_offset+4]);
                                let __len = u32::from_le_bytes(__len_bytes) as usize;
                                __ix_offset += 4;
                                #__v_logic
                            };
                        });
                    } else {
                        // Reached only when `is_zero_copy` is already false (the two
                        // branches above cover every zero-copy case), so the calling
                        // crate is confirmed Borsh-mode and the `pinocchio` arm below
                        // can never actually be selected for it — kept only as a
                        // defensive fallback in case that assumption ever changes.
                        deserialization_logic.push(quote! {
                            #[cfg(feature = "pinocchio")]
                            let #name = {
                                let __sz = <#ty as naclac_lang::prelude::NaclacPod>::naclac_size();
                                if instruction_data.len() < __ix_offset + __sz {
                                    return Err(naclac_lang::prelude::NaclacError::InvalidInstructionData.err(0));
                                }
                                let __val = <#ty as naclac_lang::prelude::NaclacPod>::naclac_from_bytes(
                                    &instruction_data[__ix_offset..__ix_offset + __sz]
                                );
                                __ix_offset += __sz;
                                __val
                            };
                            #[cfg(not(feature = "pinocchio"))]
                            let #name = {
                                let mut __r: &[u8] = &instruction_data[__ix_offset..];
                                let __val = <#ty as naclac_lang::prelude::BorshDeserialize>::deserialize(&mut __r)
                                    .map_err(|_| naclac_lang::prelude::NaclacError::InvalidInstructionData.err(0))?;
                                __ix_offset = instruction_data.len() - __r.len();
                                __val
                            };
                        });
                    }
                }

                // Build the final deserialization block, prepending __ix_offset init
                // only when at least one non-slice argument was found.
                let _args_deserialization = if has_non_slice_args {
                    quote! {
                        let mut __ix_offset: usize = 8;
                        #( #deserialization_logic )*
                    }
                } else {
                    quote! { #( #deserialization_logic )* }
                };

                // Args are now local variables — reference directly (no __args.name)
                let arg_injections = arg_names.iter().map(|name| {
                    if slice_arg_names.contains(name) {
                        quote! { , &instruction_data[8..] }
                    } else {
                        quote! { , #name }
                    }
                });
                let arg_injections = quote! { #(#arg_injections)* };

                // --- THE DISPATCH FUNCTION ---
                let dispatch_func_name = format_ident!("__dispatch_{}", func_name);

                let return_ty = extract_result_return_type(&func.sig.output);
                let set_return_data_pinocchio = set_return_data_tokens(
                    &return_ty,
                    quote! { naclac_lang::prelude::pinocchio::cpi::set_return_data },
                );
                let set_return_data_solana = set_return_data_tokens(
                    &return_ty,
                    quote! { naclac_lang::solana_program::program::set_return_data },
                );

                // Pinocchio path: takes pre-walked &[AccountType] slice.
                // load_and_validate returns (accounts, remaining_slice, bumps).
                processed_content_items.push(syn::parse_quote! {
                    #[cfg(feature = "pinocchio")]
                    pub(crate) fn #dispatch_func_name(
                        program_id: &'static naclac_lang::prelude::Address,
                        __views: &'static [naclac_lang::prelude::AccountType],
                        instruction_data: &'static [u8],
                        __duplicates: Option<&naclac_lang::prelude::AccountBitvec>,
                    ) -> naclac_lang::prelude::ProgramResult {
                        #_args_deserialization
                        let (mut accounts, __rem_slice, bumps) = #ctx_struct::load_and_validate(
                            program_id,
                            __views,
                            instruction_data,
                            __duplicates,
                        )?;
                        let ctx = unsafe {
                            naclac_lang::prelude::Context::new(
                                program_id,
                                &mut accounts,
                                __rem_slice,
                                bumps,
                            )
                        };
                        let __result = #mod_name::#func_name(ctx #arg_injections);
                        #set_return_data_pinocchio
                        if __result.is_ok() {
                            accounts.teardown(program_id, &bumps)?;
                        }
                        __result.map(|_| ())
                    }
                });

                // Standard Solana path: takes pre-built &[AccountInfo].
                processed_content_items.push(syn::parse_quote! {
                    #[cfg(not(feature = "pinocchio"))]
                    pub(crate) fn #dispatch_func_name(
                        program_id: &naclac_lang::prelude::Address,
                        accounts: &[naclac_lang::prelude::AccountInfo],
                        instruction_data: &[u8],
                        __duplicates: Option<&naclac_lang::prelude::AccountBitvec>,
                    ) -> naclac_lang::prelude::Result {
                        #_args_deserialization
                        let (mut accounts, remaining_accounts, bumps) = #ctx_struct::load_and_validate(
                            program_id,
                            accounts,
                            instruction_data,
                            __duplicates,
                        )?;
                        let ctx = unsafe {
                            naclac_lang::prelude::Context::new(
                                program_id,
                                #ctx_struct::as_mut_payload(&mut accounts),
                                remaining_accounts,
                                bumps,
                            )
                        };
                        let __result = #mod_name::#func_name(ctx #arg_injections);
                        #set_return_data_solana
                        if __result.is_ok() {
                            #ctx_struct::teardown_payload(&mut accounts, program_id, &bumps)?;
                        }
                        __result.map(|_| ())
                    }
                });

                let disc_u64 = u64::from_le_bytes([b0, b1, b2, b3, b4, b5, b6, b7]);
                // --- THE MATCH ARM ---
                match_arms.push(quote! {
                    #disc_u64 => {
                        #[cfg(feature = "pinocchio")]
                        { #mod_name::#dispatch_func_name(program_id, __views, instruction_data, __dups) }
                        #[cfg(not(feature = "pinocchio"))]
                        { #mod_name::#dispatch_func_name(program_id, accounts, instruction_data, __dups_opt) }
                    }
                });
            }
            processed_content_items.push(Item::Fn(new_func));
        } else {
            processed_content_items.push(item.clone());
        }
    }

    // --- CPI GENERATION (Moved to SDK) ---
    // The cpi module is now generated in the Rust SDK, not in the program crate.

    // --- FINAL MACRO EXPANSION ---
    let expanded = quote! {
        #[cfg(all(not(feature = "no-entrypoint"), not(feature = "pinocchio")))]
        naclac_lang::solana_program::entrypoint!(process_instruction);

        // Pinocchio SIMD-0321 entrypoint — two-parameter form.
        // The BPF loader passes r1=input (accounts), r2=ix_data_ptr (instruction data).
        // This eliminates parse_ix_context: we get ix_data directly without scanning accounts.
        #[cfg(all(not(feature = "no-entrypoint"), feature = "pinocchio"))]
        #[no_mangle]
        pub unsafe extern "C" fn entrypoint(input: *mut u8, ix_data_ptr: *const u8) -> u64 {
            match process_instruction(input, ix_data_ptr) {
                Ok(()) => naclac_lang::pinocchio::SUCCESS,
                Err(e)  => e.into(),
            }
        }
        #[cfg(all(not(feature = "no-entrypoint"), feature = "pinocchio"))]
        naclac_lang::pinocchio::default_allocator!();

        // Unified Entrypoint — standard signature required by solana/pinocchio entrypoint! macro
        #[cfg(not(feature = "pinocchio"))]
        pub fn process_instruction(
            program_id: &naclac_lang::solana_program::pubkey::Pubkey,
            accounts: &[naclac_lang::solana_program::account_info::AccountInfo<'_>],
            instruction_data: &[u8],
        ) -> naclac_lang::prelude::Result {
            // SAFETY: The Solana runtime guarantees these references are valid for the
            // entire program invocation. We transmute the lifetime to 'static so the
            // inner dispatcher can safely bind them to Context<T> using 'static references.
            unsafe {
                let program_id: &'static naclac_lang::prelude::Address = core::mem::transmute(program_id);
                let accounts: &'static [naclac_lang::prelude::AccountInfo] = core::mem::transmute(accounts);
                let instruction_data: &'static [u8] = core::mem::transmute(instruction_data);
                process_instruction_inner(program_id, accounts, instruction_data)
            }
        }

        // SIMD-0321: BPF loader passes r2 = pointer to instruction data bytes.
        // Layout: [u64 ix_data_len][ix_data bytes...][program_id: 32 bytes]
        // ix_data_ptr points to ix_data[0]; len at ix_data_ptr-8; program_id at ix_data_ptr+len.
        #[cfg(feature = "pinocchio")]
        /// Unified Entrypoint for Pinocchio — parses raw runtime inputs.
        ///
        /// # Safety
        ///
        /// This function is unsafe because it dereferences raw pointers (`input` and `ix_data_ptr`)
        /// supplied directly by the Solana runtime BPF loader. The caller must ensure these
        /// pointers point to valid, aligned, and initialized memory.
        pub unsafe fn process_instruction(input: *mut u8, ix_data_ptr: *const u8) -> naclac_lang::prelude::ProgramResult {
            // 1. Read num_accounts from the first 8 bytes.
            let num_accounts = unsafe { *(input as *const u64) } as usize;
            // 2. Decode instruction data directly from r2 — no account scan needed.
            let instruction_data: &'static [u8] = unsafe {
                let len = *(ix_data_ptr.sub(8) as *const u64) as usize;
                core::slice::from_raw_parts(ix_data_ptr, len)
            };
            // 3. Program ID immediately follows instruction data bytes.
            let program_id: &'static naclac_lang::prelude::Address = unsafe {
                let len = *(ix_data_ptr.sub(8) as *const u64) as usize;
                &*(ix_data_ptr.add(len) as *const naclac_lang::prelude::Address)
            };
            process_instruction_inner(program_id, input, num_accounts, instruction_data)
        }

        #[cfg(feature = "pinocchio")]
        #[inline(always)]
        fn process_instruction_inner(
            program_id: &'static naclac_lang::prelude::Address,
            input: *mut u8,
            num_accounts: usize,
            instruction_data: &'static [u8],
        ) -> naclac_lang::prelude::ProgramResult {
            if instruction_data.len() < 8 {
                return Err(naclac_lang::prelude::NaclacError::InvalidInstructionData.err(0));
            }
            let instruction_discriminator = u64::from_le_bytes(unsafe {
                *(instruction_data.as_ptr() as *const [u8; 8])
            });
            // Pre-walk ALL accounts ONCE — O(num_accounts), no double-scan.
            // Stack-allocate 64 slots (Solana max accounts per tx).
            // MaybeUninit::uninit() is zero-cost — no initialization overhead.
            let mut __lookup = [core::mem::MaybeUninit::<naclac_lang::prelude::AccountView>::uninit(); 64];
            let mut __cursor = unsafe {
                naclac_lang::prelude::AccountCursor::new(
                    input,
                    __lookup.as_mut_ptr() as *mut naclac_lang::prelude::AccountView,
                )
            };
            let (__views, __dups): (&'static [naclac_lang::prelude::AccountType], Option<&naclac_lang::prelude::AccountBitvec>) = unsafe {
                let (raw, dups) = __cursor.walk_n(num_accounts);
                // SAFETY: AccountInfo is #[repr(transparent)] over AccountView.
                // __lookup lives in this frame which outlives all dispatch calls.
                (core::mem::transmute(raw), dups)
            };
            match instruction_discriminator {
                #(#match_arms),*
                _ => Err(naclac_lang::prelude::NaclacError::InvalidInstructionData.err(0)),
            }
        }

        #[cfg(not(feature = "pinocchio"))]
        #[inline(always)]
        fn process_instruction_inner(
            program_id: &'static naclac_lang::prelude::Address,
            accounts: &'static [naclac_lang::prelude::AccountInfo],
            instruction_data: &'static [u8],
        ) -> naclac_lang::prelude::Result {
            if instruction_data.len() < 8 {
                return Err(naclac_lang::prelude::NaclacError::InvalidInstructionData.err(0));
            }
            let instruction_discriminator = u64::from_le_bytes(unsafe {
                *(instruction_data.as_ptr() as *const [u8; 8])
            });
            let mut __has_dups = false;
            let mut __dups = naclac_lang::prelude::AccountBitvec::default();
            for i in 0..accounts.len() {
                for j in 0..i {
                    if accounts[i].key == accounts[j].key {
                        __dups.set(i as u8);
                        __dups.set(j as u8);
                        __has_dups = true;
                    }
                }
            }
            let __dups_opt = if __has_dups { Some(&__dups) } else { None };
            match instruction_discriminator {
                #(#match_arms),*
                _ => Err(naclac_lang::prelude::NaclacError::InvalidInstructionData.err(0)),
            }
        }



        // Re-inject the developer's original module logic.
        #mod_vis mod #mod_name {
            use super::*;
            #(#processed_content_items)*
        }

    };

    expanded.into()
}
