// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#![cfg_attr(all(feature = "cpi", feature = "pinocchio"), no_std)]

#[cfg(feature = "cpi")]
pub use naclac_lang::prelude as sdk_core_cpi;
#[cfg(feature = "offchain")]
pub use naclac_client as sdk_core_offchain;

#[cfg(feature = "offchain")]
pub mod components;
pub mod instructions;
pub mod types;

#[cfg(feature = "offchain")]
pub use components::*;
pub use instructions::*;
pub use types::*;

#[macro_export]
macro_rules! declare_id {
    ($id:expr) => {};
}

declare_id!("2NRNEsBPXjtD4GzyGyesA7N69KY9pZBo4cpj5dYjhu2K");

#[cfg(feature = "offchain")]
pub fn get_big_pda(
    program_id: &naclac_client::Address
) -> (naclac_client::Address, u8) {
    naclac_client::Address::find_program_address(
        &[
            &[98, 105, 103],
        ],
        program_id,
    )
}

#[cfg(feature = "offchain")]
pub fn get_small_pda(
    program_id: &naclac_client::Address
) -> (naclac_client::Address, u8) {
    naclac_client::Address::find_program_address(
        &[
            &[115, 109, 97, 108, 108],
        ],
        program_id,
    )
}

#[cfg(feature = "cpi")]
#[derive(Clone, Copy)]
pub struct StackSafety;

#[cfg(feature = "cpi")]
impl sdk_core_cpi::Id for StackSafety {
    fn id() -> sdk_core_cpi::Address {
        sdk_core_cpi::Address::new_from_array([20, 88, 111, 82, 192, 221, 82, 247, 124, 107, 5, 182, 9, 17, 70, 227, 52, 164, 2, 149, 254, 121, 101, 59, 101, 17, 108, 95, 144, 36, 3, 220])
    }
}

