// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
pub const PROGRAM_ID: naclac_client::Address = naclac_client::Address::new_from_array([
    57, 67, 163, 161, 67, 180, 47, 127, 193, 192, 152, 67, 197, 225, 67, 171, 65, 226, 109, 163, 237, 173, 75, 105, 144, 117, 37, 194, 31, 61, 224, 133
]);

#[cfg(not(feature = "offchain"))]
pub const PROGRAM_ID: crate::sdk_core_cpi::Address = crate::sdk_core_cpi::Address::new_from_array([
    57, 67, 163, 161, 67, 180, 47, 127, 193, 192, 152, 67, 197, 225, 67, 171, 65, 226, 109, 163, 237, 173, 75, 105, 144, 117, 37, 194, 31, 61, 224, 133
]);

pub const SEED_COUNTER: &[u8] = &[99, 111, 117, 110, 116, 101, 114, 95, 118, 50];
