// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#![cfg_attr(all(feature = "cpi", feature = "pinocchio"), no_std)]

#[cfg(feature = "cpi")]
pub use naclac_lang::prelude as sdk_core;
#[cfg(all(feature = "offchain", not(feature = "cpi")))]
pub use naclac_client as sdk_core;

#[cfg(feature = "offchain")]
pub mod components;
pub mod instructions;
pub mod types;

#[cfg(feature = "offchain")]
pub use components::*;
pub use instructions::*;
pub use types::*;

#[macro_export]
macro_rules! declare_id {
    ($id:expr) => {};
}

declare_id!("9Ka4d8GiqS72JDJNqNFvUpXBS1LZ6BTCskjCaCS34vuE");

#[cfg(feature = "offchain")]
pub fn get_pool_state_pda(
    program_id: &naclac_client::Address,
    token_a_mint: &naclac_client::Address,
    token_b_mint: &naclac_client::Address,
    id: u64
) -> (naclac_client::Address, u8) {
    let id_bytes = id.to_le_bytes();
    naclac_client::Address::find_program_address(
        &[
            &[112, 111, 111, 108],
            token_a_mint.as_ref(),
            token_b_mint.as_ref(),
            &id_bytes,
        ],
        program_id,
    )
}

#[cfg(feature = "cpi")]
#[derive(Clone, Copy)]
pub struct Amm;

#[cfg(feature = "cpi")]
impl sdk_core::Id for Amm {
    fn id() -> sdk_core::Address {
        sdk_core::Address::new_from_array([123, 159, 85, 117, 61, 191, 37, 235, 151, 189, 246, 158, 253, 240, 1, 123, 204, 76, 215, 48, 217, 20, 189, 201, 65, 196, 255, 157, 61, 147, 35, 193])
    }
}

