// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#![cfg_attr(all(feature = "cpi", feature = "pinocchio"), no_std)]

#[cfg(feature = "cpi")]
pub use naclac_lang::prelude as sdk_core_cpi;
#[cfg(feature = "offchain")]
pub use naclac_client as sdk_core_offchain;

#[cfg(feature = "offchain")]
pub mod components;
pub mod instructions;
pub mod types;

#[cfg(feature = "offchain")]
pub use components::*;
pub use instructions::*;
pub use types::*;

#[macro_export]
macro_rules! declare_id {
    ($id:expr) => {};
}

declare_id!("6queAeH2Cq6WPuq6tpgRFBtFBanSNW3zdc9Y8dm4g7oF");

#[cfg(feature = "offchain")]
pub fn get_config_pda(
    program_id: &naclac_client::Address
) -> (naclac_client::Address, u8) {
    naclac_client::Address::find_program_address(
        &[
            &[99, 111, 110, 102, 105, 103],
        ],
        program_id,
    )
}

#[cfg(feature = "offchain")]
pub fn get_vault_pda(
    program_id: &naclac_client::Address
) -> (naclac_client::Address, u8) {
    naclac_client::Address::find_program_address(
        &[
            &[118, 97, 117, 108, 116],
        ],
        program_id,
    )
}

#[cfg(feature = "cpi")]
#[derive(Clone, Copy)]
pub struct Discriminator;

#[cfg(feature = "cpi")]
impl sdk_core_cpi::Id for Discriminator {
    fn id() -> sdk_core_cpi::Address {
        sdk_core_cpi::Address::new_from_array([86, 209, 213, 168, 202, 233, 209, 197, 246, 69, 50, 217, 144, 28, 235, 204, 250, 10, 126, 0, 87, 108, 44, 226, 226, 109, 235, 170, 14, 254, 169, 154])
    }
}

