// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
#[cfg(feature = "borsh")]
use crate::sdk_core_offchain::borsh::BorshSerialize;
#[cfg(feature = "offchain")]
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_offchain::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Clone, Debug))]
pub struct CreateMint2022WithMetadataPointerAndMetadataIxArgs {
    pub args: crate::types::CreateMint2022WithMetadataPointerAndMetadataArgs,
}

#[cfg(feature = "cpi")]
#[cfg(feature = "borsh")]
use crate::sdk_core_cpi::borsh::BorshSerialize;
#[cfg(feature = "cpi")]
#[cfg_attr(feature = "borsh", derive(Clone, Debug, BorshSerialize))]
#[cfg_attr(feature = "borsh", borsh(crate = "crate::sdk_core_cpi::borsh"))]
#[cfg_attr(not(feature = "borsh"), derive(Clone, Debug))]
pub struct CreateMint2022WithMetadataPointerAndMetadataCpiIxArgs {
    pub args: crate::types::CreateMint2022WithMetadataPointerAndMetadataArgsCpi,
}

#[cfg(feature = "offchain")]
pub struct CreateMint2022WithMetadataPointerAndMetadataAccounts {
    pub payer: naclac_client::Address,
    /// SAFETY: allocated and initialized entirely by hand in the handler
    /// body below — there is no naclac `Discriminator` to check since this
    /// is a raw SPL `Mint` + `MetadataPointer` + `TokenMetadata` layout, not
    /// a naclac component.
    pub mint: naclac_client::Address,
    pub mint_authority: naclac_client::Address,
    pub token_program: naclac_client::Address,
    pub system_program: naclac_client::Address,
}

#[cfg(feature = "offchain")]
pub fn build_create_mint2022_with_metadata_pointer_and_metadata<'a>(
    provider: &'a naclac_client::NaclacProvider,
    program_id: naclac_client::Address,
    args: crate::types::CreateMint2022WithMetadataPointerAndMetadataArgs,
    accounts: CreateMint2022WithMetadataPointerAndMetadataAccounts,
) -> naclac_client::InstructionBuilder<'a> {
    let mut ix_data = crate::sdk_core_offchain::vec![184, 130, 183, 108, 54, 64, 161, 161];
    let args = CreateMint2022WithMetadataPointerAndMetadataIxArgs {
        args,
    };
    #[cfg(not(feature = "borsh"))]
    {
        ix_data.extend_from_slice(crate::sdk_core_offchain::bytemuck::bytes_of(&args.args.id));
        ix_data.extend_from_slice(crate::sdk_core_offchain::bytemuck::bytes_of(&args.args.mint_bump));
        ix_data.extend_from_slice(crate::sdk_core_offchain::bytemuck::bytes_of(&args.args.decimals));
        ix_data.extend_from_slice(&(args.args.name.len() as u32).to_le_bytes());
        ix_data.extend_from_slice(args.args.name.as_bytes());
        ix_data.extend_from_slice(&(args.args.symbol.len() as u32).to_le_bytes());
        ix_data.extend_from_slice(args.args.symbol.as_bytes());
        ix_data.extend_from_slice(&(args.args.uri.len() as u32).to_le_bytes());
        ix_data.extend_from_slice(args.args.uri.as_bytes());
    }
    #[cfg(feature = "borsh")]
    {
        crate::sdk_core_offchain::borsh::BorshSerialize::serialize(&args, &mut ix_data).unwrap();
    }
    naclac_client::InstructionBuilder::new(provider, program_id, ix_data)
        .account(naclac_client::AccountMeta { address: accounts.payer, is_signer: true, is_writable: true }, "payer")
        .account(naclac_client::AccountMeta { address: accounts.mint, is_signer: false, is_writable: true }, "mint")
        .account(naclac_client::AccountMeta { address: accounts.mint_authority, is_signer: false, is_writable: false }, "mint_authority")
        .account(naclac_client::AccountMeta { address: accounts.token_program, is_signer: false, is_writable: false }, "token_program")
        .account(naclac_client::AccountMeta { address: accounts.system_program, is_signer: false, is_writable: false }, "system_program")
}

#[cfg(feature = "cpi")]
pub struct CreateMint2022WithMetadataPointerAndMetadataCpiAccounts<'a> {
    pub payer: crate::sdk_core_cpi::CpiHandleMut<'a>,
    /// SAFETY: allocated and initialized entirely by hand in the handler
    /// body below — there is no naclac `Discriminator` to check since this
    /// is a raw SPL `Mint` + `MetadataPointer` + `TokenMetadata` layout, not
    /// a naclac component.
    pub mint: crate::sdk_core_cpi::CpiHandleMut<'a>,
    pub mint_authority: crate::sdk_core_cpi::CpiHandle<'a>,
    pub token_program: crate::sdk_core_cpi::CpiHandle<'a>,
    pub system_program: crate::sdk_core_cpi::CpiHandle<'a>,
}

#[cfg(feature = "cpi")]
pub struct CreateMint2022WithMetadataPointerAndMetadataCpiCall<'a> {
    pub accounts: CreateMint2022WithMetadataPointerAndMetadataCpiAccounts<'a>,
    pub args: crate::types::CreateMint2022WithMetadataPointerAndMetadataArgsCpi,
    pub signer_seeds: &'a [&'a [&'a [u8]]],
    pub remaining_accounts: &'a [(crate::sdk_core_cpi::AccountInfo, bool, bool)],
}

#[cfg(feature = "cpi")]
pub trait CreateMint2022WithMetadataPointerAndMetadataCpi<'info> {
    fn create_mint2022_with_metadata_pointer_and_metadata<'a>(
        &self,
        accounts: CreateMint2022WithMetadataPointerAndMetadataCpiAccounts<'a>,
        args: crate::types::CreateMint2022WithMetadataPointerAndMetadataArgsCpi
    ) -> crate::sdk_core_cpi::Result<()> {
        self.create_mint2022_with_metadata_pointer_and_metadata_with_remaining_accounts(CreateMint2022WithMetadataPointerAndMetadataCpiCall {
        accounts,
        args,
        signer_seeds: &[],
        remaining_accounts: &[],
    })
    }

    fn create_mint2022_with_metadata_pointer_and_metadata_signed<'a>(
        &self,
        accounts: CreateMint2022WithMetadataPointerAndMetadataCpiAccounts<'a>,
        args: crate::types::CreateMint2022WithMetadataPointerAndMetadataArgsCpi,
        signer_seeds: &[&[&[u8]]]
    ) -> crate::sdk_core_cpi::Result<()> {
        self.create_mint2022_with_metadata_pointer_and_metadata_with_remaining_accounts(CreateMint2022WithMetadataPointerAndMetadataCpiCall {
        accounts,
        args,
        signer_seeds,
        remaining_accounts: &[],
    })
    }

    fn create_mint2022_with_metadata_pointer_and_metadata_with_remaining_accounts<'a>(
        &self,
        call: CreateMint2022WithMetadataPointerAndMetadataCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()>;

}

#[cfg(feature = "cpi")]
impl<'info> CreateMint2022WithMetadataPointerAndMetadataCpi<'info> for crate::sdk_core_cpi::Program<crate::Token> {
    fn create_mint2022_with_metadata_pointer_and_metadata_with_remaining_accounts<'a>(
        &self,
        call: CreateMint2022WithMetadataPointerAndMetadataCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()> {
        let CreateMint2022WithMetadataPointerAndMetadataCpiCall { accounts, args, signer_seeds, remaining_accounts } = call;
        let args = CreateMint2022WithMetadataPointerAndMetadataCpiIxArgs {
            args,
        };
        let mut ix_data = crate::sdk_core_cpi::Vec::new();
        ix_data.extend_from_slice(&[184, 130, 183, 108, 54, 64, 161, 161]);
        #[cfg(not(feature = "borsh"))]
        {
        ix_data.extend_from_slice(crate::sdk_core_cpi::bytemuck::bytes_of(&args.args.id));
        ix_data.extend_from_slice(crate::sdk_core_cpi::bytemuck::bytes_of(&args.args.mint_bump));
        ix_data.extend_from_slice(crate::sdk_core_cpi::bytemuck::bytes_of(&args.args.decimals));
        ix_data.extend_from_slice(&(args.args.name.len() as u32).to_le_bytes());
        ix_data.extend_from_slice(args.args.name.as_bytes());
        ix_data.extend_from_slice(&(args.args.symbol.len() as u32).to_le_bytes());
        ix_data.extend_from_slice(args.args.symbol.as_bytes());
        ix_data.extend_from_slice(&(args.args.uri.len() as u32).to_le_bytes());
        ix_data.extend_from_slice(args.args.uri.as_bytes());
        }
        #[cfg(feature = "borsh")]
        {
            crate::sdk_core_cpi::borsh::BorshSerialize::serialize(&args, &mut ix_data).unwrap();
        }
        #[cfg(feature = "pinocchio")]
        {
            let mut metas_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount>::uninit() }; 32];
            let mut idx = 0;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable_signer(accounts.payer.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(accounts.mint.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.mint_authority.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.token_program.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.system_program.info.view.address()));
            idx += 1;
            for (acc, is_writable, is_signer) in remaining_accounts {
                if idx >= 32 { break; }
                let meta = if *is_writable {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(acc.view.address())
                    }
                } else {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(acc.view.address())
                    }
                };
                metas_arr[idx].write(meta);
                idx += 1;
            }
            let account_metas = unsafe { core::slice::from_raw_parts(metas_arr.as_ptr() as *const crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount, idx) };
            let program_id_address = self.address();
            let instruction = crate::sdk_core_cpi::pinocchio::instruction::InstructionView {
                program_id: program_id_address.as_address(),
                accounts: account_metas,
                data: &ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.payer));
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.mint));
            h_idx += 1;
            handles_arr[h_idx].write(accounts.mint_authority);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.token_program);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.system_program);
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed_pinocchio_handles(&instruction, account_handles, signer_seeds)
        }
        #[cfg(not(feature = "pinocchio"))]
        {
            use crate::sdk_core_cpi::ToAddress;
            let mut account_metas = crate::sdk_core_cpi::vec![
                ::naclac_lang::solana_program::instruction::AccountMeta::new(accounts.payer.address(), true),
                ::naclac_lang::solana_program::instruction::AccountMeta::new(accounts.mint.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.mint_authority.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.token_program.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.system_program.address(), false),
            ];
            for (acc, is_writable, is_signer) in remaining_accounts {
                let meta = if *is_writable {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new(acc.address(), *is_signer)
                } else {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(acc.address(), *is_signer)
                };
                account_metas.push(meta);
            }
            let instruction = ::naclac_lang::solana_program::instruction::Instruction {
                program_id: self.address(),
                accounts: account_metas,
                data: ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.payer));
            h_idx += 1;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.mint));
            h_idx += 1;
            handles_arr[h_idx].write(accounts.mint_authority);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.token_program);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.system_program);
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed(&instruction, account_handles, signer_seeds)
        }
    }
}

