// 🛑 DO NOT EDIT - AUTO-GENERATED BY NACLAC
// Re-run `naclac generate` to refresh this file.

#[cfg(feature = "offchain")]
pub struct SetTokenAccountOwnerAccounts {
    pub vault: naclac_client::Address,
    pub current_owner: naclac_client::Address,
    /// SAFETY: only used as an address — its own key becomes the vault's new
    /// owner via `set_authority_signed` below; its data is never read or
    /// deserialized.
    pub new_owner: naclac_client::Address,
    pub token_program: naclac_client::Address,
}

#[cfg(feature = "offchain")]
pub fn build_set_token_account_owner<'a>(
    provider: &'a naclac_client::NaclacProvider,
    program_id: naclac_client::Address,
    accounts: SetTokenAccountOwnerAccounts,
) -> naclac_client::InstructionBuilder<'a> {
    let ix_data = crate::sdk_core_offchain::vec![234, 23, 62, 251, 44, 39, 183, 236];
    naclac_client::InstructionBuilder::new(provider, program_id, ix_data)
        .account(naclac_client::AccountMeta { address: accounts.vault, is_signer: false, is_writable: true }, "vault")
        .account(naclac_client::AccountMeta { address: accounts.current_owner, is_signer: true, is_writable: false }, "current_owner")
        .account(naclac_client::AccountMeta { address: accounts.new_owner, is_signer: false, is_writable: false }, "new_owner")
        .account(naclac_client::AccountMeta { address: accounts.token_program, is_signer: false, is_writable: false }, "token_program")
}

#[cfg(feature = "cpi")]
pub struct SetTokenAccountOwnerCpiAccounts<'a> {
    pub vault: crate::sdk_core_cpi::CpiHandleMut<'a>,
    pub current_owner: crate::sdk_core_cpi::CpiHandle<'a>,
    /// SAFETY: only used as an address — its own key becomes the vault's new
    /// owner via `set_authority_signed` below; its data is never read or
    /// deserialized.
    pub new_owner: crate::sdk_core_cpi::CpiHandle<'a>,
    pub token_program: crate::sdk_core_cpi::CpiHandle<'a>,
}

#[cfg(feature = "cpi")]
pub struct SetTokenAccountOwnerCpiCall<'a> {
    pub accounts: SetTokenAccountOwnerCpiAccounts<'a>,
    pub signer_seeds: &'a [&'a [&'a [u8]]],
    pub remaining_accounts: &'a [(crate::sdk_core_cpi::AccountInfo, bool, bool)],
}

#[cfg(feature = "cpi")]
pub trait SetTokenAccountOwnerCpi<'info> {
    fn set_token_account_owner<'a>(
        &self,
        accounts: SetTokenAccountOwnerCpiAccounts<'a>
    ) -> crate::sdk_core_cpi::Result<()> {
        self.set_token_account_owner_with_remaining_accounts(SetTokenAccountOwnerCpiCall {
        accounts,
        signer_seeds: &[],
        remaining_accounts: &[],
    })
    }

    fn set_token_account_owner_signed<'a>(
        &self,
        accounts: SetTokenAccountOwnerCpiAccounts<'a>,
        signer_seeds: &[&[&[u8]]]
    ) -> crate::sdk_core_cpi::Result<()> {
        self.set_token_account_owner_with_remaining_accounts(SetTokenAccountOwnerCpiCall {
        accounts,
        signer_seeds,
        remaining_accounts: &[],
    })
    }

    fn set_token_account_owner_with_remaining_accounts<'a>(
        &self,
        call: SetTokenAccountOwnerCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()>;

}

#[cfg(feature = "cpi")]
impl<'info> SetTokenAccountOwnerCpi<'info> for crate::sdk_core_cpi::Program<crate::Token> {
    fn set_token_account_owner_with_remaining_accounts<'a>(
        &self,
        call: SetTokenAccountOwnerCpiCall<'a>
    ) -> crate::sdk_core_cpi::Result<()> {
        let SetTokenAccountOwnerCpiCall { accounts, signer_seeds, remaining_accounts } = call;
        let mut ix_data = crate::sdk_core_cpi::Vec::new();
        ix_data.extend_from_slice(&[234, 23, 62, 251, 44, 39, 183, 236]);
        #[cfg(feature = "pinocchio")]
        {
            let mut metas_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount>::uninit() }; 32];
            let mut idx = 0;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(accounts.vault.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly_signer(accounts.current_owner.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.new_owner.info.view.address()));
            idx += 1;
            metas_arr[idx].write(crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(accounts.token_program.info.view.address()));
            idx += 1;
            for (acc, is_writable, is_signer) in remaining_accounts {
                if idx >= 32 { break; }
                let meta = if *is_writable {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::writable(acc.view.address())
                    }
                } else {
                    if *is_signer {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly_signer(acc.view.address())
                    } else {
                        crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount::readonly(acc.view.address())
                    }
                };
                metas_arr[idx].write(meta);
                idx += 1;
            }
            let account_metas = unsafe { core::slice::from_raw_parts(metas_arr.as_ptr() as *const crate::sdk_core_cpi::pinocchio::instruction::InstructionAccount, idx) };
            let program_id_address = self.address();
            let instruction = crate::sdk_core_cpi::pinocchio::instruction::InstructionView {
                program_id: program_id_address.as_address(),
                accounts: account_metas,
                data: &ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.vault));
            h_idx += 1;
            handles_arr[h_idx].write(accounts.current_owner);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.new_owner);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.token_program);
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed_pinocchio_handles(&instruction, account_handles, signer_seeds)
        }
        #[cfg(not(feature = "pinocchio"))]
        {
            use crate::sdk_core_cpi::ToAddress;
            let mut account_metas = crate::sdk_core_cpi::vec![
                ::naclac_lang::solana_program::instruction::AccountMeta::new(accounts.vault.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.current_owner.address(), true),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.new_owner.address(), false),
                ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(accounts.token_program.address(), false),
            ];
            for (acc, is_writable, is_signer) in remaining_accounts {
                let meta = if *is_writable {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new(acc.address(), *is_signer)
                } else {
                    ::naclac_lang::solana_program::instruction::AccountMeta::new_readonly(acc.address(), *is_signer)
                };
                account_metas.push(meta);
            }
            let instruction = ::naclac_lang::solana_program::instruction::Instruction {
                program_id: self.address(),
                accounts: account_metas,
                data: ix_data,
            };
            let mut handles_arr = [const { core::mem::MaybeUninit::<crate::sdk_core_cpi::CpiHandle>::uninit() }; 32];
            let mut h_idx = 0;
            handles_arr[h_idx].write(crate::sdk_core_cpi::CpiHandle::from(accounts.vault));
            h_idx += 1;
            handles_arr[h_idx].write(accounts.current_owner);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.new_owner);
            h_idx += 1;
            handles_arr[h_idx].write(accounts.token_program);
            h_idx += 1;
            for (acc, _, _) in remaining_accounts {
                if h_idx >= 32 { break; }
                handles_arr[h_idx].write(crate::sdk_core_cpi::ToCpiHandle::to_cpi_handle(acc));
                h_idx += 1;
            }
            let account_handles = unsafe { core::slice::from_raw_parts(handles_arr.as_ptr() as *const crate::sdk_core_cpi::CpiHandle, h_idx) };
            crate::sdk_core_cpi::cpi::invoke_signed(&instruction, account_handles, signer_seeds)
        }
    }
}

